import type { OSManifest } from "@appneurox/schemas";

export const peopleManifest = {
  id: "peopleos",
  name: "PeopleOS",
  packageName: "@appneurox/peopleos",
  version: "1.0.0",
  description: "Employee management, teams, attendance, leave requests, shifts, and workforce operations",
  namespace: "people",
  mode: "both" as const,
  dependencies: {
    required: [
      "@appneurox/platformos",
      "@appneurox/securityos",
      "@appneurox/commandos",
    ],
    optional: [
      "@appneurox/businessos",
      "@appneurox/automationos",
    ] as string[],
  },
  models: [
    {
      name: "Employee",
      description: "An employee record in the organization",
      fields: {
        id: { type: "uuid" as const, required: true, description: "Employee ID" },
        tenantId: { type: "uuid" as const, required: true, description: "Tenant ID" },
        firstName: { type: "string" as const, required: true, maxLength: 100, description: "First name" },
        lastName: { type: "string" as const, required: true, maxLength: 100, description: "Last name" },
        email: { type: "string" as const, required: true, maxLength: 255, description: "Work email address" },
        phone: { type: "string" as const, maxLength: 20, description: "Phone number" },
        department: { type: "string" as const, maxLength: 100, description: "Department name" },
        jobTitle: { type: "string" as const, maxLength: 150, description: "Job title" },
        status: { type: "enum" as const, required: true, enumValues: ["active", "on_leave", "inactive", "terminated"], description: "Employment status" },
        teamId: { type: "uuid" as const, description: "Primary team ID" },
        managerId: { type: "uuid" as const, description: "Reporting manager employee ID" },
        hireDate: { type: "date" as const, description: "Date of hire" },
        createdAt: { type: "timestamp" as const, description: "Created timestamp" },
        updatedAt: { type: "timestamp" as const, description: "Updated timestamp" },
      },
      timestamps: false,
      softDelete: false,
    },
    {
      name: "Team",
      description: "A team within the organization",
      fields: {
        id: { type: "uuid" as const, required: true, description: "Team ID" },
        tenantId: { type: "uuid" as const, required: true, description: "Tenant ID" },
        name: { type: "string" as const, required: true, maxLength: 200, description: "Team name" },
        description: { type: "text" as const, description: "Team description" },
        leadId: { type: "uuid" as const, description: "Team lead employee ID" },
        department: { type: "string" as const, maxLength: 100, description: "Department" },
        status: { type: "enum" as const, enumValues: ["active", "inactive"], description: "Team status" },
        createdAt: { type: "timestamp" as const, description: "Created timestamp" },
        updatedAt: { type: "timestamp" as const, description: "Updated timestamp" },
      },
      timestamps: false,
      softDelete: false,
    },
    {
      name: "RoleProfile",
      description: "A role profile defining permissions and responsibilities",
      fields: {
        id: { type: "uuid" as const, required: true, description: "Role profile ID" },
        tenantId: { type: "uuid" as const, required: true, description: "Tenant ID" },
        name: { type: "string" as const, required: true, maxLength: 150, description: "Role name" },
        description: { type: "text" as const, description: "Role description" },
        level: { type: "enum" as const, enumValues: ["junior", "mid", "senior", "lead", "manager", "director", "vp", "c_suite"], description: "Seniority level" },
        permissions: { type: "json" as const, description: "Role permissions list" },
        createdAt: { type: "timestamp" as const, description: "Created timestamp" },
        updatedAt: { type: "timestamp" as const, description: "Updated timestamp" },
      },
      timestamps: false,
      softDelete: false,
    },
    {
      name: "Attendance",
      description: "An attendance record for an employee",
      fields: {
        id: { type: "uuid" as const, required: true, description: "Attendance ID" },
        tenantId: { type: "uuid" as const, required: true, description: "Tenant ID" },
        employeeId: { type: "uuid" as const, required: true, description: "Employee ID" },
        date: { type: "date" as const, required: true, description: "Attendance date" },
        clockIn: { type: "timestamp" as const, description: "Clock-in time" },
        clockOut: { type: "timestamp" as const, description: "Clock-out time" },
        status: { type: "enum" as const, required: true, enumValues: ["present", "absent", "late", "half_day", "on_leave", "holiday"], description: "Attendance status" },
        notes: { type: "text" as const, description: "Attendance notes" },
        createdAt: { type: "timestamp" as const, description: "Created timestamp" },
        updatedAt: { type: "timestamp" as const, description: "Updated timestamp" },
      },
      timestamps: false,
      softDelete: false,
    },
    {
      name: "LeaveRequest",
      description: "A leave request submitted by an employee",
      fields: {
        id: { type: "uuid" as const, required: true, description: "Leave request ID" },
        tenantId: { type: "uuid" as const, required: true, description: "Tenant ID" },
        employeeId: { type: "uuid" as const, required: true, description: "Requesting employee ID" },
        type: { type: "enum" as const, required: true, enumValues: ["vacation", "sick", "personal", "maternity", "paternity", "bereavement", "unpaid"], description: "Leave type" },
        status: { type: "enum" as const, required: true, enumValues: ["pending", "approved", "rejected", "cancelled"], description: "Request status" },
        startDate: { type: "date" as const, required: true, description: "Leave start date" },
        endDate: { type: "date" as const, required: true, description: "Leave end date" },
        reason: { type: "text" as const, description: "Reason for leave" },
        approverId: { type: "uuid" as const, description: "Approving manager employee ID" },
        approvedAt: { type: "timestamp" as const, description: "Approval timestamp" },
        createdAt: { type: "timestamp" as const, description: "Created timestamp" },
        updatedAt: { type: "timestamp" as const, description: "Updated timestamp" },
      },
      timestamps: false,
      softDelete: false,
    },
    {
      name: "Shift",
      description: "A work shift assignment",
      fields: {
        id: { type: "uuid" as const, required: true, description: "Shift ID" },
        tenantId: { type: "uuid" as const, required: true, description: "Tenant ID" },
        employeeId: { type: "uuid" as const, required: true, description: "Assigned employee ID" },
        date: { type: "date" as const, required: true, description: "Shift date" },
        startTime: { type: "timestamp" as const, required: true, description: "Shift start time" },
        endTime: { type: "timestamp" as const, required: true, description: "Shift end time" },
        type: { type: "enum" as const, enumValues: ["morning", "afternoon", "night", "split", "on_call"], description: "Shift type" },
        location: { type: "string" as const, maxLength: 200, description: "Work location" },
        notes: { type: "text" as const, description: "Shift notes" },
        createdAt: { type: "timestamp" as const, description: "Created timestamp" },
        updatedAt: { type: "timestamp" as const, description: "Updated timestamp" },
      },
      timestamps: false,
      softDelete: false,
    },
  ],
  commands: [
    {
      name: "people.employee.create",
      description: "Create a new employee record",
      input: {
        firstName: { type: "string" as const, required: true, description: "First name" },
        lastName: { type: "string" as const, required: true, description: "Last name" },
        email: { type: "string" as const, required: true, description: "Work email" },
        phone: { type: "string" as const, description: "Phone number" },
        department: { type: "string" as const, description: "Department" },
        jobTitle: { type: "string" as const, description: "Job title" },
        teamId: { type: "uuid" as const, description: "Team ID" },
        managerId: { type: "uuid" as const, description: "Manager employee ID" },
        hireDate: { type: "date" as const, description: "Hire date" },
      },
      output: {
        id: { type: "uuid" as const, required: true, description: "Created employee ID" },
        status: { type: "enum" as const, required: true, enumValues: ["active"] },
      },
      auth: { required: true, permissions: ["people.employees.create"] },
      audit: true,
      idempotent: false,
      async: false,
      event: "people.employee.created",
    },
    {
      name: "people.employee.invite",
      description: "Invite a new employee to the platform",
      input: {
        email: { type: "string" as const, required: true, description: "Email to invite" },
        firstName: { type: "string" as const, required: true, description: "First name" },
        lastName: { type: "string" as const, required: true, description: "Last name" },
        teamId: { type: "uuid" as const, description: "Team ID" },
        jobTitle: { type: "string" as const, description: "Job title" },
      },
      output: {
        id: { type: "uuid" as const, required: true, description: "Created employee ID" },
        status: { type: "enum" as const, required: true, enumValues: ["active"] },
        invitationSent: { type: "boolean" as const, required: true },
      },
      auth: { required: true, permissions: ["people.employees.create"] },
      audit: true,
      idempotent: false,
      async: false,
      event: "people.employee.created",
    },
    {
      name: "people.team.create",
      description: "Create a new team",
      input: {
        name: { type: "string" as const, required: true, description: "Team name" },
        description: { type: "text" as const, description: "Team description" },
        leadId: { type: "uuid" as const, description: "Team lead employee ID" },
        department: { type: "string" as const, description: "Department" },
      },
      output: {
        id: { type: "uuid" as const, required: true, description: "Created team ID" },
        status: { type: "enum" as const, required: true, enumValues: ["active"] },
      },
      auth: { required: true, permissions: ["people.teams.manage"] },
      audit: true,
      idempotent: false,
      async: false,
    },
    {
      name: "people.attendance.record",
      description: "Record attendance for an employee",
      input: {
        employeeId: { type: "uuid" as const, required: true, description: "Employee ID" },
        date: { type: "date" as const, required: true, description: "Attendance date" },
        clockIn: { type: "timestamp" as const, description: "Clock-in time" },
        clockOut: { type: "timestamp" as const, description: "Clock-out time" },
        status: { type: "enum" as const, required: true, enumValues: ["present", "absent", "late", "half_day", "on_leave", "holiday"], description: "Attendance status" },
        notes: { type: "text" as const, description: "Notes" },
      },
      output: {
        id: { type: "uuid" as const, required: true, description: "Attendance record ID" },
        status: { type: "enum" as const, required: true, enumValues: ["present", "absent", "late", "half_day", "on_leave", "holiday"] },
      },
      auth: { required: true, permissions: ["people.attendance.record"] },
      audit: true,
      idempotent: false,
      async: false,
      event: "people.attendance.recorded",
    },
    {
      name: "people.leave.request",
      description: "Submit a leave request",
      input: {
        employeeId: { type: "uuid" as const, required: true, description: "Employee ID" },
        type: { type: "enum" as const, required: true, enumValues: ["vacation", "sick", "personal", "maternity", "paternity", "bereavement", "unpaid"], description: "Leave type" },
        startDate: { type: "date" as const, required: true, description: "Leave start date" },
        endDate: { type: "date" as const, required: true, description: "Leave end date" },
        reason: { type: "text" as const, description: "Reason for leave" },
      },
      output: {
        id: { type: "uuid" as const, required: true, description: "Leave request ID" },
        status: { type: "enum" as const, required: true, enumValues: ["pending"] },
      },
      auth: { required: true, permissions: ["people.employees.create"] },
      audit: true,
      idempotent: false,
      async: false,
      event: "people.leave.requested",
    },
    {
      name: "people.leave.approve",
      description: "Approve a leave request",
      input: {
        id: { type: "uuid" as const, required: true, description: "Leave request ID" },
        approverId: { type: "uuid" as const, required: true, description: "Approving manager employee ID" },
      },
      output: {
        id: { type: "uuid" as const, required: true, description: "Leave request ID" },
        status: { type: "enum" as const, required: true, enumValues: ["approved"] },
      },
      auth: { required: true, permissions: ["people.leave.approve"] },
      audit: true,
      idempotent: false,
      async: false,
      event: "people.leave.approved",
    },
    {
      name: "people.shift.assign",
      description: "Assign a shift to an employee",
      input: {
        employeeId: { type: "uuid" as const, required: true, description: "Employee ID" },
        date: { type: "date" as const, required: true, description: "Shift date" },
        startTime: { type: "timestamp" as const, required: true, description: "Shift start time" },
        endTime: { type: "timestamp" as const, required: true, description: "Shift end time" },
        type: { type: "enum" as const, enumValues: ["morning", "afternoon", "night", "split", "on_call"], description: "Shift type" },
        location: { type: "string" as const, description: "Work location" },
        notes: { type: "text" as const, description: "Shift notes" },
      },
      output: {
        id: { type: "uuid" as const, required: true, description: "Shift ID" },
      },
      auth: { required: true, permissions: ["people.teams.manage"] },
      audit: true,
      idempotent: false,
      async: false,
    },
  ],
  events: {
    publishes: [
      {
        name: "people.employee.created",
        description: "An employee record was created",
        payload: {
          id: { type: "uuid" as const, required: true },
          firstName: { type: "string" as const, required: true },
          lastName: { type: "string" as const, required: true },
          status: { type: "enum" as const, required: true, enumValues: ["active"] },
        },
      },
      {
        name: "people.leave.requested",
        description: "A leave request was submitted",
        payload: {
          id: { type: "uuid" as const, required: true },
          employeeId: { type: "uuid" as const, required: true },
          type: { type: "enum" as const, required: true, enumValues: ["vacation", "sick", "personal", "maternity", "paternity", "bereavement", "unpaid"] },
          status: { type: "enum" as const, required: true, enumValues: ["pending"] },
        },
      },
      {
        name: "people.leave.approved",
        description: "A leave request was approved",
        payload: {
          id: { type: "uuid" as const, required: true },
          employeeId: { type: "uuid" as const, required: true },
          status: { type: "enum" as const, required: true, enumValues: ["approved"] },
          approverId: { type: "uuid" as const, required: true },
        },
      },
      {
        name: "people.attendance.recorded",
        description: "An attendance record was created",
        payload: {
          id: { type: "uuid" as const, required: true },
          employeeId: { type: "uuid" as const, required: true },
          status: { type: "enum" as const, required: true, enumValues: ["present", "absent", "late", "half_day", "on_leave", "holiday"] },
        },
      },
    ],
    subscribes: [] as unknown[],
  },
  permissions: [
    { name: "people.employees.read", resource: "people.employees", action: "read", scope: "global" as const, description: "Read employee records" },
    { name: "people.employees.create", resource: "people.employees", action: "create", scope: "global" as const, description: "Create employee records" },
    { name: "people.teams.manage", resource: "people.teams", action: "manage", scope: "global" as const, description: "Manage teams and shifts" },
    { name: "people.attendance.record", resource: "people.attendance", action: "create", scope: "global" as const, description: "Record attendance" },
    { name: "people.leave.approve", resource: "people.leave", action: "update", scope: "global" as const, description: "Approve leave requests" },
  ],
  roles: [
    { name: "people.admin", description: "Full access to people management", permissions: ["people.employees.read", "people.employees.create", "people.teams.manage", "people.attendance.record", "people.leave.approve"] },
    { name: "people.manager", description: "Manager access - approve leave, manage teams", permissions: ["people.employees.read", "people.teams.manage", "people.attendance.record", "people.leave.approve"] },
    { name: "people.employee", description: "Self-service employee access", permissions: ["people.employees.read", "people.attendance.record"] },
  ],
  workflows: [
    {
      name: "leave-approval",
      description: "Manager approval workflow for leave requests",
      trigger: { type: "event" as const, source: "people.leave.requested" },
      steps: [
        { name: "notify-manager", type: "action" as const, command: "people.leave.approve" },
      ],
      onError: "fail" as const,
    },
  ],
  api: {
    basePath: "/v1/people",
    version: "v1",
    endpoints: [
      { path: "/employees", method: "POST" as const, description: "Create an employee", auth: { required: true, permissions: ["people.employees.create"] }, tags: ["employees"] },
      { path: "/employees", method: "GET" as const, description: "List employees", auth: { required: true, permissions: ["people.employees.read"] }, tags: ["employees"] },
      { path: "/employees/{id}", method: "GET" as const, description: "Get an employee", auth: { required: true, permissions: ["people.employees.read"] }, tags: ["employees"] },
      { path: "/employees/{id}", method: "PATCH" as const, description: "Update an employee", auth: { required: true, permissions: ["people.employees.create"] }, tags: ["employees"] },
      { path: "/teams", method: "POST" as const, description: "Create a team", auth: { required: true, permissions: ["people.teams.manage"] }, tags: ["teams"] },
      { path: "/teams", method: "GET" as const, description: "List teams", auth: { required: true, permissions: ["people.employees.read"] }, tags: ["teams"] },
      { path: "/teams/{id}", method: "GET" as const, description: "Get a team", auth: { required: true, permissions: ["people.employees.read"] }, tags: ["teams"] },
      { path: "/teams/{id}", method: "PATCH" as const, description: "Update a team", auth: { required: true, permissions: ["people.teams.manage"] }, tags: ["teams"] },
      { path: "/role-profiles", method: "POST" as const, description: "Create a role profile", auth: { required: true, permissions: ["people.teams.manage"] }, tags: ["roleProfiles"] },
      { path: "/role-profiles", method: "GET" as const, description: "List role profiles", auth: { required: true, permissions: ["people.employees.read"] }, tags: ["roleProfiles"] },
      { path: "/attendance", method: "POST" as const, description: "Record attendance", auth: { required: true, permissions: ["people.attendance.record"] }, tags: ["attendance"] },
      { path: "/attendance", method: "GET" as const, description: "List attendance records", auth: { required: true, permissions: ["people.employees.read"] }, tags: ["attendance"] },
      { path: "/leave-requests", method: "POST" as const, description: "Submit a leave request", auth: { required: true, permissions: ["people.employees.create"] }, tags: ["leaveRequests"] },
      { path: "/leave-requests", method: "GET" as const, description: "List leave requests", auth: { required: true, permissions: ["people.employees.read"] }, tags: ["leaveRequests"] },
      { path: "/leave-requests/{id}/approve", method: "POST" as const, description: "Approve a leave request", auth: { required: true, permissions: ["people.leave.approve"] }, tags: ["leaveRequests"] },
      { path: "/shifts", method: "POST" as const, description: "Assign a shift", auth: { required: true, permissions: ["people.teams.manage"] }, tags: ["shifts"] },
      { path: "/shifts", method: "GET" as const, description: "List shifts", auth: { required: true, permissions: ["people.employees.read"] }, tags: ["shifts"] },
    ],
  },
  sdk: {
    namespace: "people",
    methods: [
      { name: "createEmployee", description: "Create an employee", endpoint: "POST /v1/people/employees", auth: true },
      { name: "listEmployees", description: "List employees", endpoint: "GET /v1/people/employees", auth: true },
      { name: "getEmployee", description: "Get an employee by ID", endpoint: "GET /v1/people/employees/{id}", auth: true },
      { name: "updateEmployee", description: "Update an employee", endpoint: "PATCH /v1/people/employees/{id}", auth: true },
      { name: "createTeam", description: "Create a team", endpoint: "POST /v1/people/teams", auth: true },
      { name: "listTeams", description: "List teams", endpoint: "GET /v1/people/teams", auth: true },
      { name: "recordAttendance", description: "Record attendance", endpoint: "POST /v1/people/attendance", auth: true },
      { name: "listAttendance", description: "List attendance records", endpoint: "GET /v1/people/attendance", auth: true },
      { name: "requestLeave", description: "Submit a leave request", endpoint: "POST /v1/people/leave-requests", auth: true },
      { name: "listLeaveRequests", description: "List leave requests", endpoint: "GET /v1/people/leave-requests", auth: true },
      { name: "approveLeave", description: "Approve a leave request", endpoint: "POST /v1/people/leave-requests/{id}/approve", auth: true },
      { name: "assignShift", description: "Assign a shift", endpoint: "POST /v1/people/shifts", auth: true },
      { name: "listShifts", description: "List shifts", endpoint: "GET /v1/people/shifts", auth: true },
    ],
  },
  cli: {
    namespace: "people",
    commands: [
      { name: "employees create", description: "Create an employee", command: "people.employee.create", flags: [{ name: "first-name", type: "string" as const, required: true, description: "First name" }, { name: "last-name", type: "string" as const, required: true, description: "Last name" }, { name: "email", type: "string" as const, required: true, description: "Work email" }, { name: "department", type: "string" as const, required: false, description: "Department" }] },
      { name: "employees invite", description: "Invite an employee", command: "people.employee.invite", flags: [{ name: "email", type: "string" as const, required: true, description: "Email to invite" }, { name: "first-name", type: "string" as const, required: true, description: "First name" }, { name: "last-name", type: "string" as const, required: true, description: "Last name" }] },
      { name: "teams create", description: "Create a team", command: "people.team.create", flags: [{ name: "name", type: "string" as const, required: true, description: "Team name" }, { name: "department", type: "string" as const, required: false, description: "Department" }] },
      { name: "attendance record", description: "Record attendance", command: "people.attendance.record", flags: [{ name: "employee-id", type: "string" as const, required: true, description: "Employee ID" }, { name: "date", type: "string" as const, required: true, description: "Attendance date" }, { name: "status", type: "string" as const, required: true, description: "Attendance status" }] },
      { name: "leave request", description: "Submit a leave request", command: "people.leave.request", flags: [{ name: "employee-id", type: "string" as const, required: true, description: "Employee ID" }, { name: "type", type: "string" as const, required: true, description: "Leave type" }, { name: "start-date", type: "string" as const, required: true, description: "Start date" }, { name: "end-date", type: "string" as const, required: true, description: "End date" }] },
      { name: "leave approve", description: "Approve a leave request", command: "people.leave.approve", flags: [{ name: "id", type: "string" as const, required: true, description: "Leave request ID" }, { name: "approver-id", type: "string" as const, required: true, description: "Approver employee ID" }] },
      { name: "shifts assign", description: "Assign a shift", command: "people.shift.assign", flags: [{ name: "employee-id", type: "string" as const, required: true, description: "Employee ID" }, { name: "date", type: "string" as const, required: true, description: "Shift date" }, { name: "start-time", type: "string" as const, required: true, description: "Start time" }, { name: "end-time", type: "string" as const, required: true, description: "End time" }] },
    ],
  },
  ui: {
    forms: [
      { name: "employee", model: "Employee", title: "Employee", fields: [{ field: "firstName", widget: "text" as const, label: "First Name", validation: { required: true } }, { field: "lastName", widget: "text" as const, label: "Last Name", validation: { required: true } }, { field: "email", widget: "text" as const, label: "Email", validation: { required: true } }, { field: "phone", widget: "text" as const, label: "Phone" }, { field: "department", widget: "text" as const, label: "Department" }, { field: "jobTitle", widget: "text" as const, label: "Job Title" }, { field: "status", widget: "select" as const, label: "Status", options: [{ label: "Active", value: "active" }, { label: "On Leave", value: "on_leave" }, { label: "Inactive", value: "inactive" }, { label: "Terminated", value: "terminated" }] }, { field: "hireDate", widget: "text" as const, label: "Hire Date" }] },
      { name: "team", model: "Team", title: "Team", fields: [{ field: "name", widget: "text" as const, label: "Team Name", validation: { required: true } }, { field: "description", widget: "textarea" as const, label: "Description" }, { field: "department", widget: "text" as const, label: "Department" }, { field: "status", widget: "select" as const, label: "Status", options: [{ label: "Active", value: "active" }, { label: "Inactive", value: "inactive" }] }] },
      { name: "leaveRequest", model: "LeaveRequest", title: "Leave Request", fields: [{ field: "type", widget: "select" as const, label: "Leave Type", validation: { required: true }, options: [{ label: "Vacation", value: "vacation" }, { label: "Sick", value: "sick" }, { label: "Personal", value: "personal" }, { label: "Maternity", value: "maternity" }, { label: "Paternity", value: "paternity" }, { label: "Bereavement", value: "bereavement" }, { label: "Unpaid", value: "unpaid" }] }, { field: "startDate", widget: "text" as const, label: "Start Date", validation: { required: true } }, { field: "endDate", widget: "text" as const, label: "End Date", validation: { required: true } }, { field: "reason", widget: "textarea" as const, label: "Reason" }] },
    ],
    views: [
      { name: "employees", type: "list" as const, model: "Employee", title: "Employees", columns: [{ field: "firstName", label: "First Name" }, { field: "lastName", label: "Last Name" }, { field: "email", label: "Email" }, { field: "department", label: "Department" }, { field: "status", label: "Status", format: "badge" as const }, { field: "hireDate", label: "Hired", format: "date" as const }], defaultSort: { field: "createdAt", direction: "desc" as const }, filters: [{ field: "status", operator: "eq", label: "Status" }, { field: "department", operator: "eq", label: "Department" }] },
      { name: "teams", type: "list" as const, model: "Team", title: "Teams", columns: [{ field: "name", label: "Team" }, { field: "department", label: "Department" }, { field: "status", label: "Status", format: "badge" as const }], defaultSort: { field: "createdAt", direction: "desc" as const }, filters: [{ field: "status", operator: "eq", label: "Status" }] },
      { name: "leaveRequests", type: "list" as const, model: "LeaveRequest", title: "Leave Requests", columns: [{ field: "employeeId", label: "Employee" }, { field: "type", label: "Type" }, { field: "startDate", label: "Start", format: "date" as const }, { field: "endDate", label: "End", format: "date" as const }, { field: "status", label: "Status", format: "badge" as const }], defaultSort: { field: "createdAt", direction: "desc" as const }, filters: [{ field: "status", operator: "eq", label: "Status" }, { field: "type", operator: "eq", label: "Type" }] },
    ],
  },
  mobile: [
    { name: "self-service-dashboard", title: "My Dashboard", type: "detail" as const, model: "Employee", layout: "scroll" as const, header: { title: "My Dashboard", showBack: false }, components: [{ type: "text" as const, dataBinding: "firstName" }, { type: "text" as const, dataBinding: "status" }, { type: "text" as const, dataBinding: "department" }, { type: "button" as const, props: { label: "Record Attendance" }, action: { type: "navigate" as const, target: "attendance-record" } }, { type: "button" as const, props: { label: "Request Leave" }, action: { type: "navigate" as const, target: "leave-request-form" } }, { type: "button" as const, props: { label: "View Shifts" }, action: { type: "navigate" as const, target: "my-shifts" } }], pullToRefresh: true },
    { name: "attendance-record", title: "Record Attendance", type: "form" as const, model: "Attendance", layout: "scroll" as const, header: { title: "Clock In/Out", showBack: true }, components: [{ type: "text" as const, dataBinding: "date" }, { type: "text" as const, dataBinding: "clockIn" }, { type: "text" as const, dataBinding: "clockOut" }, { type: "select" as const, dataBinding: "status", props: { options: ["present", "absent", "late", "half_day"] } }, { type: "button" as const, props: { label: "Submit" }, action: { type: "submit" as const } }], pullToRefresh: false },
    { name: "leave-request-form", title: "Leave Request", type: "form" as const, model: "LeaveRequest", layout: "scroll" as const, header: { title: "Request Leave", showBack: true }, components: [{ type: "select" as const, dataBinding: "type", props: { options: ["vacation", "sick", "personal", "maternity", "paternity", "bereavement", "unpaid"] } }, { type: "text" as const, dataBinding: "startDate" }, { type: "text" as const, dataBinding: "endDate" }, { type: "textarea" as const, dataBinding: "reason" }, { type: "button" as const, props: { label: "Submit Request" }, action: { type: "submit" as const } }], pullToRefresh: false },
    { name: "my-shifts", title: "My Shifts", type: "list" as const, model: "Shift", layout: "scroll" as const, header: { title: "My Shifts", showBack: true }, components: [{ type: "list" as const, dataBinding: "shifts", props: { itemTitle: "date", itemSubtitle: "type", badge: "type" } }], pullToRefresh: true },
  ],
  docs: {
    sections: [
      { title: "Getting Started", path: "/docs/people/getting-started" },
      { title: "Employees", path: "/docs/people/employees" },
      { title: "Teams", path: "/docs/people/teams" },
      { title: "Attendance", path: "/docs/people/attendance" },
      { title: "Leave Management", path: "/docs/people/leave" },
      { title: "Shifts", path: "/docs/people/shifts" },
      { title: "API Reference", path: "/docs/people/api" },
    ],
    examples: [
      { title: "Create Employee", code: "appneurox people employees create --first-name 'Jane' --last-name 'Doe' --email 'jane@example.com'" },
      { title: "Invite Employee", code: "appneurox people employees invite --email 'bob@example.com' --first-name 'Bob' --last-name 'Smith'" },
      { title: "Record Attendance", code: "appneurox people attendance record --employee-id UUID --date 2026-01-15 --status present" },
      { title: "Request Leave", code: "appneurox people leave request --employee-id UUID --type vacation --start-date 2026-02-01 --end-date 2026-02-05" },
      { title: "Approve Leave", code: "appneurox people leave approve --id UUID --approver-id UUID" },
    ],
  },
  metadata: {
    source: "legacy-os-repo",
    sourceId: "peopleos",
    mvp: true,
  },
} as unknown as OSManifest;
