import { PipelineStage, SalesState } from "./types";
import { emptyState } from "./core/datastore";
import { nowIso, plusDays } from "./core/id";

const DEFAULT_PIPELINE_STAGES: PipelineStage[] = [
  { name: "lead", displayName: "Lead", order: 1, probability: 10 },
  { name: "qualified", displayName: "Qualified", order: 2, probability: 25 },
  { name: "discovery", displayName: "Discovery", order: 3, probability: 40 },
  { name: "solution_fit", displayName: "Solution Fit", order: 4, probability: 60 },
  { name: "proposal", displayName: "Proposal", order: 5, probability: 75 },
  { name: "negotiation", displayName: "Negotiation", order: 6, probability: 90 },
  { name: "verbal_approval", displayName: "Verbal Approval", order: 7, probability: 95 },
  { name: "contract", displayName: "Contract", order: 8, probability: 98 },
  { name: "won", displayName: "Won", order: 9, probability: 100 },
  { name: "lost", displayName: "Lost", order: 10, probability: 0 }
];

export function createSeedState(tenantId = "demo-tenant"): SalesState {
  const state = emptyState();
  const createdAt = nowIso();

  state.pipelines.push({
    id: "pipeline_default",
    tenantId,
    createdAt,
    updatedAt: createdAt,
    key: "default_pipeline",
    name: "Default Sales Pipeline",
    description: "Standard sales pipeline for APPNEURAL service sales",
    stages: DEFAULT_PIPELINE_STAGES,
    isDefault: true,
    status: "active"
  });

  state.leads.push(
    {
      id: "lead_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "lead_rahul_sharma",
      name: "Rahul Sharma",
      email: "rahul.sharma@techcorp.in",
      phone: "+91 98765 43210",
      company: "TechCorp India",
      jobTitle: "CTO",
      source: "website",
      status: "qualified",
      score: { total: 78, fit: 80, intent: 75, engagement: 80, budget: 75, urgency: 80, reasons: ["Warm source", "High estimated value", "Decision maker"] },
      ownerId: "user_sales_rep_1",
      estimatedValue: 250000,
      notes: "Interested in AI automation services",
      tags: ["ai-automation", "enterprise"],
      metadata: {}
    },
    {
      id: "lead_demo_2",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "lead_priya_patel",
      name: "Priya Patel",
      email: "priya.patel@startup.io",
      phone: "+91 99876 54321",
      company: "StartupIO",
      jobTitle: "Founder",
      source: "referral",
      status: "contacted",
      score: { total: 65, fit: 70, intent: 60, engagement: 65, budget: 60, urgency: 70, reasons: ["Referral", "Has company"] },
      ownerId: "user_sales_rep_1",
      estimatedValue: 150000,
      notes: "Referred by existing client",
      tags: ["startup", "referral"],
      metadata: {}
    },
    {
      id: "lead_demo_3",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "lead_ankit_gupta",
      name: "Ankit Gupta",
      email: "ankit.gupta@enterprise.com",
      phone: "+91 91234 56789",
      company: "Enterprise Solutions Ltd",
      jobTitle: "VP of Operations",
      source: "linkedin",
      status: "discovery_scheduled",
      score: { total: 82, fit: 85, intent: 80, engagement: 85, budget: 85, urgency: 75, reasons: ["LinkedIn", "Enterprise", "High value", "Decision maker"] },
      ownerId: "user_sales_manager",
      estimatedValue: 500000,
      notes: "Large enterprise deal, needs discovery call",
      tags: ["enterprise", "ai-automation", "urgent"],
      metadata: {}
    },
    {
      id: "lead_demo_4",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "lead_sneha_reddy",
      name: "Sneha Reddy",
      email: "sneha.reddy@retailmart.co",
      phone: "+91 98765 12345",
      company: "RetailMart",
      jobTitle: "Head of Digital",
      source: "workshop",
      status: "proposal_sent",
      score: { total: 88, fit: 90, intent: 85, engagement: 90, budget: 85, urgency: 90, reasons: ["Workshop", "High engagement", "Clear need", "Ready to buy"] },
      ownerId: "user_sales_rep_2",
      estimatedValue: 350000,
      notes: "Proposal sent for websiteOS + AI automation",
      tags: ["website", "ai-automation", "ecommerce"],
      metadata: {}
    },
    {
      id: "lead_demo_5",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "lead_vikram_singh",
      name: "Vikram Singh",
      email: "vikram.singh@logistics.net",
      phone: "+91 99887 76655",
      company: "LogisticsNet",
      jobTitle: "CEO",
      source: "partner",
      status: "negotiation",
      score: { total: 92, fit: 95, intent: 90, engagement: 95, budget: 95, urgency: 85, reasons: ["Partner", "CEO", "Negotiation stage", "High value"] },
      ownerId: "user_sales_manager",
      estimatedValue: 750000,
      notes: "Negotiating multi-year contract",
      tags: ["enterprise", "long-term", "partner"],
      metadata: {}
    }
  );

  state.accounts.push(
    {
      id: "account_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "account_techcorp",
      name: "TechCorp India",
      industry: "Technology",
      website: "https://techcorp.in",
      size: "medium",
      location: "Bangalore, Karnataka",
      revenue: 50000000,
      ownerId: "user_sales_rep_1",
      status: "active",
      notes: "Growing tech company, potential for upsells",
      tags: ["technology", "bangalore"],
      metadata: {}
    },
    {
      id: "account_demo_2",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "account_startupio",
      name: "StartupIO",
      industry: "Technology",
      website: "https://startup.io",
      size: "small",
      location: "Mumbai, Maharashtra",
      revenue: 10000000,
      ownerId: "user_sales_rep_1",
      status: "active",
      notes: "Early stage startup, budget conscious",
      tags: ["startup", "mumbai"],
      metadata: {}
    },
    {
      id: "account_demo_3",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "account_enterprise",
      name: "Enterprise Solutions Ltd",
      industry: "Enterprise Software",
      website: "https://enterprise.com",
      size: "enterprise",
      location: "Delhi, NCR",
      revenue: 500000000,
      ownerId: "user_sales_manager",
      status: "active",
      notes: "Large enterprise, long sales cycle",
      tags: ["enterprise", "delhi", "long-cycle"],
      metadata: {}
    }
  );

  state.contacts.push(
    {
      id: "contact_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "contact_rahul_sharma",
      firstName: "Rahul",
      lastName: "Sharma",
      email: "rahul.sharma@techcorp.in",
      phone: "+91 98765 43210",
      jobTitle: "CTO",
      department: "Technology",
      role: "decision_maker",
      accountId: "account_demo_1",
      leadId: "lead_demo_1",
      isPrimary: true,
      notes: "Primary decision maker for tech purchases",
      metadata: {}
    },
    {
      id: "contact_demo_2",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "contact_priya_patel",
      firstName: "Priya",
      lastName: "Patel",
      email: "priya.patel@startup.io",
      phone: "+91 99876 54321",
      jobTitle: "Founder",
      department: "Leadership",
      role: "decision_maker",
      accountId: "account_demo_2",
      leadId: "lead_demo_2",
      isPrimary: true,
      notes: "Solo decision maker as founder",
      metadata: {}
    },
    {
      id: "contact_demo_3",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "contact_ankit_gupta",
      firstName: "Ankit",
      lastName: "Gupta",
      email: "ankit.gupta@enterprise.com",
      phone: "+91 91234 56789",
      jobTitle: "VP of Operations",
      department: "Operations",
      role: "influencer",
      accountId: "account_demo_3",
      leadId: "lead_demo_3",
      isPrimary: true,
      notes: "Influencer, will present to board",
      metadata: {}
    }
  );

  state.deals.push(
    {
      id: "deal_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "deal_techcorp_ai",
      title: "TechCorp AI Automation Project",
      value: 250000,
      stage: "proposal",
      probability: 75,
      expectedCloseDate: plusDays(30),
      ownerId: "user_sales_rep_1",
      accountId: "account_demo_1",
      leadId: "lead_demo_1",
      contactIds: ["contact_demo_1"],
      notes: "Proposal under review",
      tags: ["ai-automation", "medium-term"],
      metadata: {}
    },
    {
      id: "deal_demo_2",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "deal_retailmart_website",
      title: "RetailMart E-commerce Platform",
      value: 350000,
      stage: "negotiation",
      probability: 90,
      expectedCloseDate: plusDays(15),
      ownerId: "user_sales_rep_2",
      leadId: "lead_demo_4",
      contactIds: [],
      notes: "Negotiating final terms",
      tags: ["website", "ecommerce"],
      metadata: {}
    },
    {
      id: "deal_demo_3",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "deal_logistics_enterprise",
      title: "LogisticsNet Enterprise Suite",
      value: 750000,
      stage: "negotiation",
      probability: 90,
      expectedCloseDate: plusDays(45),
      ownerId: "user_sales_manager",
      leadId: "lead_demo_5",
      contactIds: [],
      notes: "Multi-year contract, high priority",
      tags: ["enterprise", "long-term", "strategic"],
      metadata: {}
    },
    {
      id: "deal_demo_4",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "deal_enterprise_platform",
      title: "Enterprise Solutions Platform Upgrade",
      value: 500000,
      stage: "discovery",
      probability: 40,
      expectedCloseDate: plusDays(90),
      ownerId: "user_sales_manager",
      accountId: "account_demo_3",
      leadId: "lead_demo_3",
      contactIds: ["contact_demo_3"],
      notes: "Discovery phase, needs more meetings",
      tags: ["enterprise", "long-cycle"],
      metadata: {}
    },
    {
      id: "deal_demo_5",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "deal_startup_basic",
      title: "StartupIO Basic Package",
      value: 75000,
      stage: "won",
      probability: 100,
      expectedCloseDate: createdAt,
      actualCloseDate: createdAt,
      ownerId: "user_sales_rep_1",
      accountId: "account_demo_2",
      contactIds: ["contact_demo_2"],
      notes: "Closed! Welcome to APPNEURAL",
      tags: ["startup", "closed-won"],
      metadata: {}
    }
  );

  state.activities.push(
    {
      id: "activity_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "activity_call_rahul",
      type: "call",
      subject: "Discovery call with Rahul Sharma",
      description: "Discussed AI automation requirements for TechCorp",
      dealId: "deal_demo_1",
      leadId: "lead_demo_1",
      contactId: "contact_demo_1",
      accountId: "account_demo_1",
      ownerId: "user_sales_rep_1",
      duration: 45,
      outcome: "Interested, wants proposal",
      metadata: {}
    },
    {
      id: "activity_demo_2",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "activity_email_proposal",
      type: "email",
      subject: "Proposal sent to RetailMart",
      description: "Sent comprehensive proposal for e-commerce platform",
      dealId: "deal_demo_2",
      leadId: "lead_demo_4",
      ownerId: "user_sales_rep_2",
      outcome: "Client reviewing",
      metadata: {}
    },
    {
      id: "activity_demo_3",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "activity_meeting_negotiation",
      type: "meeting",
      subject: "Contract negotiation with LogisticsNet",
      description: "Negotiating terms and pricing for enterprise contract",
      dealId: "deal_demo_3",
      leadId: "lead_demo_5",
      ownerId: "user_sales_manager",
      duration: 90,
      outcome: "Progress made, next meeting scheduled",
      metadata: {}
    },
    {
      id: "activity_demo_4",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "activity_demo_enterprise",
      type: "demo",
      subject: "Platform demo for Enterprise Solutions",
      description: "Demonstrated full platform capabilities",
      dealId: "deal_demo_4",
      leadId: "lead_demo_3",
      contactId: "contact_demo_3",
      accountId: "account_demo_3",
      ownerId: "user_sales_manager",
      duration: 60,
      outcome: "Good response, wants technical deep dive",
      metadata: {}
    },
    {
      id: "activity_demo_5",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "activity_whatsapp_followup",
      type: "whatsapp",
      subject: "Quick follow-up with Priya Patel",
      description: "Checked in on startup package decision",
      dealId: undefined,
      leadId: "lead_demo_2",
      contactId: "contact_demo_2",
      ownerId: "user_sales_rep_1",
      outcome: "Will decide next week",
      metadata: {}
    }
  );

  state.followUps.push(
    {
      id: "followup_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "followup_proposal_review",
      subject: "Follow up on TechCorp proposal",
      description: "Check if Rahul has reviewed the proposal",
      type: "follow_up",
      status: "pending",
      priority: "high",
      dueDate: plusDays(1),
      dealId: "deal_demo_1",
      leadId: "lead_demo_1",
      ownerId: "user_sales_rep_1",
      notes: "Important - deal at risk if not followed up",
      metadata: {}
    },
    {
      id: "followup_demo_2",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "followup_negotiation_call",
      subject: "Schedule negotiation call with LogisticsNet",
      description: "Coordinate with Vikram for final contract discussion",
      type: "meeting",
      status: "pending",
      priority: "urgent",
      dueDate: plusDays(2),
      dealId: "deal_demo_3",
      leadId: "lead_demo_5",
      ownerId: "user_sales_manager",
      notes: "Critical deal - need to close this month",
      metadata: {}
    },
    {
      id: "followup_demo_3",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "followup_enterprise_discovery",
      subject: "Send case studies to Enterprise Solutions",
      description: "Share relevant case studies and technical documentation",
      type: "email",
      status: "pending",
      priority: "medium",
      dueDate: plusDays(3),
      dealId: "deal_demo_4",
      leadId: "lead_demo_3",
      ownerId: "user_sales_manager",
      metadata: {}
    },
    {
      id: "followup_demo_4",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "followup_priya_decision",
      subject: "Check back with Priya on startup package",
      type: "follow_up",
      status: "pending",
      priority: "medium",
      dueDate: plusDays(5),
      dealId: undefined,
      leadId: "lead_demo_2",
      contactId: "contact_demo_2",
      ownerId: "user_sales_rep_1",
      notes: "She said she'd decide next week",
      metadata: {}
    }
  );

  state.proposals.push(
    {
      id: "proposal_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "proposal_techcorp",
      title: "TechCorp AI Automation Solution",
      status: "sent",
      dealId: "deal_demo_1",
      leadId: "lead_demo_1",
      accountId: "account_demo_1",
      contactId: "contact_demo_1",
      ownerId: "user_sales_rep_1",
      validUntil: plusDays(30),
      sections: [
        { title: "Executive Summary", content: "AI-powered automation solution for TechCorp...", order: 1 },
        { title: "Proposed Solution", content: "Custom AI automation platform with integrations...", order: 2 },
        { title: "Timeline", content: "Implementation in 3 phases over 6 months...", order: 3 },
        { title: "Investment", content: "Total investment: ₹2,50,000", order: 4 }
      ],
      lineItems: [
        { description: "AI Automation Platform License", quantity: 1, unitPrice: 150000, total: 150000, metadata: {} },
        { description: "Implementation & Integration", quantity: 1, unitPrice: 75000, total: 75000, metadata: {} },
        { description: "Training & Documentation", quantity: 1, unitPrice: 25000, total: 25000, metadata: {} }
      ],
      subtotal: 250000,
      tax: 45000,
      discount: 0,
      total: 295000,
      notes: "Waiting for client review",
      sentAt: createdAt,
      metadata: {}
    },
    {
      id: "proposal_demo_2",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "proposal_retailmart",
      title: "RetailMart E-commerce Platform",
      status: "negotiating",
      dealId: "deal_demo_2",
      leadId: "lead_demo_4",
      ownerId: "user_sales_rep_2",
      validUntil: plusDays(15),
      sections: [
        { title: "Project Overview", content: "Full-featured e-commerce platform with AI recommendations...", order: 1 },
        { title: "Features", content: "Product catalog, cart, checkout, payments, AI recommendations...", order: 2 },
        { title: "Delivery Timeline", content: "4-month implementation plan...", order: 3 }
      ],
      lineItems: [
        { description: "WebsiteOS Platform License", quantity: 1, unitPrice: 200000, total: 200000, metadata: {} },
        { description: "AI Recommendation Engine", quantity: 1, unitPrice: 75000, total: 75000, metadata: {} },
        { description: "Payment Gateway Integration", quantity: 1, unitPrice: 25000, total: 25000, metadata: {} },
        { description: "Launch Support", quantity: 1, unitPrice: 50000, total: 50000, metadata: {} }
      ],
      subtotal: 350000,
      tax: 63000,
      discount: 15000,
      total: 398000,
      notes: "Negotiating 15% discount",
      sentAt: createdAt,
      viewedAt: createdAt,
      metadata: {}
    }
  );

  state.targets.push(
    {
      id: "target_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "target_q2_revenue",
      title: "Q2 Revenue Target",
      type: "revenue",
      period: "quarterly",
      targetValue: 2000000,
      currentValue: 750000,
      startDate: new Date().toISOString().split("T")[0],
      endDate: plusDays(30).split("T")[0],
      ownerId: "user_sales_manager",
      teamId: "team_sales",
      status: "active",
      metadata: {}
    },
    {
      id: "target_demo_2",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "target_monthly_leads",
      title: "Monthly Lead Generation",
      type: "leads",
      period: "monthly",
      targetValue: 50,
      currentValue: 23,
      startDate: new Date().toISOString().split("T")[0],
      endDate: plusDays(15).split("T")[0],
      ownerId: "user_sales_rep_1",
      status: "active",
      metadata: {}
    },
    {
      id: "target_demo_3",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "target_monthly_qualified",
      title: "Monthly Qualified Leads",
      type: "qualified_leads",
      period: "monthly",
      targetValue: 15,
      currentValue: 5,
      startDate: new Date().toISOString().split("T")[0],
      endDate: plusDays(15).split("T")[0],
      ownerId: "user_sales_rep_1",
      status: "active",
      metadata: {}
    }
  );

  state.forecasts.push(
    {
      id: "forecast_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "forecast_may_2025",
      title: "May 2025 Revenue Forecast",
      period: "monthly",
      startDate: "2025-05-01",
      endDate: "2025-05-31",
      status: "submitted",
      ownerId: "user_sales_manager",
      totalValue: 1850000,
      totalWeightedValue: 1412500,
      items: [
        { dealId: "deal_demo_1", dealTitle: "TechCorp AI Automation Project", value: 250000, probability: 75, weightedValue: 187500, expectedCloseDate: plusDays(30), stage: "proposal" },
        { dealId: "deal_demo_2", dealTitle: "RetailMart E-commerce Platform", value: 350000, probability: 90, weightedValue: 315000, expectedCloseDate: plusDays(15), stage: "negotiation" },
        { dealId: "deal_demo_3", dealTitle: "LogisticsNet Enterprise Suite", value: 750000, probability: 90, weightedValue: 675000, expectedCloseDate: plusDays(45), stage: "negotiation" },
        { dealId: "deal_demo_4", dealTitle: "Enterprise Solutions Platform Upgrade", value: 500000, probability: 40, weightedValue: 200000, expectedCloseDate: plusDays(90), stage: "discovery" }
      ],
      assumptions: "Based on current pipeline and probability adjustments",
      notes: "Strong month if LogisticsNet closes",
      submittedAt: createdAt,
      metadata: {}
    }
  );

  state.events.push({
    id: "event_demo_seed",
    tenantId,
    createdAt,
    updatedAt: createdAt,
    type: "salesos.seeded",
    source: "SalesOS",
    data: { message: "SalesOS demo data seeded", leads: 5, deals: 5, activities: 5 }
  });

  return state;
}
