import { promises as fs } from "fs";
import path from "path";

function uniq(items) {
  return Array.from(new Set(items.filter((item) => typeof item === "string" && item.trim().length > 0)));
}

function toServiceKey(value) {
  if (!value) return "";
  const raw = String(value).trim();
  if (raw.startsWith("@appneurox/")) return raw.slice("@appneurox/".length).toLowerCase();
  return raw.toLowerCase();
}

async function fileExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function readText(filePath) {
  return await fs.readFile(filePath, "utf8");
}

function inferPortFromMain(source) {
  const patterns = [
    /const\s+port\s*=\s*Number\(\s*process\.env\.PORT\s*\?\?\s*(\d+)\s*\)/,
    /const\s+port\s*=\s*Number\(\s*process\.env\.PORT\s*\|\|\s*(\d+)\s*\)/,
    /const\s+port\s*=\s*Number\(\s*\(process\.env\.PORT\s*\?\?\s*(\d+)\)\s*\)/,
    /const\s+port\s*=\s*(\d+)\s*;/
  ];
  for (const pattern of patterns) {
    const match = source.match(pattern);
    if (match && match[1]) return Number(match[1]);
  }
  return undefined;
}

async function updateManifest(osDir, manifestPath) {
  const raw = await readText(manifestPath);
  const manifest = JSON.parse(raw);

  const mainPath = path.join(osDir, "src", "main.ts");
  const port = (await fileExists(mainPath)) ? inferPortFromMain(await readText(mainPath)) : undefined;
  if (!manifest.runtime) manifest.runtime = {};
  if (port && typeof manifest.runtime.port !== "number") manifest.runtime.port = port;
  if (typeof manifest.runtime.port === "number" && typeof manifest.runtime.localBaseUrl !== "string") {
    manifest.runtime.localBaseUrl = `http://localhost:${manifest.runtime.port}`;
  }

  const required = uniq((manifest.dependencies?.required ?? []).map(toServiceKey)).map((key) => `@appneurox/${key}`);
  const optional = uniq((manifest.dependencies?.optional ?? []).map(toServiceKey))
    .filter((key) => !required.includes(`@appneurox/${key}`))
    .map((key) => `@appneurox/${key}`);

  if (manifest.dependencies) {
    manifest.dependencies.required = required;
    manifest.dependencies.optional = optional;
  }

  const related = uniq([...(manifest.relatedSystems ?? []).map(toServiceKey), ...required.map(toServiceKey)]);
  manifest.relatedSystems = related;

  await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2) + "\n", "utf8");
  return { manifest, port: manifest.runtime?.port };
}

async function updateReadme(osDir, manifest) {
  const readmePath = path.join(osDir, "README.md");
  if (!(await fileExists(readmePath))) return;
  let text = await readText(readmePath);

  text = text.replace(/Planning reference:\s*`[^`]+`/g, "Catalog: `../README.md`");
  text = text.replace(/\/APPNEURAL Plannings\/OSs\/[^\s)]+/g, "docs/planning.md");

  const deps = (manifest.dependencies?.required ?? []).map(toServiceKey).filter(Boolean);
  const relatedBlock = deps.length
    ? `\n## Related OSs\n\n${deps.map((key) => `- ${key}`).join("\n")}\n`
    : "";

  if (deps.length) {
    if (text.includes("## Related OSs")) {
      text = text.replace(/## Related OSs[\s\S]*$/m, relatedBlock.trimStart());
    } else {
      text = text.trimEnd() + relatedBlock;
    }
  }

  await fs.writeFile(readmePath, text.trimEnd() + "\n", "utf8");
}

async function buildCatalog(rootDir, entries) {
  const sorted = [...entries].sort((a, b) => String(a.id).localeCompare(String(b.id)));
  const lines = [];
  lines.push("# APPNEURAL OS Catalog");
  lines.push("");
  lines.push("This index is generated by `scripts/link-os.mjs`.");
  lines.push("");
  lines.push("## OS Packages");
  lines.push("");
  for (const item of sorted) {
    const manifestRel = `./${item.dir}/manifest.json`;
    const readmeRel = `./${item.dir}/README.md`;
    const portInfo = item.port ? ` (port ${item.port})` : "";
    const docsInfo = item.api?.docsPath ? ` docs: ${item.api.docsPath}` : "";
    lines.push(`- ${item.id}${portInfo} — [manifest](${manifestRel}) [readme](${readmeRel})${docsInfo}`);
  }
  lines.push("");
  await fs.writeFile(path.join(rootDir, "README.md"), lines.join("\n"), "utf8");
  await fs.writeFile(path.join(rootDir, "catalog.json"), JSON.stringify(sorted, null, 2) + "\n", "utf8");
}

async function main() {
  const rootDir = process.argv[2] ? path.resolve(process.argv[2]) : process.cwd();
  const dirEntries = await fs.readdir(rootDir, { withFileTypes: true });

  const catalog = [];
  for (const entry of dirEntries) {
    if (!entry.isDirectory()) continue;
    if (entry.name === "scripts") continue;
    const osDir = path.join(rootDir, entry.name);
    const manifestPath = path.join(osDir, "manifest.json");
    if (!(await fileExists(manifestPath))) continue;
    const { manifest, port } = await updateManifest(osDir, manifestPath);
    await updateReadme(osDir, manifest);
    catalog.push({
      dir: entry.name,
      id: manifest.id,
      name: manifest.name,
      package: manifest.package,
      version: manifest.version,
      description: manifest.description,
      api: manifest.api,
      runtime: manifest.runtime,
      port
    });
  }

  await buildCatalog(rootDir, catalog);
  process.stdout.write(`Linked ${catalog.length} OS packages.\n`);
}

main().catch((error) => {
  process.stderr.write(String(error?.stack ?? error) + "\n");
  process.exit(1);
});
