import { WebsiteState } from "./core/domain";
import { newId, nowIso } from "./core/utils";

export function createSeedState(tenantId: string): WebsiteState {
  const websiteId = newId("website");
  const userId = "demo-user";

  const websites = [
    {
      id: websiteId,
      tenantId,
      createdAt: nowIso(),
      updatedAt: nowIso(),
      name: "APPNEURAL",
      description: "AI-powered business automation and digital transformation",
      domain: "appneural.com",
      status: "active" as const,
      publishedAt: nowIso(),
      analyticsEnabled: true,
      seoScore: 78,
      settings: {
        title: "APPNEURAL - AI Automation & Digital Transformation",
        description: "We build intelligent systems that help businesses reduce chaos, automate workflows, and scale with clarity.",
        keywords: ["AI automation", "digital transformation", "business automation", "SaaS"],
        language: "en",
        timezone: "UTC",
        googleAnalyticsId: "G-XXXXXXXXXX",
        socialLinks: {
          linkedin: "https://linkedin.com/company/appneural",
          twitter: "https://twitter.com/appneural",
        },
      },
      metadata: {},
      createdBy: userId,
    },
  ];

  const pages = [
    {
      id: newId("page"),
      tenantId,
      createdAt: nowIso(),
      updatedAt: nowIso(),
      websiteId,
      title: "Home",
      slug: "/",
      status: "published" as const,
      pageType: "home" as const,
      content: "Welcome to APPNEURAL",
      sections: [
        {
          id: newId("section"),
          type: "hero" as const,
          order: 1,
          content: {
            headline: "Build Intelligent Systems",
            subheadline: "We help businesses reduce chaos, automate workflows, and scale with clarity.",
            cta: "Get Started",
          },
        },
        {
          id: newId("section"),
          type: "features" as const,
          order: 2,
          content: {
            title: "Our Services",
            features: [
              "Product Development",
              "AI Automation",
              "Team Outsourcing",
              "GenAI Training",
            ],
          },
        },
        {
          id: newId("section"),
          type: "cta" as const,
          order: 3,
          content: {
            text: "Ready to transform your business?",
            cta: "Schedule Consultation",
          },
        },
      ],
      seo: {
        metaTitle: "APPNEURAL - AI Automation & Digital Transformation",
        metaDescription: "We build intelligent systems that help businesses reduce chaos, automate workflows, and scale with clarity.",
        keywords: ["AI automation", "digital transformation", "business automation"],
        ogTitle: "APPNEURAL - Build Intelligent Systems",
        ogDescription: "AI-powered business automation and digital transformation",
        noIndex: false,
        noFollow: false,
        schemaMarkup: [
          {
            type: "organization" as const,
            data: {
              name: "APPNEURAL",
              url: "https://appneural.com",
              logo: "https://appneural.com/logo.png",
            },
          },
        ],
        breadcrumbs: [],
        internalLinks: [],
        externalLinks: [],
      },
      publishedAt: nowIso(),
      authorId: userId,
      lastPublishedAt: nowIso(),
      version: 1,
      order: 0,
      metadata: {},
    },
    {
      id: newId("page"),
      tenantId,
      createdAt: nowIso(),
      updatedAt: nowIso(),
      websiteId,
      title: "Services",
      slug: "/services",
      status: "published" as const,
      pageType: "service" as const,
      content: "Our Services",
      sections: [
        {
          id: newId("section"),
          type: "hero" as const,
          order: 1,
          content: {
            headline: "Our Services",
            subheadline: "Comprehensive solutions for your digital transformation journey",
          },
        },
        {
          id: newId("section"),
          type: "features" as const,
          order: 2,
          content: {
            title: "What We Offer",
            features: [
              { name: "Product Development", description: "End-to-end product development from concept to launch" },
              { name: "AI Automation", description: "Intelligent automation solutions powered by AI" },
              { name: "Team Outsourcing", description: "Access to skilled teams for your projects" },
              { name: "GenAI Training", description: "Hands-on training on generative AI technologies" },
            ],
          },
        },
      ],
      seo: {
        metaTitle: "Services - APPNEURAL",
        metaDescription: "Comprehensive digital transformation services including product development, AI automation, and team outsourcing.",
        keywords: ["services", "product development", "AI automation", "outsourcing"],
        noIndex: false,
        noFollow: false,
        schemaMarkup: [],
        breadcrumbs: [{ label: "Home", url: "/" }, { label: "Services", url: "/services" }],
        internalLinks: [],
        externalLinks: [],
      },
      publishedAt: nowIso(),
      authorId: userId,
      lastPublishedAt: nowIso(),
      version: 1,
      order: 1,
      metadata: {},
    },
    {
      id: newId("page"),
      tenantId,
      createdAt: nowIso(),
      updatedAt: nowIso(),
      websiteId,
      title: "Contact",
      slug: "/contact",
      status: "published" as const,
      pageType: "contact" as const,
      content: "Get in Touch",
      sections: [
        {
          id: newId("section"),
          type: "contact" as const,
          order: 1,
          content: {
            headline: "Get in Touch",
            subheadline: "Ready to start your transformation journey?",
            email: "hello@appneural.com",
          },
        },
      ],
      seo: {
        metaTitle: "Contact - APPNEURAL",
        metaDescription: "Contact APPNEURAL for AI automation, digital transformation, and software development services.",
        keywords: ["contact", "consultation", "AI automation"],
        noIndex: false,
        noFollow: false,
        schemaMarkup: [],
        breadcrumbs: [{ label: "Home", url: "/" }, { label: "Contact", url: "/contact" }],
        internalLinks: [],
        externalLinks: [],
      },
      publishedAt: nowIso(),
      authorId: userId,
      lastPublishedAt: nowIso(),
      version: 1,
      order: 2,
      metadata: {},
    },
    {
      id: newId("page"),
      tenantId,
      createdAt: nowIso(),
      updatedAt: nowIso(),
      websiteId,
      title: "AI Automation Services",
      slug: "/services/ai-automation",
      status: "draft" as const,
      pageType: "service" as const,
      content: "AI Automation Services",
      sections: [],
      seo: {
        metaTitle: "AI Automation Services - APPNEURAL",
        metaDescription: "Transform your business with AI-powered automation solutions.",
        keywords: ["AI", "automation", "machine learning"],
        noIndex: false,
        noFollow: false,
        schemaMarkup: [],
        breadcrumbs: [{ label: "Home", url: "/" }, { label: "Services", url: "/services" }, { label: "AI Automation", url: "/services/ai-automation" }],
        internalLinks: [],
        externalLinks: [],
      },
      publishedAt: undefined,
      authorId: userId,
      lastPublishedAt: undefined,
      version: 1,
      parentId: undefined,
      order: 3,
      metadata: {},
    },
  ];

  const forms = [
    {
      id: newId("form"),
      tenantId,
      createdAt: nowIso(),
      updatedAt: nowIso(),
      websiteId,
      name: "Contact Form",
      type: "contact" as const,
      fields: [
        { id: newId("field"), name: "name", label: "Name", type: "text" as const, required: true, order: 1 },
        { id: newId("field"), name: "email", label: "Email", type: "email" as const, required: true, order: 2 },
        { id: newId("field"), name: "phone", label: "Phone", type: "phone" as const, required: false, order: 3 },
        { id: newId("field"), name: "message", label: "Message", type: "textarea" as const, required: true, order: 4 },
      ],
      settings: {
        submitButtonText: "Send Message",
        successMessage: "Thank you! We'll be in touch soon.",
        spamProtection: true,
      },
      status: "active" as const,
      submissionsCount: 12,
      lastSubmissionAt: nowIso(),
      createdBy: userId,
    },
    {
      id: newId("form"),
      tenantId,
      createdAt: nowIso(),
      updatedAt: nowIso(),
      websiteId,
      name: "Lead Generation Form",
      type: "lead" as const,
      fields: [
        { id: newId("field"), name: "name", label: "Name", type: "text" as const, required: true, order: 1 },
        { id: newId("field"), name: "email", label: "Email", type: "email" as const, required: true, order: 2 },
        { id: newId("field"), name: "company", label: "Company", type: "text" as const, required: true, order: 3 },
        { id: newId("field"), name: "service", label: "Service Interest", type: "select" as const, required: true, order: 4, options: [
          { value: "product-development", label: "Product Development" },
          { value: "ai-automation", label: "AI Automation" },
          { value: "team-outsourcing", label: "Team Outsourcing" },
          { value: "training", label: "Training" },
        ]},
      ],
      settings: {
        submitButtonText: "Request Consultation",
        successMessage: "Thanks! Our team will reach out within 24 hours.",
        spamProtection: true,
        autoReply: {
          enabled: true,
          subject: "Thank you for your inquiry",
          body: "We received your message and will respond shortly.",
        },
      },
      status: "active" as const,
      submissionsCount: 28,
      lastSubmissionAt: nowIso(),
      createdBy: userId,
    },
  ];

  const ctas = [
    {
      id: newId("cta"),
      tenantId,
      createdAt: nowIso(),
      updatedAt: nowIso(),
      websiteId,
      text: "Get Started",
      type: "primary" as const,
      url: "/contact",
      position: "hero" as const,
      status: "active" as const,
      clicks: 342,
      conversions: 89,
      createdBy: userId,
    },
    {
      id: newId("cta"),
      tenantId,
      createdAt: nowIso(),
      updatedAt: nowIso(),
      websiteId,
      text: "Learn More",
      type: "secondary" as const,
      url: "/services",
      position: "content" as const,
      status: "active" as const,
      clicks: 215,
      conversions: 54,
      createdBy: userId,
    },
  ];

  const landingPages = [
    {
      id: newId("landing"),
      tenantId,
      createdAt: nowIso(),
      updatedAt: nowIso(),
      websiteId,
      name: "Free AI Automation Audit",
      slug: "/free-ai-audit",
      offer: "Free AI Automation Audit",
      headline: "Discover How AI Can Transform Your Business",
      subheadline: "Get a personalized audit of your current processes and see where AI automation can save you time and money.",
      status: "published" as const,
      formId: forms[1].id,
      content: "Complete our form to receive your free AI automation audit.",
      seo: {
        metaTitle: "Free AI Automation Audit - APPNEURAL",
        metaDescription: "Get a free AI automation audit and discover how AI can transform your business processes.",
        keywords: ["AI audit", "automation audit", "free consultation"],
        noIndex: false,
        noFollow: false,
        schemaMarkup: [],
        breadcrumbs: [],
        internalLinks: [],
        externalLinks: [],
      },
      publishedAt: nowIso(),
      conversions: 47,
      views: 1243,
      conversionRate: 3.78,
      metadata: {},
    },
  ];

  const analytics: any[] = [];
  for (let i = 0; i < 30; i++) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    analytics.push({
      id: newId("analytics"),
      tenantId,
      createdAt: nowIso(),
      updatedAt: nowIso(),
      websiteId,
      date: date.toISOString().split("T")[0],
      visitors: Math.floor(Math.random() * 200) + 50,
      pageViews: Math.floor(Math.random() * 500) + 100,
      uniquePageViews: Math.floor(Math.random() * 400) + 80,
      bounceRate: Math.random() * 30 + 30,
      avgSessionDuration: Math.floor(Math.random() * 300) + 60,
      topPages: [],
      trafficSources: [
        { source: "google", medium: "organic", visitors: Math.floor(Math.random() * 100) + 20, percentage: 45 },
        { source: "linkedin", medium: "social", visitors: Math.floor(Math.random() * 50) + 10, percentage: 25 },
        { source: "direct", visitors: Math.floor(Math.random() * 40) + 10, percentage: 20 },
        { source: "twitter", medium: "social", visitors: Math.floor(Math.random() * 30) + 5, percentage: 10 },
      ],
      conversions: Math.floor(Math.random() * 10) + 2,
      formSubmissions: Math.floor(Math.random() * 5) + 1,
      ctaClicks: Math.floor(Math.random() * 20) + 5,
    });
  }

  return {
    websites,
    pages,
    landingPages,
    components: [],
    forms,
    formSubmissions: [],
    ctas,
    domains: [],
    deployments: [],
    analytics,
    events: [],
    sitemaps: [],
    audits: [],
    croChecks: [],
  };
}
