import { createServer } from "http";
import { DataStore } from "./core/datastore";
import { EventBus } from "./core/event-bus";
import { Router } from "./core/http";
import { registerRoutes } from "./modules/routes";
import { ProductService } from "./services/product.service";
import { createSeedState } from "./seed-state";
const port = Number(process.env.PORT ?? 9000);
const dbFile = process.env.PRODUCTOS_DB_FILE ?? "data/productos.db.json";
const tenantId = process.env.DEFAULT_TENANT_ID ?? "demo-tenant";
const store = new DataStore(dbFile);
if (store.getState().products.length === 0) store.reset(createSeedState(tenantId));
const router = registerRoutes(new Router(), new ProductService(store, new EventBus(store)));
const server = createServer((req: any, res: any) => { router.handle(req, res); });
server.listen(port, () => { console.log(`ProductOS running on http://localhost:${port}`); console.log(`Health: http://localhost:${port}/health`); console.log(`Docs:   http://localhost:${port}/docs`); });
