import { AgenticState } from "./core/domain";
import { emptyState } from "./core/datastore";
import { newId, nowIso } from "./core/id";

export function createSeedState(tenantId = "demo-tenant"): AgenticState {
  const state = emptyState();
  const createdAt = nowIso();

  state.guardrails.push(
    {
      id: "guard_safe_content",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "safe_content",
      name: "Safe Content Guardrail",
      description: "Blocks harmful, illegal, or inappropriate content",
      status: "active",
      type: "both",
      bannedTerms: ["malware", "hack", "exploit", "illegal"],
      requiredTerms: [],
      requireCitations: false,
      allowCustomData: true,
      sensitiveDataPatterns: ["ssn", "credit_card", "password"],
      actionOnViolation: "block",
      severityLevel: "high",
      metadata: { category: "safety", version: "1.0" }
    },
    {
      id: "guard_data_privacy",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "data_privacy",
      name: "Data Privacy Guardrail",
      description: "Ensures PII and sensitive data are protected",
      status: "active",
      type: "output",
      bannedTerms: [],
      requiredTerms: [],
      requireCitations: false,
      allowCustomData: true,
      sensitiveDataPatterns: ["ssn", "credit_card"],
      actionOnViolation: "redact",
      severityLevel: "medium",
      metadata: { category: "privacy", version: "1.0" }
    },
    {
      id: "guard_approval_required",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "approval_required",
      name: "Human Approval Gate",
      description: "Requires human approval for external actions",
      status: "active",
      type: "tool_call",
      bannedTerms: [],
      requiredTerms: [],
      requireCitations: false,
      allowCustomData: true,
      sensitiveDataPatterns: [],
      actionOnViolation: "approve_with_flag",
      severityLevel: "high",
      metadata: { category: "governance", version: "1.0" }
    }
  );

  state.toolRegistry.push(
    {
      id: "tool_email",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "send_email",
      name: "Send Email",
      description: "Sends an email to specified recipients",
      type: "builtin",
      status: "active",
      category: "communication",
      inputSchema: { to: "string", subject: "string", body: "string", cc: "string?" },
      outputSchema: { success: "boolean", messageId: "string" },
      config: {},
      timeoutMs: 30000,
      requiresApproval: true,
      capability: "communication",
      version: "1.0.0",
      metadata: {}
    },
    {
      id: "tool_calculator",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "calculator",
      name: "Calculator",
      description: "Performs mathematical calculations",
      type: "builtin",
      status: "active",
      category: "computation",
      inputSchema: { expression: "string" },
      outputSchema: { result: "number" },
      config: {},
      timeoutMs: 5000,
      requiresApproval: false,
      capability: "computation",
      version: "1.0.0",
      metadata: {}
    },
    {
      id: "tool_crm_update",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "crm_update",
      name: "CRM Update",
      description: "Updates customer records in CRM",
      type: "http",
      status: "active",
      category: "integration",
      inputSchema: { entityType: "string", entityId: "string", fields: "object" },
      outputSchema: { success: "boolean", updated: "object" },
      config: { baseUrl: "https://crm.example.com/api" },
      timeoutMs: 10000,
      requiresApproval: true,
      capability: "crm",
      version: "1.0.0",
      metadata: {}
    },
    {
      id: "tool_document_gen",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "document_generator",
      name: "Document Generator",
      description: "Generates PDF or DOCX documents",
      type: "builtin",
      status: "active",
      category: "data",
      inputSchema: { templateId: "string", data: "object", format: "string" },
      outputSchema: { documentId: "string", url: "string" },
      config: {},
      timeoutMs: 60000,
      requiresApproval: false,
      capability: "document_generation",
      version: "1.0.0",
      metadata: {}
    }
  );

  state.agentTemplates.push(
    {
      id: "tmpl_support_agent",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "support_agent",
      name: "Customer Support Agent",
      description: "Handles customer inquiries and support tickets",
      status: "active",
      category: "support",
      template: "You are a helpful customer support agent. Assist customers with their inquiries professionally.",
      variables: ["customerName", "ticketId", "issueType"],
      defaultCapabilities: ["read_ticket", "reply_email", "create_task", "escalate"],
      requiredTools: ["tool_email"],
      recommendedGuardrails: ["guard_safe_content"],
      usageExamples: ["Handle support ticket", "Respond to customer query", "Escalate complex issues"],
      tags: ["support", "customer-service", "helpdesk"],
      version: 1,
      createdBy: "seed"
    },
    {
      id: "tmpl_sales_agent",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "sales_agent",
      name: "Sales Assistant Agent",
      description: "Assists with sales activities and lead qualification",
      status: "active",
      category: "sales",
      template: "You are a professional sales assistant. Help qualify leads and assist with sales processes.",
      variables: ["leadName", "company", "product"],
      defaultCapabilities: ["qualify_lead", "update_crm", "send_proposal", "schedule_meeting"],
      requiredTools: ["tool_crm_update", "tool_email"],
      recommendedGuardrails: ["guard_data_privacy"],
      usageExamples: ["Qualify a lead", "Generate proposal", "Follow up with prospect"],
      tags: ["sales", "crm", "lead-generation"],
      version: 1,
      createdBy: "seed"
    },
    {
      id: "tmpl_research_agent",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "research_agent",
      name: "Research Agent",
      description: "Performs research and analysis tasks",
      status: "active",
      category: "research",
      template: "You are a thorough research assistant. Gather information, analyze data, and provide insights.",
      variables: ["topic", "sources", "depth"],
      defaultCapabilities: ["web_search", "summarize", "extract_key_points", "cite_sources"],
      requiredTools: [],
      recommendedGuardrails: ["guard_safe_content"],
      usageExamples: ["Research market trends", "Analyze competitors", "Summarize articles"],
      tags: ["research", "analysis", "data"],
      version: 1,
      createdBy: "seed"
    },
    {
      id: "tmpl_code_reviewer",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "code_reviewer",
      name: "Code Review Agent",
      description: "Reviews code for quality, security, and best practices",
      status: "active",
      category: "code_review",
      template: "You are an expert code reviewer. Analyze code for quality, security issues, and best practices.",
      variables: ["language", "repo", "prNumber"],
      defaultCapabilities: ["read_code", "check_style", "find_bugs", "suggest_improvements"],
      requiredTools: [],
      recommendedGuardrails: ["guard_safe_content"],
      usageExamples: ["Review PR", "Check code quality", "Find security issues"],
      tags: ["code-review", "quality", "security"],
      version: 1,
      createdBy: "seed"
    }
  );

  state.agents.push(
    {
      id: "agent_support",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "support_agent_demo",
      name: "Demo Support Agent",
      description: "Customer support agent for handling inquiries",
      status: "active",
      version: 1,
      agentType: "assistant",
      capabilities: ["read_ticket", "reply_email", "create_task", "escalate"],
      promptTemplate: "You are a helpful customer support agent. Assist customers professionally and efficiently.",
      variables: { tone: "friendly", responseTime: "fast" },
      knowledgeBaseIds: [],
      toolIds: ["tool_email"],
      guardrailIds: ["guard_safe_content", "guard_approval_required"],
      memoryEnabled: true,
      workflowEnabled: true,
      outputFormat: "text",
      metadata: { demo: true },
      createdBy: "seed"
    },
    {
      id: "agent_sales",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "sales_agent_demo",
      name: "Demo Sales Assistant",
      description: "Sales assistant for lead qualification and CRM updates",
      status: "active",
      version: 1,
      agentType: "assistant",
      capabilities: ["qualify_lead", "update_crm", "send_proposal", "schedule_meeting"],
      promptTemplate: "You are a professional sales assistant. Help qualify leads and assist with sales processes.",
      variables: { style: "consultative", focus: "conversion" },
      knowledgeBaseIds: [],
      toolIds: ["tool_crm_update", "tool_email", "tool_document_gen"],
      guardrailIds: ["guard_safe_content", "guard_data_privacy", "guard_approval_required"],
      memoryEnabled: true,
      workflowEnabled: false,
      outputFormat: "structured",
      metadata: { demo: true },
      createdBy: "seed"
    },
    {
      id: "agent_researcher",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "research_agent_demo",
      name: "Demo Research Agent",
      description: "Research agent for gathering and analyzing information",
      status: "active",
      version: 1,
      agentType: "researcher",
      capabilities: ["web_search", "summarize", "extract_key_points", "cite_sources"],
      promptTemplate: "You are a thorough research assistant. Gather information, analyze data, and provide well-cited insights.",
      variables: { depth: "comprehensive", format: "detailed" },
      knowledgeBaseIds: [],
      toolIds: ["tool_calculator"],
      guardrailIds: ["guard_safe_content"],
      memoryEnabled: true,
      workflowEnabled: false,
      outputFormat: "markdown",
      metadata: { demo: true },
      createdBy: "seed"
    },
    {
      id: "agent_builder",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "agent_builder_demo",
      name: "Agent Builder Assistant",
      description: "Helps create and configure new AI agents",
      status: "active",
      version: 1,
      agentType: "builder",
      capabilities: ["create_agent", "configure_tools", "set_guardrails", "test_agent"],
      promptTemplate: "You are an agent builder assistant. Help users create, configure, and deploy AI agents.",
      variables: { mode: "interactive", templates: "enabled" },
      knowledgeBaseIds: [],
      toolIds: [],
      guardrailIds: ["guard_safe_content"],
      memoryEnabled: true,
      workflowEnabled: true,
      outputFormat: "structured",
      metadata: { demo: true, type: "builder" },
      createdBy: "seed"
    }
  );

  state.agentWorkflows.push(
    {
      id: "wf_support_ticket",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "support_ticket_flow",
      name: "Support Ticket Workflow",
      description: "Standard workflow for handling support tickets",
      status: "active",
      agentId: "agent_support",
      steps: [
        { stepId: "step_1", name: "Read Ticket", order: 1, type: "prompt", config: { action: "read_ticket" }, nextStepOnSuccess: "step_2" },
        { stepId: "step_2", name: "Analyze Issue", order: 2, type: "prompt", config: { action: "analyze" }, nextStepOnSuccess: "step_3" },
        { stepId: "step_3", name: "Generate Response", order: 3, type: "prompt", config: { action: "generate_response" }, nextStepOnSuccess: "step_4" },
        { stepId: "step_4", name: "Send Email", order: 4, type: "tool_call", config: { action: "send_email" }, toolId: "tool_email", nextStepOnSuccess: "step_5" },
        { stepId: "step_5", name: "Update Ticket", order: 5, type: "tool_call", config: { action: "update_status" } }
      ],
      triggerType: "manual",
      triggerConfig: {},
      conditions: [],
      errorHandling: { onError: "retry", maxRetries: 3, fallbackStepId: "step_5" },
      timeoutSeconds: 300,
      retryPolicy: { maxAttempts: 3, backoffMultiplier: 2, initialDelayMs: 1000, maxDelayMs: 30000 },
      version: 1,
      createdBy: "seed"
    },
    {
      id: "wf_lead_qualification",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "lead_qualification_flow",
      name: "Lead Qualification Workflow",
      description: "Workflow for qualifying sales leads",
      status: "active",
      agentId: "agent_sales",
      steps: [
        { stepId: "step_1", name: "Assess Lead", order: 1, type: "prompt", config: { action: "assess_lead" }, nextStepOnSuccess: "step_2" },
        { stepId: "step_2", name: "Score Lead", order: 2, type: "prompt", config: { action: "score_lead" }, nextStepOnSuccess: "step_3" },
        { stepId: "step_3", name: "Update CRM", order: 3, type: "tool_call", config: { action: "update_crm" }, toolId: "tool_crm_update" },
        { stepId: "step_4", name: "Send Proposal", order: 4, type: "tool_call", config: { action: "send_proposal" }, toolId: "tool_email", guardrailIds: ["guard_approval_required"] }
      ],
      triggerType: "manual",
      triggerConfig: {},
      conditions: [],
      errorHandling: { onError: "pause", maxRetries: 2 },
      timeoutSeconds: 600,
      retryPolicy: { maxAttempts: 2, backoffMultiplier: 1.5, initialDelayMs: 500, maxDelayMs: 15000 },
      version: 1,
      createdBy: "seed"
    }
  );

  state.agentMemories.push(
    {
      id: "mem_demo_pref",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      agentId: "agent_support",
      memoryType: "user_preference",
      content: "Customers prefer quick, concise responses with actionable next steps.",
      importance: 8,
      source: "system",
      linkedEntityIds: [],
      tags: ["preferences", "support", "response-style"],
      metadata: {}
    },
    {
      id: "mem_demo_knowledge",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      agentId: "agent_researcher",
      memoryType: "knowledge",
      content: "Research should always cite sources and include confidence levels for claims.",
      importance: 9,
      source: "system",
      linkedEntityIds: [],
      tags: ["research", "best-practices", "citations"],
      metadata: {}
    }
  );

  state.evaluationSuites.push({
    id: "evalsuite_support",
    tenantId,
    createdAt,
    updatedAt: createdAt,
    key: "support_agent_eval",
    name: "Support Agent Evaluation",
    description: "Evaluation suite for support agent quality",
    status: "active",
    agentId: "agent_support",
    version: 1,
    cases: [
      {
        id: "case_1",
        name: "Handles greeting",
        input: { query: "Hello, I need help with my account" },
        expectedContains: ["help", "account"],
        forbiddenTerms: [],
        evaluationCriteria: { correctness: 8, relevance: 9, safety: 10, formatCompliance: 8, toolUsageAccuracy: 7 },
        metadata: {}
      },
      {
        id: "case_2",
        name: "Handles complaint",
        input: { query: "I'm very frustrated with your service" },
        expectedContains: ["apologize", "understand", "resolve"],
        forbiddenTerms: ["frustrating"],
        evaluationCriteria: { correctness: 8, relevance: 9, safety: 10, formatCompliance: 8, toolUsageAccuracy: 7 },
        metadata: {}
      }
    ],
    tags: ["support", "evaluation", "qa"],
    createdBy: "seed"
  });

  state.events.push({
    id: "event_bootstrap",
    tenantId,
    createdAt,
    updatedAt: createdAt,
    type: "agenticos.seeded",
    source: "AgenticOS",
    data: { message: "AgenticOS demo data seeded", agents: 4, tools: 4, guardrails: 3 }
  });

  return state;
}
