const assert = require('node:assert/strict');
const test = require('node:test');
const { unlinkSync } = require('node:fs');
const { join } = require('node:path');
const { DataStore } = require('../dist/core/datastore.js');
const { EventBus } = require('../dist/core/event-bus.js');
const { SalesService } = require('../dist/services/sales.service.js');
const { createSeedState } = require('../dist/seed-state.js');
const { hasPermission } = require('../dist/core/security.js');
function makeService() { const file = join(process.cwd(), 'data', `salesos-test-${Date.now()}-${Math.random().toString(36).slice(2)}.json`); const store = new DataStore(file); store.reset(createSeedState('test-tenant')); const service = new SalesService(store, new EventBus(store)); const actor = { tenantId: 'test-tenant', userId: 'tester', role: 'sales_admin' }; return { service, actor, file }; }
function cleanup(file) { try { unlinkSync(file); } catch {} }

test('SalesOS seed overview returns sales analytics', () => { const { service, actor, file } = makeService(); const overview = service.overview(actor); assert.equal(overview.counts.leads, 3); assert.equal(overview.counts.deals, 3); assert.equal(overview.counts.quotes, 2); assert.equal(overview.analytics.openDeals, 2); assert.equal(overview.analytics.wonDeals, 1); assert.equal(overview.analytics.wonRevenue, 320000); cleanup(file); });

test('SalesOS creates, qualifies, and converts leads into deals', () => { const { service, actor, file } = makeService(); const lead = service.createLead(actor, { firstName: 'Dev', lastName: 'Sen', email: 'dev@acme.example', company: 'Acme Retail', source: 'referral', expectedValue: 250000, tags: ['enterprise'] }); assert.ok(lead.score >= 70); const qualified = service.qualifyLead(actor, lead.id); assert.equal(qualified.status, 'qualified'); const result = service.convertLead(actor, lead.id, { title: 'Acme Retail SalesOS Deal', closeDate: '2026-07-31' }); assert.equal(result.lead.status, 'converted'); assert.equal(result.deal.leadId, lead.id); assert.equal(service.getDeal(actor, result.deal.id).accountName, 'Acme Retail'); cleanup(file); });

test('SalesOS creates pipeline stages, moves deals, and closes deals', () => { const { service, actor, file } = makeService(); const pipeline = service.createPipeline(actor, { code: 'ENTERPRISE', name: 'Enterprise Pipeline' }); const discovery = service.createPipelineStage(actor, { pipelineId: pipeline.id, code: 'DISC', name: 'Discovery', order: 1, probability: 30, forecastCategory: 'pipeline' }); const commit = service.createPipelineStage(actor, { pipelineId: pipeline.id, code: 'COMMIT', name: 'Commit', order: 2, probability: 85, forecastCategory: 'commit' }); const deal = service.createDeal(actor, { title: 'Enterprise Platform Deal', accountName: 'Enterprise Co', pipelineId: pipeline.id, stageId: discovery.id, ownerId: 'rep_maya', value: 700000, closeDate: '2026-08-15' }); const moved = service.moveDealStage(actor, deal.id, commit.id); assert.equal(moved.probability, 85); assert.equal(moved.forecastCategory, 'commit'); const won = service.markDealWon(actor, deal.id); assert.equal(won.status, 'won'); assert.equal(won.probability, 100); cleanup(file); });

test('SalesOS creates quotes, calculates totals, and acceptance closes deal', () => { const { service, actor, file } = makeService(); const quote = service.createQuote(actor, { dealId: 'deal_brandlyup_pixel', validUntil: '2026-06-30', lineItems: [{ productId: 'prod_growth_pack', quantity: 2, discountPct: 10 }] }); assert.equal(quote.subtotal, 90000); assert.equal(quote.discountTotal, 9000); assert.equal(quote.taxTotal, 14580); assert.equal(quote.total, 95580); assert.equal(service.approveQuote(actor, quote.id).status, 'approved'); assert.equal(service.sendQuote(actor, quote.id).status, 'sent'); assert.equal(service.acceptQuote(actor, quote.id).status, 'accepted'); assert.equal(service.getDeal(actor, 'deal_brandlyup_pixel').status, 'won'); cleanup(file); });

test('SalesOS creates proposals, activities, and forecasts', () => { const { service, actor, file } = makeService(); const proposal = service.createProposal(actor, { dealId: 'deal_appneurox_northstar', quoteId: 'quote_northstar', title: 'Northstar Expansion', summary: 'Expansion proposal', content: 'Detailed expansion scope.' }); assert.equal(service.sendProposal(actor, proposal.id).status, 'sent'); const activity = service.createActivity(actor, { type: 'call', subject: 'Decision call', relatedType: 'deal', relatedId: 'deal_appneurox_northstar', dueAt: '2026-06-10T10:00:00.000Z' }); const completed = service.completeActivity(actor, activity.id, 'Decision maker asked for revision'); assert.equal(completed.status, 'done'); const forecast = service.createForecast(actor, { periodStart: '2026-05-01', periodEnd: '2026-06-30', currency: 'INR' }); assert.equal(forecast.summary.openDealCount, 2); assert.equal(forecast.summary.closedWonValue, 320000); assert.ok(forecast.summary.expectedRevenue > forecast.summary.closedWonValue); cleanup(file); });

test('SalesOS records events and audit logs', () => { const { service, actor, file } = makeService(); const lead = service.createLead(actor, { firstName: 'Mira', lastName: 'Shah', email: 'mira@sample.example', source: 'web', expectedValue: 100000 }); const events = service.listEvents(actor); const auditLogs = service.listAuditLogs(actor); assert.ok(events.some((event) => event.event === 'lead.created' && event.data.leadId === lead.id)); assert.ok(auditLogs.some((log) => log.action === 'lead.create' && log.entityId === lead.id)); cleanup(file); });

test('SalesOS permissions protect operations by role', () => { assert.equal(hasPermission('viewer', 'sales.leads.write'), false); assert.equal(hasPermission('sales_rep', 'sales.deals.write'), true); assert.equal(hasPermission('sales_rep', 'sales.quotes.approve'), false); assert.equal(hasPermission('sales_manager', 'sales.quotes.approve'), true); assert.equal(hasPermission('sales_ops', 'sales.pipeline.write'), true); assert.equal(hasPermission('quote_manager', 'sales.quotes.approve'), true); assert.equal(hasPermission('auditor', 'sales.audit.read'), true); assert.equal(hasPermission('sales_admin', 'sales.products.write'), true); });
