import { AnalyticsState } from "./domain";
import { emptyState } from "./domain";
import { nowIso } from "./core/id";

export function createSeedState(tenantId = "demo-tenant"): AnalyticsState {
  const state = emptyState();
  const createdAt = nowIso();

  state.metrics.push(
    {
      id: "metric_revenue",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "revenue",
      name: "Monthly Revenue",
      description: "Total revenue generated per month",
      status: "active",
      formula: "sum(invoices.amount)",
      aggregation: "sum",
      unit: "USD",
      category: "finance",
      tags: ["revenue", "finance", "monthly"],
      format: "currency",
      freshness: "daily",
    },
    {
      id: "metric_active_users",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "active_users",
      name: "Active Users",
      description: "Number of active users in the last 30 days",
      status: "active",
      formula: "count(distinct users.id)",
      aggregation: "count",
      unit: "users",
      category: "product",
      tags: ["users", "engagement"],
      format: "number",
      freshness: "daily",
    },
    {
      id: "metric_conversion_rate",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "conversion_rate",
      name: "Conversion Rate",
      description: "Percentage of visitors who convert to customers",
      status: "active",
      formula: "leads.closed / leads.total * 100",
      aggregation: "avg",
      unit: "%",
      category: "marketing",
      tags: ["conversion", "marketing"],
      format: "percent",
      freshness: "daily",
    },
    {
      id: "metric_ai_requests",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "ai_requests",
      name: "AI Requests",
      description: "Total AI API requests",
      status: "active",
      formula: "count(ai_requests.id)",
      aggregation: "sum",
      unit: "requests",
      category: "ai",
      tags: ["ai", "usage"],
      format: "number",
      freshness: "hourly",
    }
  );

  state.kpis.push(
    {
      id: "kpi_monthly_revenue",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "monthly_revenue",
      name: "Monthly Revenue Target",
      description: "Target monthly revenue for the sales team",
      status: "active",
      metricId: "metric_revenue",
      target: 1000000,
      current: 850000,
      unit: "USD",
      aggregation: "sum",
      direction: "higher_is_better",
      category: "finance",
      tags: ["revenue", "target", "monthly"],
      thresholds: [
        { label: "Critical", min: 0, max: 500000, color: "#ef4444" },
        { label: "Warning", min: 500000, max: 750000, color: "#f59e0b" },
        { label: "Good", min: 750000, max: 900000, color: "#22c55e" },
        { label: "Excellent", min: 900000, max: 1000000, color: "#3b82f6" },
      ],
      history: [
        { timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), value: 750000 },
        { timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(), value: 780000 },
        { timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(), value: 800000 },
        { timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(), value: 820000 },
        { timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), value: 840000 },
        { timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), value: 850000 },
      ],
    },
    {
      id: "kpi_user_growth",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "user_growth",
      name: "Monthly Active Users Growth",
      description: "Month-over-month growth in active users",
      status: "active",
      metricId: "metric_active_users",
      target: 50000,
      current: 42500,
      unit: "users",
      aggregation: "count",
      direction: "higher_is_better",
      category: "product",
      tags: ["users", "growth", "maus"],
    },
    {
      id: "kpi_conversion",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "conversion_rate",
      name: "Lead Conversion Rate",
      description: "Percentage of leads converting to customers",
      status: "active",
      metricId: "metric_conversion_rate",
      target: 15,
      current: 12.5,
      unit: "%",
      aggregation: "avg",
      direction: "higher_is_better",
      category: "sales",
      tags: ["conversion", "sales", "leads"],
    }
  );

  state.dashboards.push(
    {
      id: "dash_executive",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "executive-dashboard",
      name: "Executive Dashboard",
      description: "High-level metrics for executive leadership",
      status: "active",
      tags: ["executive", "overview", "leadership"],
      layout: {
        columns: 12,
        rows: 8,
        widgets: [],
      },
      ownerId: "user_admin",
      sharedWith: ["user_admin", "user_ceo"],
      refreshInterval: 300,
      filters: [],
    },
    {
      id: "dash_sales",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "sales-dashboard",
      name: "Sales Dashboard",
      description: "Revenue, pipeline, and sales performance metrics",
      status: "active",
      tags: ["sales", "revenue", "pipeline"],
      layout: {
        columns: 12,
        rows: 8,
        widgets: [],
      },
      ownerId: "user_admin",
      sharedWith: ["user_admin", "user_sales_manager"],
      refreshInterval: 600,
    },
    {
      id: "dash_product",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "product-dashboard",
      name: "Product Dashboard",
      description: "User engagement, retention, and feature adoption",
      status: "active",
      tags: ["product", "users", "engagement"],
      layout: {
        columns: 12,
        rows: 8,
        widgets: [],
      },
      ownerId: "user_admin",
      sharedWith: ["user_admin", "user_pm"],
      refreshInterval: 3600,
    },
    {
      id: "dash_ai_usage",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "ai-usage-dashboard",
      name: "AI Usage Dashboard",
      description: "AI requests, token usage, and cost analytics",
      status: "active",
      tags: ["ai", "usage", "cost"],
      layout: {
        columns: 12,
        rows: 8,
        widgets: [],
      },
      ownerId: "user_admin",
      sharedWith: ["user_admin"],
      refreshInterval: 300,
    }
  );

  state.widgets.push(
    {
      id: "widget_rev_chart",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      dashboardId: "dash_executive",
      key: "revenue-trend",
      name: "Revenue Trend",
      description: "Monthly revenue over the last 12 months",
      type: "chart",
      chartType: "line",
      metricId: "metric_revenue",
      config: {
        title: "Monthly Revenue",
        aggregation: "sum",
        dateRange: "12m",
        showTrend: true,
        colors: ["#3b82f6"],
      },
      position: { widgetId: "widget_rev_chart", x: 0, y: 0, w: 8, h: 4 },
    },
    {
      id: "widget_rev_kpi",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      dashboardId: "dash_executive",
      key: "revenue-kpi",
      name: "Revenue KPI",
      type: "kpi",
      kpiId: "kpi_monthly_revenue",
      config: {
        title: "Monthly Revenue",
        showTrend: true,
        format: "currency",
      },
      position: { widgetId: "widget_rev_kpi", x: 8, y: 0, w: 4, h: 4 },
    },
    {
      id: "widget_users_kpi",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      dashboardId: "dash_executive",
      key: "users-kpi",
      name: "Active Users KPI",
      type: "kpi",
      kpiId: "kpi_user_growth",
      config: {
        title: "Active Users",
        showTrend: true,
        format: "number",
      },
      position: { widgetId: "widget_users_kpi", x: 0, y: 4, w: 6, h: 4 },
    },
    {
      id: "widget_conv_kpi",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      dashboardId: "dash_executive",
      key: "conversion-kpi",
      name: "Conversion Rate KPI",
      type: "kpi",
      kpiId: "kpi_conversion",
      config: {
        title: "Conversion Rate",
        showTrend: true,
        format: "percent",
      },
      position: { widgetId: "widget_conv_kpi", x: 6, y: 4, w: 6, h: 4 },
    }
  );

  state.funnels.push(
    {
      id: "funnel_lead_conversion",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "lead-conversion-funnel",
      name: "Lead Conversion Funnel",
      description: "Website visitor to paying customer conversion path",
      status: "active",
      steps: [
        { name: "Website Visitor", event: "page_view", order: 1 },
        { name: "Lead Form", event: "lead_form_submit", order: 2 },
        { name: "Qualified Lead", event: "lead_qualified", order: 3 },
        { name: "Proposal Sent", event: "proposal_sent", order: 4 },
        { name: "Deal Won", event: "deal_closed_won", order: 5 },
      ],
      conversionWindow: 30,
      tags: ["sales", "conversion", "leads"],
    },
    {
      id: "funnel_onboarding",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "user-onboarding-funnel",
      name: "User Onboarding Funnel",
      description: "New user sign-up to first value journey",
      status: "active",
      steps: [
        { name: "Sign Up", event: "user_signup", order: 1 },
        { name: "Profile Complete", event: "profile_completed", order: 2 },
        { name: "First Action", event: "first_action", order: 3 },
        { name: "First Value", event: "first_value", order: 4 },
        { name: "Retained", event: "retained_30d", order: 5 },
      ],
      conversionWindow: 14,
      tags: ["onboarding", "retention", "activation"],
    }
  );

  state.cohorts.push(
    {
      id: "cohort_monthly_signups",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "monthly-signup-cohort",
      name: "Monthly Signup Cohorts",
      description: "User retention by signup month",
      status: "active",
      type: "retention",
      definition: {
        cohortBy: "signup_date",
        actions: [{ event: "user_login" }],
        grouping: "month",
      },
      dateRange: {
        start: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
        end: new Date().toISOString(),
      },
      tags: ["retention", "cohort", "monthly"],
    },
    {
      id: "cohort_paid_users",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "paid-user-cohort",
      name: "Paid User Cohorts",
      description: "Revenue retention by paid user cohort",
      status: "active",
      type: "revenue",
      definition: {
        cohortBy: "first_purchase",
        actions: [{ event: "purchase" }],
        grouping: "month",
      },
      dateRange: {
        start: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
        end: new Date().toISOString(),
      },
      tags: ["revenue", "cohort", "paid"],
    }
  );

  state.segments.push(
    {
      id: "segment_power_users",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "power-users",
      name: "Power Users",
      description: "Users with high engagement and feature usage",
      status: "active",
      type: "user",
      rules: [
        { field: "login_count", operator: "gte", value: 50 },
        { field: "features_used", operator: "gte", value: 10 },
        { field: "last_login_days", operator: "lte", value: 7 },
      ],
      tags: ["engagement", "high-value"],
    },
    {
      id: "segment_at_risk",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "at-risk-users",
      name: "At-Risk Users",
      description: "Users showing signs of churn risk",
      status: "active",
      type: "user",
      rules: [
        { field: "last_login_days", operator: "gte", value: 30 },
        { field: "features_used", operator: "lte", value: 3 },
        { field: "support_tickets", operator: "gte", value: 2 },
      ],
      tags: ["churn", "at-risk"],
    },
    {
      id: "segment_trial_users",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "trial-users",
      name: "Trial Users",
      description: "Users in trial period",
      status: "active",
      type: "user",
      rules: [
        { field: "plan", operator: "eq", value: "trial" },
        { field: "trial_days_remaining", operator: "gte", value: 0 },
      ],
      tags: ["trial", "conversion-target"],
    }
  );

  state.alerts.push(
    {
      id: "alert_revenue_drop",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "revenue-drop-alert",
      name: "Revenue Drop Alert",
      description: "Alert when daily revenue drops by more than 20%",
      status: "active",
      metricId: "metric_revenue",
      condition: {
        metric: "revenue",
        operator: "change_pct",
        threshold: 20,
        comparisonWindow: 1,
        changePercent: -20,
      },
      notificationChannels: ["email", "slack"],
    },
    {
      id: "alert_high_ai_cost",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "ai-cost-alert",
      name: "High AI Cost Alert",
      description: "Alert when AI costs exceed daily budget",
      status: "active",
      metricId: "metric_ai_requests",
      condition: {
        metric: "ai_cost",
        operator: "gt",
        threshold: 10000,
      },
      notificationChannels: ["email"],
    },
    {
      id: "alert_conversion_drop",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "conversion-drop-alert",
      name: "Conversion Rate Drop Alert",
      description: "Alert when conversion rate drops below 10%",
      status: "active",
      metricId: "metric_conversion_rate",
      condition: {
        metric: "conversion_rate",
        operator: "lt",
        threshold: 10,
      },
      notificationChannels: ["email", "slack"],
    }
  );

  state.reports.push(
    {
      id: "report_monthly_exec",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "monthly-executive-report",
      name: "Monthly Executive Report",
      description: "High-level overview of business metrics for leadership",
      status: "active",
      type: "executive",
      dashboardIds: ["dash_executive"],
      kpiIds: ["kpi_monthly_revenue", "kpi_user_growth", "kpi_conversion"],
      sections: [
        {
          title: "Executive Summary",
          type: "summary",
          content: "Key highlights and metrics for the month",
        },
        {
          title: "Revenue Performance",
          type: "chart",
          widgetId: "widget_rev_chart",
        },
        {
          title: "KPI Scorecard",
          type: "kpi",
          kpiIds: ["kpi_monthly_revenue", "kpi_user_growth", "kpi_conversion"],
        },
      ],
      format: "pdf",
      ownerId: "user_admin",
      tags: ["executive", "monthly", "report"],
      schedule: {
        frequency: "monthly",
        dayOfMonth: 1,
        time: "09:00",
        recipients: ["ceo@appneural.com", "cfo@appneural.com"],
        enabled: true,
      },
    },
    {
      id: "report_weekly_sales",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "weekly-sales-report",
      name: "Weekly Sales Report",
      description: "Sales pipeline and performance metrics",
      status: "active",
      type: "sales",
      dashboardIds: ["dash_sales"],
      kpiIds: [],
      sections: [],
      format: "pdf",
      ownerId: "user_admin",
      tags: ["sales", "weekly", "report"],
      schedule: {
        frequency: "weekly",
        dayOfWeek: 1,
        time: "08:00",
        recipients: ["sales@appneural.com"],
        enabled: true,
      },
    }
  );

  state.attributionModels.push(
    {
      id: "attr_last_touch",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "last-touch-attribution",
      name: "Last Touch Attribution",
      description: "100% credit to the last touchpoint before conversion",
      type: "last_touch",
      status: "active",
      config: {
        lookbackWindow: 30,
      },
      touchpoints: [
        { name: "Organic Search", event: "organic_search" },
        { name: "Paid Ad", event: "paid_ad_click" },
        { name: "Social Media", event: "social_click" },
        { name: "Email", event: "email_click" },
        { name: "Direct", event: "direct_visit" },
      ],
    },
    {
      id: "attr_linear",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "linear-attribution",
      name: "Linear Attribution",
      description: "Equal credit to all touchpoints in the customer journey",
      type: "linear",
      status: "active",
      config: {
        lookbackWindow: 30,
      },
      touchpoints: [
        { name: "Organic Search", event: "organic_search" },
        { name: "Paid Ad", event: "paid_ad_click" },
        { name: "Social Media", event: "social_click" },
        { name: "Email", event: "email_click" },
        { name: "Direct", event: "direct_visit" },
      ],
    },
    {
      id: "attr_time_decay",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "time-decay-attribution",
      name: "Time Decay Attribution",
      description: "More credit to touchpoints closer to conversion",
      type: "time_decay",
      status: "active",
      config: {
        lookbackWindow: 30,
      },
      touchpoints: [
        { name: "Organic Search", event: "organic_search" },
        { name: "Paid Ad", event: "paid_ad_click" },
        { name: "Social Media", event: "social_click" },
        { name: "Email", event: "email_click" },
        { name: "Direct", event: "direct_visit" },
      ],
    }
  );

  state.dataSources.push(
    {
      id: "ds_postgres",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "postgres-dw",
      name: "PostgreSQL Data Warehouse",
      description: "Main data warehouse for business data",
      type: "database",
      status: "active",
      config: {
        host: "db.example.com",
        port: 5432,
        database: "analytics",
      },
      maskedCredentials: "***masked***",
      lastSyncAt: nowIso(),
      syncStatus: "idle",
      tags: ["database", "primary"],
    },
    {
      id: "ds_stripe",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "stripe-payments",
      name: "Stripe Payments",
      description: "Payment and subscription data from Stripe",
      type: "integration",
      status: "active",
      config: {
        webhookUrl: "https://api.appneural.com/webhooks/stripe",
      },
      maskedCredentials: "***masked***",
      lastSyncAt: nowIso(),
      syncStatus: "idle",
      tags: ["payments", "stripe"],
    },
    {
      id: "ds_mixpanel",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "mixpanel-events",
      name: "Mixpanel Analytics",
      description: "User behavior and event analytics",
      type: "integration",
      status: "active",
      config: {
        projectId: "12345",
      },
      maskedCredentials: "***masked***",
      lastSyncAt: nowIso(),
      syncStatus: "idle",
      tags: ["analytics", "events", "mixpanel"],
    }
  );

  state.events.push(
    {
      id: "evt_demo_seed",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      type: "analytics.seeded",
      source: "AnalyticsOS",
      data: { message: "AnalyticsOS demo data seeded" },
    },
    {
      id: "evt_page_view",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      type: "page_view",
      source: "WebsiteOS",
      userId: "user_123",
      data: { page: "/dashboard", duration: 120 },
    },
    {
      id: "evt_lead_created",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      type: "lead_created",
      source: "SalesOS",
      data: { leadId: "lead_456", source: "website" },
    },
    {
      id: "evt_deal_won",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      type: "deal_closed_won",
      source: "SalesOS",
      data: { dealId: "deal_789", value: 50000 },
    }
  );

  state.insights.push(
    {
      id: "insight_rev_trend",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      type: "trend",
      title: "Revenue Growth Trend",
      description: "Revenue has increased by 15% month-over-month for the past 3 months",
      severity: "info",
      metricId: "metric_revenue",
      data: {
        trend: "increasing",
        growthRate: 15,
        months: 3,
      },
      recommendations: [
        "Continue current marketing strategy",
        "Focus on high-margin products",
      ],
    },
    {
      id: "insight_conv_drop",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      type: "anomaly",
      title: "Conversion Rate Drop Detected",
      description: "Conversion rate dropped by 20% compared to last week. Investigate potential causes.",
      severity: "warning",
      metricId: "metric_conversion_rate",
      data: {
        currentRate: 10.5,
        expectedRate: 13.2,
        dropPercent: 20,
      },
      recommendations: [
        "Check for website issues",
        "Review recent marketing campaign changes",
        "Analyze competitor activity",
      ],
    },
    {
      id: "insight_power_users",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      type: "recommendation",
      title: "Power User Opportunity",
      description: "Power users (top 10%) generate 60% of engagement. Consider dedicated onboarding for new users.",
      severity: "info",
      data: {
        powerUserCount: 500,
        totalUsers: 5000,
        powerUserEngagement: 60,
      },
      recommendations: [
        "Create power user mentorship program",
        "Develop onboarding flows based on power user behavior",
      ],
    }
  );

  state.forecasts.push(
    {
      id: "forecast_revenue",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "revenue-forecast",
      name: "Revenue Forecast",
      description: "30-day revenue forecast based on historical data",
      status: "active",
      metricId: "metric_revenue",
      model: "linear",
      horizon: 30,
      confidence: 0.95,
      data: [
        { timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), value: 750000 },
        { timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(), value: 780000 },
        { timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(), value: 800000 },
        { timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(), value: 820000 },
        { timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), value: 840000 },
        { timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), value: 850000 },
      ],
      predictions: [
        { timestamp: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), value: 875000, predicted: true, lowerBound: 850000, upperBound: 900000 },
        { timestamp: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(), value: 900000, predicted: true, lowerBound: 870000, upperBound: 930000 },
        { timestamp: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(), value: 920000, predicted: true, lowerBound: 880000, upperBound: 960000 },
        { timestamp: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(), value: 940000, predicted: true, lowerBound: 890000, upperBound: 990000 },
        { timestamp: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(), value: 960000, predicted: true, lowerBound: 900000, upperBound: 1020000 },
        { timestamp: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(), value: 980000, predicted: true, lowerBound: 910000, upperBound: 1050000 },
      ],
      tags: ["revenue", "forecast", "30d"],
    }
  );

  return state;
}
