import { emptyState } from "./core/datastore";
import { nowIso, newId, plusDays } from "./core/id";
import { InventoryState } from "./types";

export function createSeedState(tenantId = "demo-tenant"): InventoryState {
  const state = emptyState();
  const createdAt = nowIso();

  state.items.push(
    {
      id: "item_laptop_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      sku: "LAP-DELL-001",
      name: "Dell Laptop XPS 15",
      description: "Dell XPS 15 laptop for employees",
      category: "Electronics",
      unit: "piece",
      brand: "Dell",
      model: "XPS 15",
      barcode: "1234567890123",
      qrCode: undefined,
      costPrice: 85000,
      sellingPrice: 120000,
      minimumStock: 5,
      maximumStock: 50,
      reorderLevel: 10,
      status: "active",
      tags: ["laptop", "electronics", "asset"],
      metadata: {}
    },
    {
      id: "item_projector_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      sku: "PROJ-SONY-001",
      name: "Sony Projector VPL-XW5000",
      description: "4K projector for training rooms",
      category: "Electronics",
      unit: "piece",
      brand: "Sony",
      model: "VPL-XW5000",
      barcode: "1234567890124",
      qrCode: undefined,
      costPrice: 150000,
      sellingPrice: 200000,
      minimumStock: 2,
      maximumStock: 20,
      reorderLevel: 5,
      status: "active",
      tags: ["projector", "electronics", "training"],
      metadata: {}
    },
    {
      id: "item_kit_workshop_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      sku: "KIT-AIWORKSHOP-001",
      name: "AI Workshop Kit",
      description: "Complete workshop kit for AI training",
      category: "Training Materials",
      unit: "kit",
      brand: "APPNEURAL",
      model: undefined,
      barcode: "KIT-2024-001",
      qrCode: undefined,
      costPrice: 250,
      sellingPrice: 500,
      minimumStock: 50,
      maximumStock: 500,
      reorderLevel: 100,
      status: "active",
      tags: ["workshop", "training", "kit"],
      metadata: {}
    },
    {
      id: "item_certificate_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      sku: "CERT-PAPER-A4-001",
      name: "Certificate Paper A4",
      description: "Premium certificate paper for printing certificates",
      category: "Office Supplies",
      unit: "ream",
      brand: "HP",
      model: "Premium",
      barcode: "1234567890125",
      qrCode: undefined,
      costPrice: 450,
      sellingPrice: 600,
      minimumStock: 20,
      maximumStock: 200,
      reorderLevel: 50,
      status: "active",
      tags: ["certificate", "paper", "office"],
      metadata: {}
    },
    {
      id: "item_camera_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      sku: "CAM-SONY-A7-001",
      name: "Sony Alpha A7 Camera",
      description: "Professional camera for content creation",
      category: "Electronics",
      unit: "piece",
      brand: "Sony",
      model: "Alpha A7 IV",
      barcode: "1234567890126",
      qrCode: undefined,
      costPrice: 180000,
      sellingPrice: 250000,
      minimumStock: 2,
      maximumStock: 15,
      reorderLevel: 5,
      status: "active",
      tags: ["camera", "electronics", "asset"],
      metadata: {}
    },
    {
      id: "item_chair_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      sku: "FURN-CHAIR-001",
      name: "Ergonomic Office Chair",
      description: "High-quality ergonomic chair for office",
      category: "Furniture",
      unit: "piece",
      brand: "Herman Miller",
      model: "Embody",
      barcode: "1234567890127",
      qrCode: undefined,
      costPrice: 45000,
      sellingPrice: 75000,
      minimumStock: 10,
      maximumStock: 100,
      reorderLevel: 25,
      status: "active",
      tags: ["chair", "furniture", "office"],
      metadata: {}
    },
    {
      id: "item_usb_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      sku: "ACC-USB-64GB-001",
      name: "USB Drive 64GB",
      description: "64GB USB flash drive for data storage",
      category: "Accessories",
      unit: "piece",
      brand: "SanDisk",
      model: "Ultra Flair",
      barcode: "1234567890128",
      qrCode: undefined,
      costPrice: 350,
      sellingPrice: 600,
      minimumStock: 30,
      maximumStock: 200,
      reorderLevel: 50,
      status: "active",
      tags: ["usb", "accessories", "storage"],
      metadata: {}
    },
    {
      id: "item_book_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      sku: "BOOK-JS-001",
      name: "JavaScript: The Good Parts",
      description: "Programming book for JavaScript training",
      category: "Books",
      unit: "piece",
      brand: "O'Reilly",
      model: undefined,
      barcode: "1234567890129",
      qrCode: undefined,
      costPrice: 450,
      sellingPrice: 750,
      minimumStock: 15,
      maximumStock: 100,
      reorderLevel: 30,
      status: "active",
      tags: ["book", "training", "programming"],
      metadata: {}
    }
  );

  state.warehouses.push(
    {
      id: "wh_udaipur_main",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      code: "UDAIPUR-MAIN",
      name: "Udaipur Main Office Store",
      description: "Primary inventory storage for Udaipur office",
      address: "123 Main Street",
      city: "Udaipur",
      state: "Rajasthan",
      country: "India",
      zipCode: "313001",
      managerId: undefined,
      capacity: 1000,
      status: "active",
      zones: [],
      metadata: {}
    },
    {
      id: "wh_jaipur_office",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      code: "JAIPUR-OFFICE",
      name: "Jaipur Branch Store",
      description: "Secondary inventory storage for Jaipur branch",
      address: "456 Market Road",
      city: "Jaipur",
      state: "Rajasthan",
      country: "India",
      zipCode: "302001",
      managerId: undefined,
      capacity: 500,
      status: "active",
      zones: [],
      metadata: {}
    },
    {
      id: "wh_training_center",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      code: "TRAINING-CENTER",
      name: "Training Center Materials Store",
      description: "Training materials and workshop kits storage",
      address: "789 Learning Lane",
      city: "Udaipur",
      state: "Rajasthan",
      country: "India",
      zipCode: "313002",
      managerId: undefined,
      capacity: 2000,
      status: "active",
      zones: [],
      metadata: {}
    }
  );

  state.stockLevels.push(
    {
      id: "stock_laptop_udaipur",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_laptop_001",
      warehouseId: "wh_udaipur_main",
      locationId: undefined,
      quantity: 25,
      reservedQuantity: 5,
      availableQuantity: 20,
      damagedQuantity: 0,
      expiredQuantity: 0,
      inTransitQuantity: 0,
      metadata: {}
    },
    {
      id: "stock_projector_udaipur",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_projector_001",
      warehouseId: "wh_udaipur_main",
      locationId: undefined,
      quantity: 8,
      reservedQuantity: 2,
      availableQuantity: 6,
      damagedQuantity: 0,
      expiredQuantity: 0,
      inTransitQuantity: 0,
      metadata: {}
    },
    {
      id: "stock_kit_workshop_training",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_kit_workshop_001",
      warehouseId: "wh_training_center",
      locationId: undefined,
      quantity: 180,
      reservedQuantity: 80,
      availableQuantity: 100,
      damagedQuantity: 5,
      expiredQuantity: 0,
      inTransitQuantity: 0,
      metadata: {}
    },
    {
      id: "stock_certificate_training",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_certificate_001",
      warehouseId: "wh_training_center",
      locationId: undefined,
      quantity: 15,
      reservedQuantity: 0,
      availableQuantity: 15,
      damagedQuantity: 0,
      expiredQuantity: 0,
      inTransitQuantity: 0,
      metadata: {}
    },
    {
      id: "stock_camera_udaipur",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_camera_001",
      warehouseId: "wh_udaipur_main",
      locationId: undefined,
      quantity: 6,
      reservedQuantity: 1,
      availableQuantity: 5,
      damagedQuantity: 0,
      expiredQuantity: 0,
      inTransitQuantity: 0,
      metadata: {}
    },
    {
      id: "stock_chair_udaipur",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_chair_001",
      warehouseId: "wh_udaipur_main",
      locationId: undefined,
      quantity: 45,
      reservedQuantity: 10,
      availableQuantity: 35,
      damagedQuantity: 2,
      expiredQuantity: 0,
      inTransitQuantity: 0,
      metadata: {}
    },
    {
      id: "stock_usb_udaipur",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_usb_001",
      warehouseId: "wh_udaipur_main",
      locationId: undefined,
      quantity: 120,
      reservedQuantity: 0,
      availableQuantity: 120,
      damagedQuantity: 0,
      expiredQuantity: 0,
      inTransitQuantity: 0,
      metadata: {}
    },
    {
      id: "stock_book_udaipur",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_book_001",
      warehouseId: "wh_udaipur_main",
      locationId: undefined,
      quantity: 65,
      reservedQuantity: 0,
      availableQuantity: 65,
      damagedQuantity: 0,
      expiredQuantity: 0,
      inTransitQuantity: 0,
      metadata: {}
    },
    {
      id: "stock_kit_workshop_jaipur",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_kit_workshop_001",
      warehouseId: "wh_jaipur_office",
      locationId: undefined,
      quantity: 60,
      reservedQuantity: 20,
      availableQuantity: 40,
      damagedQuantity: 0,
      expiredQuantity: 0,
      inTransitQuantity: 0,
      metadata: {}
    }
  );

  state.inwards.push(
    {
      id: "inward_kit_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_kit_workshop_001",
      warehouseId: "wh_training_center",
      locationId: undefined,
      referenceNumber: "PO-2024-001",
      sourceType: "purchase",
      sourceId: undefined,
      quantity: 200,
      unitCost: 250,
      totalCost: 50000,
      batchNumber: "BATCH-2024-01",
      expiryDate: undefined,
      receivedBy: "admin",
      notes: "Received from vendor",
      status: "received",
      metadata: {}
    },
    {
      id: "inward_certificate_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_certificate_001",
      warehouseId: "wh_training_center",
      locationId: undefined,
      referenceNumber: "PO-2024-002",
      sourceType: "purchase",
      sourceId: undefined,
      quantity: 50,
      unitCost: 450,
      totalCost: 22500,
      batchNumber: "BATCH-2024-02",
      expiryDate: undefined,
      receivedBy: "admin",
      notes: "Premium certificate paper",
      status: "received",
      metadata: {}
    }
  );

  state.outwards.push(
    {
      id: "outward_kit_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_kit_workshop_001",
      warehouseId: "wh_training_center",
      locationId: undefined,
      referenceNumber: "ISSUE-2024-001",
      destinationType: "issue",
      destinationId: undefined,
      quantity: 80,
      unitCost: 250,
      totalCost: 20000,
      issuedTo: "Batch AI-2024-05",
      issuedBy: "admin",
      approvedBy: "manager",
      notes: "Issued for upcoming workshop batch",
      status: "issued",
      metadata: {}
    },
    {
      id: "outward_laptop_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_laptop_001",
      warehouseId: "wh_udaipur_main",
      locationId: undefined,
      referenceNumber: "ASSET-ASSIGN-001",
      destinationType: "issue",
      destinationId: undefined,
      quantity: 5,
      unitCost: 85000,
      totalCost: 425000,
      issuedTo: "Employee Onboarding",
      issuedBy: "admin",
      approvedBy: "manager",
      notes: "Laptops assigned to new employees",
      status: "issued",
      metadata: {}
    }
  );

  state.adjustments.push(
    {
      id: "adj_damaged_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_kit_workshop_001",
      warehouseId: "wh_training_center",
      locationId: undefined,
      adjustmentType: "damage",
      quantity: 5,
      reason: "Damaged during handling",
      referenceNumber: "ADJ-2024-001",
      adjustedBy: "admin",
      approvedBy: "manager",
      notes: "Workshop kits damaged during storage",
      status: "applied",
      metadata: {}
    },
    {
      id: "adj_count_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_chair_001",
      warehouseId: "wh_udaipur_main",
      locationId: undefined,
      adjustmentType: "count",
      quantity: -2,
      reason: "Physical count variance",
      referenceNumber: "COUNT-2024-01",
      adjustedBy: "admin",
      approvedBy: "manager",
      notes: "Found 2 damaged chairs during stock count",
      status: "applied",
      metadata: {}
    }
  );

  state.transfers.push({
    id: "transfer_001",
    tenantId,
    createdAt,
    updatedAt: createdAt,
    referenceNumber: "TRF-20240523-trf001",
    fromWarehouseId: "wh_udaipur_main",
    fromLocationId: undefined,
    toWarehouseId: "wh_jaipur_office",
    toLocationId: undefined,
    status: "approved",
    requestedBy: "admin",
    approvedBy: "manager",
    receivedBy: undefined,
    items: [],
    notes: "Transfer workshop kits to Jaipur branch",
    metadata: {}
  });

  state.transferItems.push(
    {
      id: "trfitem_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      transferId: "transfer_001",
      itemId: "item_kit_workshop_001",
      quantity: 50,
      quantitySent: 50,
      quantityReceived: 0,
      unitCost: 250
    }
  );

  state.reorderRules.push(
    {
      id: "reorder_kit_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_kit_workshop_001",
      minimumQuantity: 50,
      reorderQuantity: 200,
      reorderPoint: 100,
      leadTimeDays: 7,
      preferredVendorId: undefined,
      autoReorder: true,
      status: "active",
      notes: "Standard reorder for workshop kits"
    },
    {
      id: "reorder_certificate_001",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      itemId: "item_certificate_001",
      minimumQuantity: 20,
      reorderQuantity: 100,
      reorderPoint: 50,
      leadTimeDays: 5,
      preferredVendorId: undefined,
      autoReorder: true,
      status: "active",
      notes: "Standard reorder for certificate paper"
    }
  );

  state.events.push({
    id: "evt_seed_bootstrap",
    tenantId,
    createdAt,
    updatedAt: createdAt,
    type: "inventory.seeded",
    source: "InventoryOS",
    data: { message: "InventoryOS demo data seeded" }
  });

  return state;
}
