import { DataStore } from "./core/datastore";
import { badRequest, conflict, notFound } from "./core/errors";
import { newId, nowIso } from "./core/id";
import { clone, ensureArray, ensureObject, ensureString, optionalObject, optionalString, pickQuery } from "./core/utils";
import { TaskEvent, TaskItem, TaskItemType, TaskOverview, TaskRun, RequestActor } from "./domain";

const allowedTypes: TaskItemType[] = ["Task", "TaskBoard", "Checklist", "TaskComment", "TaskDependency", "TaskReminder", "TaskApproval", "TaskSLA"];

export class TaskService {
  constructor(private readonly store: DataStore) {}
  getRoutesSummary(): string { return "TaskOS service is ready"; }
  overview(actor: RequestActor): TaskOverview { const state = this.store.getState(); const items = state.items.filter((item) => item.tenantId === actor.tenantId); const runs = state.runs.filter((run) => run.tenantId === actor.tenantId); const topTypes = allowedTypes.map((type) => ({ type, count: items.filter((item) => item.type === type).length })).filter((item) => item.count > 0); return { items: { total: items.length, active: items.filter((item) => item.status === "active").length, pendingReview: items.filter((item) => item.status === "pending_review").length, archived: items.filter((item) => item.status === "archived").length }, runs: { total: runs.length, queued: runs.filter((run) => run.status === "queued").length, running: runs.filter((run) => run.status === "running").length, completed: runs.filter((run) => run.status === "completed").length, failed: runs.filter((run) => run.status === "failed").length }, events: { total: state.events.filter((event) => event.tenantId === actor.tenantId).length }, topTypes }; }
  listItems(actor: RequestActor, query?: URLSearchParams): TaskItem[] { const search = pickQuery(query, "search")?.toLowerCase(); const status = pickQuery(query, "status"); const type = pickQuery(query, "type"); return clone(this.store.getState().items.filter((item) => { if (item.tenantId !== actor.tenantId) return false; if (status && item.status !== status) return false; if (type && item.type !== type) return false; if (search && !(item.key + " " + item.name + " " + (item.description ?? "")).toLowerCase().includes(search)) return false; return true; })); }
  getItem(id: string, actor: RequestActor): TaskItem { const item = this.store.getState().items.find((candidate) => candidate.id === id && candidate.tenantId === actor.tenantId); if (!item) notFound("Task item not found"); return clone(item); }
  createItem(input: unknown, actor: RequestActor): TaskItem { const body = ensureObject(input, "item"); const state = this.store.getState(); const key = ensureString(body.key, "item.key"); if (state.items.some((item) => item.tenantId === actor.tenantId && item.key === key)) conflict("Item key '" + key + "' already exists"); const type = this.parseType(body.type); const now = nowIso(); const item: TaskItem = { id: newId("task"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, key, name: ensureString(body.name, "item.name"), description: optionalString(body.description), type, status: String(body.status ?? "draft") as any, ownerId: optionalString(body.ownerId), tags: ensureArray<string>(body.tags, "item.tags").map(String), attributes: optionalObject(body.attributes), metadata: optionalObject(body.metadata) }; state.items.push(item); this.store.save(); this.recordEvent(actor, "task.created", "TaskOS", item.id, { key: item.key, type: item.type }); this.store.audit(actor, "item.create", "item", item.id, undefined, item); return clone(item); }
  updateItem(id: string, input: unknown, actor: RequestActor): TaskItem { const body = ensureObject(input, "item"); const state = this.store.getState(); const item = state.items.find((candidate) => candidate.id === id && candidate.tenantId === actor.tenantId); if (!item) notFound("Task item not found"); const before = clone(item); if (body.name !== undefined) item.name = ensureString(body.name, "item.name"); if (body.description !== undefined) item.description = optionalString(body.description); if (body.type !== undefined) item.type = this.parseType(body.type); if (body.status !== undefined) item.status = String(body.status) as any; if (body.ownerId !== undefined) item.ownerId = optionalString(body.ownerId); if (body.tags !== undefined) item.tags = ensureArray<string>(body.tags, "item.tags").map(String); if (body.attributes !== undefined) item.attributes = optionalObject(body.attributes); if (body.metadata !== undefined) item.metadata = optionalObject(body.metadata); item.updatedAt = nowIso(); this.store.save(); this.recordEvent(actor, "task.updated", "TaskOS", item.id, { key: item.key, status: item.status }); this.store.audit(actor, "item.update", "item", item.id, before, item); return clone(item); }
  archiveItem(id: string, actor: RequestActor): TaskItem { return this.updateItem(id, { status: "archived" }, actor); }
  listRuns(actor: RequestActor): TaskRun[] { return clone(this.store.getState().runs.filter((run) => run.tenantId === actor.tenantId)); }
  createRun(input: unknown, actor: RequestActor): TaskRun { const body = ensureObject(input, "run"); const now = nowIso(); const run: TaskRun = { id: newId("run"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, itemId: optionalString(body.itemId), name: String(body.name ?? "TaskOS run"), status: "completed", input: optionalObject(body.input), output: { message: "TaskOS run completed", handledBy: "TaskService" }, startedAt: now, completedAt: now }; this.store.getState().runs.unshift(run); this.store.save(); this.recordEvent(actor, "task.run.completed", "TaskOS", run.itemId, { runId: run.id }); this.store.audit(actor, "run.create", "run", run.id, undefined, run); return clone(run); }
  listEvents(actor: RequestActor): TaskEvent[] { return clone(this.store.getState().events.filter((event) => event.tenantId === actor.tenantId)); }
  listAuditLogs(actor: RequestActor) { return clone(this.store.getState().auditLogs.filter((log) => log.tenantId === actor.tenantId)); }
  private parseType(value: unknown): TaskItemType { const type = ensureString(value ?? allowedTypes[0], "item.type") as TaskItemType; if (!allowedTypes.includes(type)) badRequest("item.type must be one of " + allowedTypes.join(", ")); return type; }
  private recordEvent(actor: RequestActor, type: string, source: string, itemId: string | undefined, payload: Record<string, unknown>): void { const now = nowIso(); this.store.getState().events.unshift({ id: newId("event"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, type, source, itemId, payload }); this.store.save(); }
}
