-- SalesOS PostgreSQL schema starter
create table sales_leads (id text primary key, tenant_id text not null, lead_number text not null, first_name text not null, last_name text not null, email text not null, phone text, company text, source text not null, status text not null, score numeric not null default 0, expected_value numeric not null default 0, currency text not null default 'INR', owner_id text, tags jsonb not null default '[]', notes text, converted_deal_id text, converted_at timestamptz, custom_fields jsonb not null default '{}', created_by text not null, created_at timestamptz not null, updated_at timestamptz not null);
create table sales_pipelines (id text primary key, tenant_id text not null, code text not null, name text not null, description text, is_default boolean not null default false, status text not null default 'active', created_by text not null, created_at timestamptz not null, updated_at timestamptz not null);
create table sales_pipeline_stages (id text primary key, tenant_id text not null, pipeline_id text not null references sales_pipelines(id), code text not null, name text not null, stage_order integer not null, probability numeric not null default 0, forecast_category text not null, status text not null default 'active', created_by text not null, created_at timestamptz not null, updated_at timestamptz not null);
create table sales_deals (id text primary key, tenant_id text not null, deal_number text not null, title text not null, account_name text not null, contact_name text, contact_email text, lead_id text, pipeline_id text not null references sales_pipelines(id), stage_id text not null references sales_pipeline_stages(id), owner_id text not null, value numeric not null default 0, currency text not null default 'INR', probability numeric not null default 0, forecast_category text not null, close_date date not null, status text not null default 'open', loss_reason text, tags jsonb not null default '[]', custom_fields jsonb not null default '{}', created_by text not null, won_at timestamptz, lost_at timestamptz, created_at timestamptz not null, updated_at timestamptz not null);
create table sales_products (id text primary key, tenant_id text not null, sku text not null, name text not null, description text, unit_price numeric not null default 0, currency text not null default 'INR', tax_rate numeric not null default 0, status text not null default 'active', created_by text not null, created_at timestamptz not null, updated_at timestamptz not null);
create table sales_quotes (id text primary key, tenant_id text not null, quote_number text not null, deal_id text not null references sales_deals(id), account_name text not null, contact_email text, status text not null default 'draft', currency text not null default 'INR', valid_until date not null, line_items jsonb not null default '[]', subtotal numeric not null default 0, discount_total numeric not null default 0, tax_total numeric not null default 0, total numeric not null default 0, terms text, created_by text not null, approved_by text, approved_at timestamptz, sent_at timestamptz, accepted_at timestamptz, rejected_at timestamptz, created_at timestamptz not null, updated_at timestamptz not null);
create table sales_proposals (id text primary key, tenant_id text not null, proposal_number text not null, deal_id text not null references sales_deals(id), quote_id text references sales_quotes(id), title text not null, summary text not null, content text not null, status text not null default 'draft', created_by text not null, sent_at timestamptz, accepted_at timestamptz, rejected_at timestamptz, created_at timestamptz not null, updated_at timestamptz not null);
create table sales_activities (id text primary key, tenant_id text not null, type text not null, subject text not null, related_type text not null, related_id text not null, owner_id text not null, due_at timestamptz, completed_at timestamptz, status text not null default 'planned', notes text, outcome text, created_by text not null, created_at timestamptz not null, updated_at timestamptz not null);
create table sales_forecasts (id text primary key, tenant_id text not null, period_start date not null, period_end date not null, currency text not null default 'INR', owner_id text, generated_by text not null, summary jsonb not null, created_at timestamptz not null, updated_at timestamptz not null);
create table sales_events (id text primary key, tenant_id text not null, event text not null, source text not null default 'SalesOS', actor_id text not null, data jsonb not null default '{}', created_at timestamptz not null, updated_at timestamptz not null);
create table sales_audit_logs (id text primary key, tenant_id text not null, actor_id text not null, role text not null, action text not null, entity_type text not null, entity_id text, before jsonb, after jsonb, created_at timestamptz not null, updated_at timestamptz not null);
create index idx_sales_leads_tenant_status on sales_leads(tenant_id, status);
create index idx_sales_deals_tenant_status on sales_deals(tenant_id, status);
create index idx_sales_deals_tenant_close_date on sales_deals(tenant_id, close_date);
create index idx_sales_quotes_tenant_status on sales_quotes(tenant_id, status);
create index idx_sales_activities_tenant_owner on sales_activities(tenant_id, owner_id);
