import { Config, ConfigState, EnvironmentConfig, FeatureFlag, RuntimeOverride, TenantSetting } from "./domain";
import { emptyState } from "./core/datastore";
import { nowIso } from "./core/id";

export function createSeedState(tenantId = "demo-tenant"): ConfigState {
  const state = emptyState();
  const createdAt = nowIso();

  state.configs.push(
    {
      id: "config_default_timezone",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "platform.default_timezone",
      name: "Default Timezone",
      description: "Default timezone for new tenants",
      value: "Asia/Kolkata",
      valueType: "string",
      environment: "global",
      scope: "global",
      status: "published",
      tags: ["platform", "locale", "default"],
      sensitive: false,
      approvalRequired: false,
      version: 1,
      createdBy: "seed"
    },
    {
      id: "config_default_currency",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "platform.default_currency",
      name: "Default Currency",
      description: "Default currency for new tenants",
      value: "INR",
      valueType: "string",
      environment: "global",
      scope: "global",
      status: "published",
      tags: ["platform", "billing", "default"],
      sensitive: false,
      approvalRequired: false,
      version: 1,
      createdBy: "seed"
    },
    {
      id: "config_default_ai_provider",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "platform.default_ai_provider",
      name: "Default AI Provider",
      description: "Default AI provider for platform",
      value: "azure-ai-foundry",
      valueType: "string",
      environment: "global",
      scope: "global",
      status: "published",
      tags: ["platform", "ai", "provider"],
      sensitive: false,
      approvalRequired: true,
      version: 1,
      createdBy: "seed"
    },
    {
      id: "config_file_upload_limit",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "careeros.resume_upload_max_mb",
      name: "Resume Upload Limit",
      description: "Maximum file size for resume uploads in CareerOS",
      value: 10,
      valueType: "number",
      environment: "global",
      scope: "module",
      moduleId: "careeros",
      status: "published",
      tags: ["careeros", "upload", "file"],
      schema: {
        type: "number",
        constraints: { min: 1, max: 50 }
      },
      defaultValue: 10,
      sensitive: false,
      approvalRequired: false,
      version: 2,
      createdBy: "seed",
      updatedBy: "seed"
    },
    {
      id: "config_cert_generation",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "learningos.enable_certificate_generation",
      name: "Enable Certificate Generation",
      description: "Enable certificate generation for LearningOS",
      value: true,
      valueType: "boolean",
      environment: "global",
      scope: "module",
      moduleId: "learningos",
      status: "published",
      tags: ["learningos", "certificate", "feature"],
      sensitive: false,
      approvalRequired: false,
      version: 1,
      createdBy: "seed"
    }
  );

  state.featureFlags.push(
    {
      id: "ff_ai_resume_matcher",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "enable_ai_resume_matcher",
      name: "AI Resume Matcher",
      description: "Enable AI-powered resume matching for CareerOS",
      enabled: true,
      environment: "staging",
      rolloutPercentage: 100,
      status: "active",
      killSwitch: false,
      tags: ["careeros", "ai", "feature"],
      createdBy: "seed",
      metadata: {
        moduleId: "careeros",
        rolloutStrategy: "percentage"
      }
    },
    {
      id: "ff_bulk_cert_gen",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "enable_bulk_certificate_generation",
      name: "Bulk Certificate Generation",
      description: "Enable bulk certificate generation for LearningOS",
      enabled: false,
      environment: "production",
      status: "draft",
      killSwitch: false,
      tags: ["learningos", "certificate", "bulk"],
      createdBy: "seed"
    },
    {
      id: "ff_new_billing_portal",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "enable_new_billing_portal",
      name: "New Billing Portal",
      description: "Enable new billing portal experience",
      enabled: true,
      environment: "staging",
      rolloutPercentage: 20,
      targetTenants: ["abc-institute", "demo-tenant"],
      targetPlans: ["enterprise"],
      status: "active",
      killSwitch: true,
      tags: ["billing", "portal", "ux"],
      createdBy: "seed"
    },
    {
      id: "ff_agent_workflows",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "enable_agent_workflows",
      name: "Agent Workflows",
      description: "Enable AI agent workflows for automation",
      enabled: true,
      environment: "development",
      rolloutPercentage: 100,
      targetRoles: ["ai_admin", "admin"],
      status: "active",
      killSwitch: false,
      tags: ["ai", "automation", "workflow"],
      createdBy: "seed"
    },
    {
      id: "ff_advanced_analytics",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "enable_advanced_analytics",
      name: "Advanced Analytics",
      description: "Enable advanced analytics dashboard",
      enabled: false,
      environment: "production",
      status: "draft",
      killSwitch: false,
      tags: ["analytics", "dashboard"],
      createdBy: "seed"
    },
    {
      id: "ff_whatsapp_notifications",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "enable_whatsapp_notifications",
      name: "WhatsApp Notifications",
      description: "Enable WhatsApp as notification channel",
      enabled: true,
      environment: "staging",
      status: "active",
      killSwitch: true,
      tags: ["notification", "whatsapp", "channel"],
      createdBy: "seed",
      metadata: {
        provider: "twilio"
      }
    },
    {
      id: "ff_enterprise_sso",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "enable_enterprise_sso",
      name: "Enterprise SSO",
      description: "Enable SAML/OIDC SSO for enterprise tenants",
      enabled: true,
      environment: "production",
      targetPlans: ["enterprise"],
      status: "active",
      killSwitch: false,
      tags: ["sso", "enterprise", "auth"],
      createdBy: "seed"
    },
    {
      id: "ff_beta_dashboard",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "enable_beta_dashboard",
      name: "Beta Dashboard",
      description: "Enable new beta version of dashboard",
      enabled: true,
      environment: "staging",
      rolloutPercentage: 5,
      targetRoles: ["admin", "owner"],
      status: "active",
      killSwitch: true,
      tags: ["dashboard", "beta", "ux"],
      createdBy: "seed"
    }
  );

  state.environmentConfigs.push(
    {
      id: "env_config_local",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "local_config",
      name: "Local Development Config",
      environment: "local",
      values: {
        api_base_url: "http://localhost:3000",
        debug_mode: true,
        log_level: "debug",
        ai_model: "mock",
        payment_mode: "test"
      },
      status: "active",
      tags: ["local", "development"],
      createdBy: "seed"
    },
    {
      id: "env_config_development",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "development_config",
      name: "Development Environment Config",
      environment: "development",
      values: {
        api_base_url: "https://dev.api.appneural.com",
        debug_mode: true,
        log_level: "debug",
        ai_model: "mock",
        payment_mode: "test",
        rate_limit_per_minute: 100
      },
      status: "active",
      tags: ["development"],
      createdBy: "seed"
    },
    {
      id: "env_config_staging",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "staging_config",
      name: "Staging Environment Config",
      environment: "staging",
      values: {
        api_base_url: "https://staging.api.appneural.com",
        debug_mode: false,
        log_level: "info",
        ai_model: "azure-openai",
        payment_mode: "test",
        rate_limit_per_minute: 500,
        webhook_url: "https://staging.appneural.com/webhooks"
      },
      status: "active",
      tags: ["staging"],
      createdBy: "seed"
    },
    {
      id: "env_config_production",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "production_config",
      name: "Production Environment Config",
      environment: "production",
      values: {
        api_base_url: "https://api.appneural.com",
        debug_mode: false,
        log_level: "warn",
        ai_model: "azure-openai",
        payment_mode: "live",
        rate_limit_per_minute: 1000,
        webhook_url: "https://appneural.com/webhooks"
      },
      status: "active",
      tags: ["production"],
      createdBy: "seed"
    }
  );

  state.tenantSettings.push(
    {
      id: "tenant_setting_abc_logo",
      tenantId: "abc-institute",
      createdAt,
      updatedAt: createdAt,
      key: "branding.logo",
      name: "Tenant Logo",
      value: "abc-logo.png",
      valueType: "string",
      category: "branding",
      status: "active",
      inherited: false,
      overrideGlobal: true,
      tags: ["branding", "logo"],
      createdBy: "seed"
    },
    {
      id: "tenant_setting_abc_color",
      tenantId: "abc-institute",
      createdAt,
      updatedAt: createdAt,
      key: "branding.primary_color",
      name: "Primary Brand Color",
      value: "#5289F2",
      valueType: "string",
      category: "branding",
      status: "active",
      inherited: false,
      overrideGlobal: true,
      tags: ["branding", "color"],
      createdBy: "seed"
    },
    {
      id: "tenant_setting_abc_timezone",
      tenantId: "abc-institute",
      createdAt,
      updatedAt: createdAt,
      key: "platform.timezone",
      name: "Tenant Timezone",
      value: "Asia/Kolkata",
      valueType: "string",
      category: "custom",
      status: "active",
      inherited: false,
      overrideGlobal: true,
      tags: ["platform", "locale"],
      createdBy: "seed"
    },
    {
      id: "tenant_setting_abc_enabled_modules",
      tenantId: "abc-institute",
      createdAt,
      updatedAt: createdAt,
      key: "modules.enabled",
      name: "Enabled Modules",
      value: ["LearningOS", "CareerOS", "NotificationOS"],
      valueType: "array",
      category: "feature",
      status: "active",
      inherited: false,
      overrideGlobal: true,
      tags: ["modules", "feature"],
      createdBy: "seed"
    },
    {
      id: "tenant_setting_demo_logo",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "branding.logo",
      name: "Demo Tenant Logo",
      value: "demo-logo.png",
      valueType: "string",
      category: "branding",
      status: "active",
      inherited: false,
      overrideGlobal: true,
      tags: ["branding", "logo"],
      createdBy: "seed"
    }
  );

  state.runtimeOverrides.push(
    {
      id: "runtime_ai_timeout",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "ai.model.timeout_ms",
      name: "AI Model Timeout",
      description: "Runtime override for AI model timeout",
      moduleId: "aios",
      target: "ai.model",
      value: 30000,
      valueType: "number",
      environment: "production",
      priority: 10,
      status: "active",
      createdBy: "seed"
    },
    {
      id: "runtime_workflow_retry",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "workflow.retry_count",
      name: "Workflow Retry Count",
      description: "Runtime override for workflow retry count",
      moduleId: "workflowos",
      target: "workflow.retry",
      value: 3,
      valueType: "number",
      environment: "staging",
      priority: 5,
      status: "active",
      createdBy: "seed"
    },
    {
      id: "runtime_notification_fallback",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "notification.fallback_channel",
      name: "Notification Fallback Channel",
      description: "Fallback channel when primary fails",
      target: "notification.fallback",
      value: "email",
      valueType: "string",
      environment: "production",
      priority: 15,
      status: "active",
      createdBy: "seed"
    },
    {
      id: "runtime_rate_limit",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      key: "api.rate_limit",
      name: "API Rate Limit",
      description: "Runtime override for API rate limit",
      target: "api.rate_limit",
      value: 1000,
      valueType: "number",
      environment: "production",
      priority: 20,
      status: "active",
      createdBy: "seed"
    },
    {
      id: "runtime_abc_fallback_model",
      tenantId: "abc-institute",
      createdAt,
      updatedAt: createdAt,
      key: "ai.model.fallback",
      name: "AI Fallback Model for ABC",
      description: "Fallback model for ABC Institute tenant",
      moduleId: "aios",
      target: "ai.model.fallback",
      value: "gpt-4",
      valueType: "string",
      environment: "production",
      priority: 10,
      status: "active",
      createdBy: "seed"
    }
  );

  state.auditLogs.push({
    id: "audit_seed_configos",
    tenantId,
    createdAt,
    updatedAt: createdAt,
    actorId: "seed",
    role: "admin",
    action: "seed",
    entityType: "ConfigOS",
    after: { message: "ConfigOS demo data seeded" }
  });

  return state;
}
