import { BillingState, BillingAccount, PricingPlan, Subscription, Invoice, Payment, CreditWallet, Coupon, TaxRule, UsageRecord } from "./domain";
import { newId, nowIso, plusDays, plusMonths } from "./core/id";

export function createSeedState(tenantId: string): BillingState {
  const now = nowIso();

  const accounts: BillingAccount[] = [
    {
      id: newId("acc"),
      tenantId,
      customerId: "cust_001",
      customerName: "Acme Corp",
      email: "billing@acme.com",
      phone: "+91-9876543210",
      companyName: "Acme Corporation",
      billingAddress: {
        line1: "123 Business Park",
        city: "Mumbai",
        state: "Maharashtra",
        postalCode: "400001",
        country: "India",
      },
      gstin: "27AAAAA0000A1Z5",
      currency: "INR",
      status: "active",
      taxExempt: false,
      notes: "Enterprise client",
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
    {
      id: newId("acc"),
      tenantId,
      customerId: "cust_002",
      customerName: "TechStart Inc",
      email: "accounts@techstart.io",
      phone: "+91-9876543211",
      companyName: "TechStart Inc",
      billingAddress: {
        line1: "456 Startup Hub",
        city: "Bangalore",
        state: "Karnataka",
        postalCode: "560001",
        country: "India",
      },
      gstin: "29BBBBBB0000B2Z6",
      currency: "INR",
      status: "active",
      taxExempt: false,
      notes: "SMB customer",
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
    {
      id: newId("acc"),
      tenantId,
      customerId: "cust_003",
      customerName: "Freelancer Pro",
      email: "pro@freelancer.dev",
      phone: "+91-9876543212",
      billingAddress: {
        line1: "789 Home Office",
        city: "Delhi",
        state: "Delhi",
        postalCode: "110001",
        country: "India",
      },
      currency: "INR",
      status: "trial",
      taxExempt: false,
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
  ];

  const plans: PricingPlan[] = [
    {
      id: newId("plan"),
      tenantId,
      key: "starter_monthly",
      name: "Starter Monthly",
      description: "Perfect for individuals and small teams",
      product: "CareerOS",
      status: "active",
      type: "starter",
      billingCycle: "monthly",
      price: 499,
      currency: "INR",
      trialDays: 14,
      features: [
        { key: "resumes", name: "Resume Management", description: "Manage up to 5 resumes", included: true, limit: 5 },
        { key: "jd_matches", name: "JD Matches", description: "20 JD matches per month", included: true, limit: 20, overage: 10 },
        { key: "ai_reports", name: "AI Reports", description: "5 AI improvement reports", included: true, limit: 5 },
        { key: "live_cv", name: "Live CV Link", included: true },
        { key: "analytics", name: "Basic Analytics", included: true },
      ],
      limits: [
        { key: "users", name: "Users", value: 1, unit: "users" },
        { key: "resumes", name: "Resumes", value: 5, unit: "resumes" },
        { key: "jd_matches", name: "JD Matches", value: 20, unit: "matches/month" },
      ],
      modules: ["careeros"],
      isPublic: true,
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
    {
      id: newId("plan"),
      tenantId,
      key: "professional_monthly",
      name: "Professional Monthly",
      description: "For growing professionals and teams",
      product: "CareerOS",
      status: "active",
      type: "professional",
      billingCycle: "monthly",
      price: 999,
      currency: "INR",
      trialDays: 14,
      features: [
        { key: "resumes", name: "Resume Management", description: "Unlimited resumes", included: true },
        { key: "jd_matches", name: "JD Matches", description: "100 JD matches per month", included: true, limit: 100, overage: 5 },
        { key: "ai_reports", name: "AI Reports", description: "20 AI improvement reports", included: true, limit: 20 },
        { key: "live_cv", name: "Live CV Links", included: true },
        { key: "analytics", name: "Advanced Analytics", included: true },
        { key: "custom_domain", name: "Custom Domain", included: true },
      ],
      limits: [
        { key: "users", name: "Users", value: 5, unit: "users" },
        { key: "resumes", name: "Resumes", value: -1, unit: "unlimited" },
        { key: "jd_matches", name: "JD Matches", value: 100, unit: "matches/month" },
      ],
      modules: ["careeros", "aiassistant"],
      isPublic: true,
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
    {
      id: newId("plan"),
      tenantId,
      key: "business_monthly",
      name: "Business Monthly",
      description: "For businesses and agencies",
      product: "CareerOS",
      status: "active",
      type: "business",
      billingCycle: "monthly",
      price: 2499,
      currency: "INR",
      trialDays: 14,
      features: [
        { key: "resumes", name: "Resume Management", description: "Unlimited resumes", included: true },
        { key: "jd_matches", name: "JD Matches", description: "Unlimited JD matches", included: true },
        { key: "ai_reports", name: "AI Reports", description: "Unlimited AI reports", included: true },
        { key: "live_cv", name: "Live CV Links", included: true },
        { key: "analytics", name: "Advanced Analytics", included: true },
        { key: "custom_domain", name: "Custom Domain", included: true },
        { key: "api_access", name: "API Access", included: true },
        { key: "white_label", name: "White Label", included: true },
      ],
      limits: [
        { key: "users", name: "Users", value: 25, unit: "users" },
        { key: "resumes", name: "Resumes", value: -1, unit: "unlimited" },
        { key: "jd_matches", name: "JD Matches", value: -1, unit: "unlimited" },
      ],
      modules: ["careeros", "aiassistant", "toolos", "integration"],
      isPublic: true,
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
    {
      id: newId("plan"),
      tenantId,
      key: "enterprise_yearly",
      name: "Enterprise Yearly",
      description: "Custom enterprise solution",
      product: "CareerOS",
      status: "active",
      type: "enterprise",
      billingCycle: "yearly",
      price: 19999,
      currency: "INR",
      trialDays: 30,
      features: [
        { key: "resumes", name: "Resume Management", description: "Unlimited resumes", included: true },
        { key: "jd_matches", name: "JD Matches", description: "Unlimited JD matches", included: true },
        { key: "ai_reports", name: "AI Reports", description: "Unlimited AI reports", included: true },
        { key: "live_cv", name: "Live CV Links", included: true },
        { key: "analytics", name: "Enterprise Analytics", included: true },
        { key: "custom_domain", name: "Custom Domain", included: true },
        { key: "api_access", name: "API Access", included: true },
        { key: "white_label", name: "White Label", included: true },
        { key: "sla", name: "SLA Support", included: true },
        { key: "dedicated_manager", name: "Dedicated Account Manager", included: true },
      ],
      limits: [
        { key: "users", name: "Users", value: -1, unit: "unlimited" },
        { key: "resumes", name: "Resumes", value: -1, unit: "unlimited" },
        { key: "jd_matches", name: "JD Matches", value: -1, unit: "unlimited" },
      ],
      modules: ["careeros", "aiassistant", "toolos", "integration", "custom"],
      isPublic: true,
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
  ];

  const subscriptions: Subscription[] = [
    {
      id: newId("sub"),
      tenantId,
      billingAccountId: accounts[0].id,
      planId: plans[2].id,
      status: "active",
      type: "monthly",
      billingCycle: "monthly",
      currentPeriodStart: plusDays(-15),
      currentPeriodEnd: plusDays(15),
      autoRenew: true,
      seatCount: 10,
      modules: ["careeros", "aiassistant", "toolos"],
      addons: [],
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
    {
      id: newId("sub"),
      tenantId,
      billingAccountId: accounts[1].id,
      planId: plans[1].id,
      status: "active",
      type: "monthly",
      billingCycle: "monthly",
      currentPeriodStart: plusDays(-20),
      currentPeriodEnd: plusDays(10),
      autoRenew: true,
      seatCount: 3,
      modules: ["careeros"],
      addons: [],
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
    {
      id: newId("sub"),
      tenantId,
      billingAccountId: accounts[2].id,
      planId: plans[0].id,
      status: "trial",
      type: "monthly",
      billingCycle: "monthly",
      currentPeriodStart: now,
      trialEnd: plusDays(14),
      autoRenew: true,
      seatCount: 1,
      modules: ["careeros"],
      addons: [],
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
  ];

  const invoices: Invoice[] = [
    {
      id: newId("inv"),
      tenantId,
      billingAccountId: accounts[0].id,
      subscriptionId: subscriptions[0].id,
      invoiceNumber: "INV-2024-001",
      status: "paid",
      type: "subscription",
      currency: "INR",
      issueDate: plusDays(-15),
      dueDate: plusDays(0),
      periodStart: plusDays(-15),
      periodEnd: plusDays(15),
      subtotal: 2499,
      discountAmount: 0,
      taxAmount: 450,
      totalAmount: 2949,
      amountPaid: 2949,
      amountDue: 0,
      items: [
        {
          id: newId("item"),
          description: "Business Monthly - Monthly Subscription",
          quantity: 1,
          unitPrice: 2499,
          totalAmount: 2499,
          taxRate: 18,
          taxAmount: 450,
          metadata: {},
        },
      ],
      paidAt: plusDays(-14),
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
    {
      id: newId("inv"),
      tenantId,
      billingAccountId: accounts[1].id,
      subscriptionId: subscriptions[1].id,
      invoiceNumber: "INV-2024-002",
      status: "pending",
      type: "subscription",
      currency: "INR",
      issueDate: plusDays(-20),
      dueDate: plusDays(10),
      periodStart: plusDays(-20),
      periodEnd: plusDays(10),
      subtotal: 999,
      discountAmount: 0,
      taxAmount: 180,
      totalAmount: 1179,
      amountPaid: 0,
      amountDue: 1179,
      items: [
        {
          id: newId("item"),
          description: "Professional Monthly - Monthly Subscription",
          quantity: 1,
          unitPrice: 999,
          totalAmount: 999,
          taxRate: 18,
          taxAmount: 180,
          metadata: {},
        },
      ],
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
  ];

  const payments: Payment[] = [
    {
      id: newId("pay"),
      tenantId,
      invoiceId: invoices[0].id,
      billingAccountId: accounts[0].id,
      amount: 2949,
      currency: "INR",
      status: "paid",
      gateway: "razorpay",
      gatewayTransactionId: "pay_razor_123",
      paymentDate: plusDays(-14),
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
  ];

  const wallets: CreditWallet[] = [
    {
      id: newId("wallet"),
      tenantId,
      billingAccountId: accounts[0].id,
      type: "ai_credits",
      balance: 5000,
      totalPurchased: 10000,
      totalUsed: 5000,
      autoRecharge: true,
      autoRechargeAmount: 5000,
      lowBalanceThreshold: 1000,
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
    {
      id: newId("wallet"),
      tenantId,
      billingAccountId: accounts[1].id,
      type: "ai_credits",
      balance: 2500,
      totalPurchased: 5000,
      totalUsed: 2500,
      autoRecharge: false,
      lowBalanceThreshold: 500,
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
  ];

  const coupons: Coupon[] = [
    {
      id: newId("coupon"),
      tenantId,
      code: "CAREER50",
      name: "50% Off CareerOS",
      description: "50% off for first-time customers",
      type: "percentage",
      value: 50,
      maxUses: 100,
      usedCount: 15,
      maxUsesPerUser: 1,
      validFrom: plusDays(-30),
      validUntil: plusDays(60),
      applicablePlans: ["starter_monthly", "professional_monthly"],
      applicableModules: ["careeros"],
      minOrderAmount: 499,
      status: "active",
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
    {
      id: newId("coupon"),
      tenantId,
      code: "FLAT200",
      name: "₹200 Off",
      description: "₹200 off on any plan",
      type: "fixed",
      value: 200,
      maxUses: 500,
      usedCount: 87,
      validFrom: plusDays(-60),
      validUntil: plusDays(30),
      applicablePlans: [],
      applicableModules: [],
      status: "active",
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
  ];

  const taxRules: TaxRule[] = [
    {
      id: newId("tax"),
      tenantId,
      name: "GST 18%",
      rate: 18,
      type: "percentage",
      country: "India",
      state: "Maharashtra",
      hsnCode: "998429",
      applicableTo: ["all"],
      isActive: true,
      priority: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: newId("tax"),
      tenantId,
      name: "GST 18% - Karnataka",
      rate: 18,
      type: "percentage",
      country: "India",
      state: "Karnataka",
      hsnCode: "998429",
      applicableTo: ["all"],
      isActive: true,
      priority: 1,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const usageRecords: UsageRecord[] = [
    {
      id: newId("usage"),
      tenantId,
      subscriptionId: subscriptions[0].id,
      billingAccountId: accounts[0].id,
      eventType: "ai_tokens",
      unit: "tokens",
      quantity: 50000,
      unitPrice: 0.001,
      totalAmount: 50,
      timestamp: plusDays(-1),
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
    {
      id: newId("usage"),
      tenantId,
      subscriptionId: subscriptions[0].id,
      billingAccountId: accounts[0].id,
      eventType: "jd_match",
      unit: "tool_runs",
      quantity: 25,
      unitPrice: 10,
      totalAmount: 250,
      timestamp: plusDays(-2),
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
    {
      id: newId("usage"),
      tenantId,
      subscriptionId: subscriptions[1].id,
      billingAccountId: accounts[1].id,
      eventType: "ai_tokens",
      unit: "tokens",
      quantity: 30000,
      unitPrice: 0.001,
      totalAmount: 30,
      timestamp: plusDays(-1),
      metadata: {},
      createdAt: now,
      updatedAt: now,
    },
  ];

  return {
    billingAccounts: accounts,
    pricingPlans: plans,
    subscriptions,
    trials: [],
    usageRecords,
    creditWallets: wallets,
    creditTransactions: [],
    invoices,
    invoiceItems: [],
    payments,
    paymentMethods: [],
    refunds: [],
    coupons,
    taxRules,
    dunningAttempts: [],
    revenueRecords: [],
    reconciliationRecords: [],
    auditLogs: [],
    events: [],
  };
}
