import { AnalyticsEngine } from "../engines/analytics-engine";
import { ForecastEngine } from "../engines/forecast-engine";
import { LeadScoringEngine } from "../engines/lead-scoring-engine";
import { QuoteEngine } from "../engines/quote-engine";
import { DataStore } from "../core/datastore";
import { EventBus } from "../core/event-bus";
import { badRequest, conflict, notFound } from "../core/errors";
import { newId, nowIso } from "../core/id";
import { assertDate, clone, numberOrZero, optionalString, requiredString } from "../core/utils";
import { ActivityStatus, ActivityType, CurrencyCode, Deal, DealStatus, EntityStatus, Forecast, ForecastCategory, Lead, LeadSource, LeadStatus, Pipeline, PipelineStage, Proposal, ProposalStatus, Quote, QuoteLineInput, QuoteStatus, RelatedType, RequestActor, SalesActivity, SalesProduct } from "../core/domain";

interface ListFilter { status?: string; ownerId?: string; pipelineId?: string; }
type LeadInput = Partial<Lead> & { firstName?: string; lastName?: string; email?: string; };
type DealInput = Partial<Deal> & { title?: string; accountName?: string; closeDate?: string; };
type QuoteInput = { dealId?: string; validUntil?: string; lineItems?: QuoteLineInput[]; terms?: string; currency?: CurrencyCode; contactEmail?: string; };

export class SalesService {
  constructor(private readonly store: DataStore, private readonly events: EventBus) {}

  overview(actor: RequestActor): unknown { const state = this.store.getState(); return { os: "SalesOS", tenantId: actor.tenantId, counts: { leads: this.tenant(state.leads, actor.tenantId).length, pipelines: this.tenant(state.pipelines, actor.tenantId).length, stages: this.tenant(state.pipelineStages, actor.tenantId).length, deals: this.tenant(state.deals, actor.tenantId).length, products: this.tenant(state.products, actor.tenantId).length, quotes: this.tenant(state.quotes, actor.tenantId).length, proposals: this.tenant(state.proposals, actor.tenantId).length, activities: this.tenant(state.activities, actor.tenantId).length, forecasts: this.tenant(state.forecasts, actor.tenantId).length }, analytics: AnalyticsEngine.calculate(state, actor.tenantId), recentEvents: this.tenant(state.events, actor.tenantId).slice(0, 10) }; }
  listAuditLogs(actor: RequestActor): unknown[] { return this.tenant(this.store.getState().auditLogs, actor.tenantId); }
  listEvents(actor: RequestActor): unknown[] { return this.tenant(this.store.getState().events, actor.tenantId); }

  listLeads(actor: RequestActor, filter: ListFilter = {}): Lead[] { return this.tenant(this.store.getState().leads, actor.tenantId).filter((lead) => !filter.status || lead.status === filter.status).filter((lead) => !filter.ownerId || lead.ownerId === filter.ownerId); }
  getLead(actor: RequestActor, id: string): Lead { return this.findById(this.store.getState().leads, actor.tenantId, id, "Lead"); }
  createLead(actor: RequestActor, input: LeadInput): Lead { const now = nowIso(); const source = (input.source ?? "web") as LeadSource; const expectedValue = numberOrZero(input.expectedValue); const tags = Array.isArray(input.tags) ? input.tags : []; const score = input.score !== undefined ? numberOrZero(input.score) : LeadScoringEngine.score({ source, company: input.company, expectedValue, email: input.email, tags }); const lead: Lead = { id: input.id ?? newId("lead"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, leadNumber: input.leadNumber ?? this.nextNumber("LEAD", this.store.getState().leads.length + 1), firstName: requiredString(input.firstName, "firstName"), lastName: requiredString(input.lastName, "lastName"), email: requiredString(input.email, "email"), phone: optionalString(input.phone), company: optionalString(input.company), source, status: (input.status ?? (score >= 70 ? "qualified" : "new")) as LeadStatus, score, expectedValue, currency: input.currency ?? "INR", ownerId: optionalString(input.ownerId) ?? actor.userId, tags, notes: optionalString(input.notes), customFields: input.customFields ?? {}, createdBy: actor.userId }; this.store.getState().leads.unshift(lead); this.store.save(); this.store.audit(actor, "lead.create", "Lead", lead.id, undefined, lead); this.events.emit(actor, "lead.created", { leadId: lead.id, status: lead.status, score: lead.score }); return clone(lead); }
  updateLeadStatus(actor: RequestActor, id: string, status: LeadStatus, notes?: string): Lead { const lead = this.getLead(actor, id); const before = clone(lead); lead.status = status; lead.updatedAt = nowIso(); if (notes) lead.notes = notes; this.store.save(); this.store.audit(actor, "lead.status.update", "Lead", lead.id, before, lead); this.events.emit(actor, "lead.status_updated", { leadId: lead.id, status }); return clone(lead); }
  qualifyLead(actor: RequestActor, id: string): Lead { return this.updateLeadStatus(actor, id, "qualified"); }
  convertLead(actor: RequestActor, id: string, input: { pipelineId?: string; stageId?: string; title?: string; closeDate?: string; value?: number; ownerId?: string } = {}): { lead: Lead; deal: Deal } { const lead = this.getLead(actor, id); if (lead.status === "converted") conflict("Lead is already converted", { convertedDealId: lead.convertedDealId }); const pipeline = input.pipelineId ? this.getPipeline(actor, input.pipelineId) : this.defaultPipeline(actor); const stage = input.stageId ? this.getPipelineStage(actor, input.stageId) : this.firstStage(actor, pipeline.id); const deal = this.createDeal(actor, { title: input.title ?? `${lead.company ?? `${lead.firstName} ${lead.lastName}`} opportunity`, accountName: lead.company ?? `${lead.firstName} ${lead.lastName}`, contactName: `${lead.firstName} ${lead.lastName}`, contactEmail: lead.email, leadId: lead.id, pipelineId: pipeline.id, stageId: stage.id, ownerId: input.ownerId ?? lead.ownerId ?? actor.userId, value: input.value ?? lead.expectedValue, currency: lead.currency, closeDate: input.closeDate ?? new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10), tags: lead.tags }); const before = clone(lead); lead.status = "converted"; lead.convertedDealId = deal.id; lead.convertedAt = nowIso(); lead.updatedAt = lead.convertedAt; this.store.save(); this.store.audit(actor, "lead.convert", "Lead", lead.id, before, lead); this.events.emit(actor, "lead.converted", { leadId: lead.id, dealId: deal.id }); return { lead: clone(lead), deal }; }

  listPipelines(actor: RequestActor): Pipeline[] { return this.tenant(this.store.getState().pipelines, actor.tenantId); }
  getPipeline(actor: RequestActor, id: string): Pipeline { return this.findById(this.store.getState().pipelines, actor.tenantId, id, "Pipeline"); }
  listPipelineStages(actor: RequestActor, pipelineId?: string): PipelineStage[] { return this.tenant(this.store.getState().pipelineStages, actor.tenantId).filter((stage) => !pipelineId || stage.pipelineId === pipelineId).sort((a, b) => a.order - b.order); }
  getPipelineStage(actor: RequestActor, id: string): PipelineStage { return this.findById(this.store.getState().pipelineStages, actor.tenantId, id, "Pipeline stage"); }
  createPipeline(actor: RequestActor, input: Partial<Pipeline>): Pipeline { const now = nowIso(); const pipeline: Pipeline = { id: input.id ?? newId("pipe"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, code: requiredString(input.code, "code"), name: requiredString(input.name, "name"), description: optionalString(input.description), isDefault: Boolean(input.isDefault), status: (input.status ?? "active") as EntityStatus, createdBy: actor.userId }; if (pipeline.isDefault) this.tenant(this.store.getState().pipelines, actor.tenantId).forEach((existing) => { existing.isDefault = false; existing.updatedAt = now; }); this.store.getState().pipelines.push(pipeline); this.store.save(); this.store.audit(actor, "pipeline.create", "Pipeline", pipeline.id, undefined, pipeline); this.events.emit(actor, "pipeline.created", { pipelineId: pipeline.id }); return clone(pipeline); }
  createPipelineStage(actor: RequestActor, input: Partial<PipelineStage> & { pipelineId?: string; code?: string; name?: string; order?: number }): PipelineStage { const pipelineId = requiredString(input.pipelineId, "pipelineId"); this.getPipeline(actor, pipelineId); const now = nowIso(); const stage: PipelineStage = { id: input.id ?? newId("stage"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, pipelineId, code: requiredString(input.code, "code"), name: requiredString(input.name, "name"), order: Number(input.order ?? this.listPipelineStages(actor, pipelineId).length + 1), probability: Math.max(0, Math.min(100, numberOrZero(input.probability))), forecastCategory: (input.forecastCategory ?? "pipeline") as ForecastCategory, status: (input.status ?? "active") as EntityStatus, createdBy: actor.userId }; this.store.getState().pipelineStages.push(stage); this.store.save(); this.store.audit(actor, "pipeline_stage.create", "PipelineStage", stage.id, undefined, stage); this.events.emit(actor, "pipeline_stage.created", { pipelineId, stageId: stage.id }); return clone(stage); }

  listDeals(actor: RequestActor, filter: ListFilter = {}): Deal[] { return this.tenant(this.store.getState().deals, actor.tenantId).filter((deal) => !filter.status || deal.status === filter.status).filter((deal) => !filter.ownerId || deal.ownerId === filter.ownerId).filter((deal) => !filter.pipelineId || deal.pipelineId === filter.pipelineId); }
  getDeal(actor: RequestActor, id: string): Deal { return this.findById(this.store.getState().deals, actor.tenantId, id, "Deal"); }
  createDeal(actor: RequestActor, input: DealInput): Deal { const pipeline = input.pipelineId ? this.getPipeline(actor, input.pipelineId) : this.defaultPipeline(actor); const stage = input.stageId ? this.getPipelineStage(actor, input.stageId) : this.firstStage(actor, pipeline.id); if (stage.pipelineId !== pipeline.id) badRequest("stageId must belong to pipelineId"); const now = nowIso(); const deal: Deal = { id: input.id ?? newId("deal"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, dealNumber: input.dealNumber ?? this.nextNumber("DEAL", this.store.getState().deals.length + 1), title: requiredString(input.title, "title"), accountName: requiredString(input.accountName, "accountName"), contactName: optionalString(input.contactName), contactEmail: optionalString(input.contactEmail), leadId: optionalString(input.leadId), pipelineId: pipeline.id, stageId: stage.id, ownerId: input.ownerId ?? actor.userId, value: numberOrZero(input.value), currency: input.currency ?? "INR", probability: input.probability !== undefined ? numberOrZero(input.probability) : stage.probability, forecastCategory: input.forecastCategory ?? stage.forecastCategory, closeDate: assertDate(input.closeDate, "closeDate").slice(0, 10), status: (input.status ?? "open") as DealStatus, lossReason: optionalString(input.lossReason), tags: Array.isArray(input.tags) ? input.tags : [], customFields: input.customFields ?? {}, createdBy: actor.userId }; this.store.getState().deals.unshift(deal); this.store.save(); this.store.audit(actor, "deal.create", "Deal", deal.id, undefined, deal); this.events.emit(actor, "deal.created", { dealId: deal.id, value: deal.value, stageId: deal.stageId }); return clone(deal); }
  moveDealStage(actor: RequestActor, id: string, stageId: string): Deal { const deal = this.getDeal(actor, id); const stage = this.getPipelineStage(actor, stageId); if (stage.pipelineId !== deal.pipelineId) badRequest("Stage belongs to a different pipeline"); const before = clone(deal); deal.stageId = stage.id; deal.probability = stage.probability; deal.forecastCategory = stage.forecastCategory; deal.updatedAt = nowIso(); this.store.save(); this.store.audit(actor, "deal.stage.move", "Deal", deal.id, before, deal); this.events.emit(actor, "deal.stage_changed", { dealId: deal.id, stageId: stage.id, probability: deal.probability }); return clone(deal); }
  markDealWon(actor: RequestActor, id: string, input: { stageId?: string; value?: number } = {}): Deal { const deal = this.getDeal(actor, id); const before = clone(deal); if (input.stageId) deal.stageId = this.getPipelineStage(actor, input.stageId).id; if (input.value !== undefined) deal.value = numberOrZero(input.value); deal.status = "won"; deal.probability = 100; deal.forecastCategory = "closed"; deal.wonAt = nowIso(); deal.updatedAt = deal.wonAt; this.store.save(); this.store.audit(actor, "deal.won", "Deal", deal.id, before, deal); this.events.emit(actor, "deal.won", { dealId: deal.id, value: deal.value, currency: deal.currency }); return clone(deal); }
  markDealLost(actor: RequestActor, id: string, reason: string): Deal { const deal = this.getDeal(actor, id); const before = clone(deal); deal.status = "lost"; deal.probability = 0; deal.forecastCategory = "omitted"; deal.lossReason = requiredString(reason, "reason"); deal.lostAt = nowIso(); deal.updatedAt = deal.lostAt; this.store.save(); this.store.audit(actor, "deal.lost", "Deal", deal.id, before, deal); this.events.emit(actor, "deal.lost", { dealId: deal.id, reason: deal.lossReason }); return clone(deal); }

  listProducts(actor: RequestActor): SalesProduct[] { return this.tenant(this.store.getState().products, actor.tenantId); }
  getProduct(actor: RequestActor, id: string): SalesProduct { return this.findById(this.store.getState().products, actor.tenantId, id, "Sales product"); }
  createProduct(actor: RequestActor, input: Partial<SalesProduct>): SalesProduct { const now = nowIso(); const product: SalesProduct = { id: input.id ?? newId("prod"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, sku: requiredString(input.sku, "sku"), name: requiredString(input.name, "name"), description: optionalString(input.description), unitPrice: numberOrZero(input.unitPrice), currency: input.currency ?? "INR", taxRate: numberOrZero(input.taxRate), status: (input.status ?? "active") as EntityStatus, createdBy: actor.userId }; this.store.getState().products.push(product); this.store.save(); this.store.audit(actor, "product.create", "SalesProduct", product.id, undefined, product); this.events.emit(actor, "product.created", { productId: product.id, sku: product.sku }); return clone(product); }

  listQuotes(actor: RequestActor, filter: ListFilter = {}): Quote[] { return this.tenant(this.store.getState().quotes, actor.tenantId).filter((quote) => !filter.status || quote.status === filter.status); }
  getQuote(actor: RequestActor, id: string): Quote { return this.findById(this.store.getState().quotes, actor.tenantId, id, "Quote"); }
  createQuote(actor: RequestActor, input: QuoteInput): Quote { const dealId = requiredString(input.dealId, "dealId"); const deal = this.getDeal(actor, dealId); const calculation = QuoteEngine.calculate(input.lineItems ?? [], this.tenant(this.store.getState().products, actor.tenantId)); const now = nowIso(); const quote: Quote = { id: newId("quote"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, quoteNumber: this.nextNumber("QUOTE", this.store.getState().quotes.length + 1), dealId: deal.id, accountName: deal.accountName, contactEmail: optionalString(input.contactEmail) ?? deal.contactEmail, status: "draft", currency: input.currency ?? deal.currency, validUntil: assertDate(input.validUntil, "validUntil").slice(0, 10), lineItems: calculation.lineItems, subtotal: calculation.subtotal, discountTotal: calculation.discountTotal, taxTotal: calculation.taxTotal, total: calculation.total, terms: optionalString(input.terms), createdBy: actor.userId }; this.store.getState().quotes.unshift(quote); this.store.save(); this.store.audit(actor, "quote.create", "Quote", quote.id, undefined, quote); this.events.emit(actor, "quote.created", { quoteId: quote.id, dealId: deal.id, total: quote.total }); return clone(quote); }
  approveQuote(actor: RequestActor, id: string): Quote { return this.setQuoteStatus(actor, id, "approved", { approvedBy: actor.userId, approvedAt: nowIso() }); }
  sendQuote(actor: RequestActor, id: string): Quote { return this.setQuoteStatus(actor, id, "sent", { sentAt: nowIso() }); }
  rejectQuote(actor: RequestActor, id: string): Quote { return this.setQuoteStatus(actor, id, "rejected", { rejectedAt: nowIso() }); }
  acceptQuote(actor: RequestActor, id: string, markDealWon = true): Quote { const quote = this.setQuoteStatus(actor, id, "accepted", { acceptedAt: nowIso() }); if (markDealWon) this.markDealWon(actor, quote.dealId, { value: quote.total }); return quote; }
  private setQuoteStatus(actor: RequestActor, id: string, status: QuoteStatus, patch: Partial<Quote>): Quote { const quote = this.getQuote(actor, id); const before = clone(quote); Object.assign(quote, patch, { status, updatedAt: nowIso() }); this.store.save(); this.store.audit(actor, `quote.${status}`, "Quote", quote.id, before, quote); this.events.emit(actor, `quote.${status}`, { quoteId: quote.id, dealId: quote.dealId, total: quote.total }); return clone(quote); }

  listProposals(actor: RequestActor, filter: ListFilter = {}): Proposal[] { return this.tenant(this.store.getState().proposals, actor.tenantId).filter((proposal) => !filter.status || proposal.status === filter.status); }
  getProposal(actor: RequestActor, id: string): Proposal { return this.findById(this.store.getState().proposals, actor.tenantId, id, "Proposal"); }
  createProposal(actor: RequestActor, input: Partial<Proposal> & { dealId?: string; title?: string; summary?: string; content?: string }): Proposal { const dealId = requiredString(input.dealId, "dealId"); this.getDeal(actor, dealId); if (input.quoteId) this.getQuote(actor, input.quoteId); const now = nowIso(); const proposal: Proposal = { id: input.id ?? newId("proposal"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, proposalNumber: input.proposalNumber ?? this.nextNumber("PROP", this.store.getState().proposals.length + 1), dealId, quoteId: optionalString(input.quoteId), title: requiredString(input.title, "title"), summary: requiredString(input.summary, "summary"), content: requiredString(input.content, "content"), status: (input.status ?? "draft") as ProposalStatus, createdBy: actor.userId }; this.store.getState().proposals.unshift(proposal); this.store.save(); this.store.audit(actor, "proposal.create", "Proposal", proposal.id, undefined, proposal); this.events.emit(actor, "proposal.created", { proposalId: proposal.id, dealId }); return clone(proposal); }
  sendProposal(actor: RequestActor, id: string): Proposal { return this.setProposalStatus(actor, id, "sent", { sentAt: nowIso() }); }
  acceptProposal(actor: RequestActor, id: string): Proposal { return this.setProposalStatus(actor, id, "accepted", { acceptedAt: nowIso() }); }
  rejectProposal(actor: RequestActor, id: string): Proposal { return this.setProposalStatus(actor, id, "rejected", { rejectedAt: nowIso() }); }
  private setProposalStatus(actor: RequestActor, id: string, status: ProposalStatus, patch: Partial<Proposal>): Proposal { const proposal = this.getProposal(actor, id); const before = clone(proposal); Object.assign(proposal, patch, { status, updatedAt: nowIso() }); this.store.save(); this.store.audit(actor, `proposal.${status}`, "Proposal", proposal.id, before, proposal); this.events.emit(actor, `proposal.${status}`, { proposalId: proposal.id, dealId: proposal.dealId }); return clone(proposal); }

  listActivities(actor: RequestActor, filter: ListFilter = {}): SalesActivity[] { return this.tenant(this.store.getState().activities, actor.tenantId).filter((activity) => !filter.status || activity.status === filter.status).filter((activity) => !filter.ownerId || activity.ownerId === filter.ownerId); }
  getActivity(actor: RequestActor, id: string): SalesActivity { return this.findById(this.store.getState().activities, actor.tenantId, id, "Activity"); }
  createActivity(actor: RequestActor, input: Partial<SalesActivity> & { type?: ActivityType; subject?: string; relatedType?: RelatedType; relatedId?: string }): SalesActivity { const now = nowIso(); const status = (input.status ?? (input.dueAt && Date.parse(input.dueAt) < Date.now() ? "overdue" : "planned")) as ActivityStatus; const activity: SalesActivity = { id: input.id ?? newId("act"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, type: (input.type ?? "task") as ActivityType, subject: requiredString(input.subject, "subject"), relatedType: (input.relatedType ?? "deal") as RelatedType, relatedId: requiredString(input.relatedId, "relatedId"), ownerId: input.ownerId ?? actor.userId, dueAt: optionalString(input.dueAt), status, notes: optionalString(input.notes), outcome: optionalString(input.outcome), createdBy: actor.userId }; this.store.getState().activities.unshift(activity); this.store.save(); this.store.audit(actor, "activity.create", "SalesActivity", activity.id, undefined, activity); this.events.emit(actor, "activity.created", { activityId: activity.id, relatedType: activity.relatedType, relatedId: activity.relatedId }); return clone(activity); }
  completeActivity(actor: RequestActor, id: string, outcome?: string): SalesActivity { const activity = this.getActivity(actor, id); const before = clone(activity); activity.status = "done"; activity.completedAt = nowIso(); activity.outcome = optionalString(outcome) ?? activity.outcome; activity.updatedAt = activity.completedAt; this.store.save(); this.store.audit(actor, "activity.complete", "SalesActivity", activity.id, before, activity); this.events.emit(actor, "activity.completed", { activityId: activity.id, outcome: activity.outcome }); return clone(activity); }

  listForecasts(actor: RequestActor): Forecast[] { return this.tenant(this.store.getState().forecasts, actor.tenantId); }
  createForecast(actor: RequestActor, input: { periodStart?: string; periodEnd?: string; currency?: CurrencyCode; ownerId?: string }): Forecast { const periodStart = assertDate(input.periodStart, "periodStart").slice(0, 10); const periodEnd = assertDate(input.periodEnd, "periodEnd").slice(0, 10); if (Date.parse(periodEnd) < Date.parse(periodStart)) badRequest("periodEnd must be after periodStart"); const currency = input.currency ?? "INR"; const summary = ForecastEngine.generate(this.tenant(this.store.getState().deals, actor.tenantId), periodStart, periodEnd, currency, input.ownerId); const now = nowIso(); const forecast: Forecast = { id: newId("forecast"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, periodStart, periodEnd, currency, ownerId: optionalString(input.ownerId), generatedBy: actor.userId, summary }; this.store.getState().forecasts.unshift(forecast); this.store.save(); this.store.audit(actor, "forecast.create", "Forecast", forecast.id, undefined, forecast); this.events.emit(actor, "forecast.created", { forecastId: forecast.id, periodStart, periodEnd, expectedRevenue: summary.expectedRevenue }); return clone(forecast); }

  private defaultPipeline(actor: RequestActor): Pipeline { const pipeline = this.tenant(this.store.getState().pipelines, actor.tenantId).find((candidate) => candidate.isDefault) ?? this.tenant(this.store.getState().pipelines, actor.tenantId)[0]; if (!pipeline) notFound("No pipeline exists for tenant"); return pipeline; }
  private firstStage(actor: RequestActor, pipelineId: string): PipelineStage { const stage = this.listPipelineStages(actor, pipelineId)[0]; if (!stage) notFound("No pipeline stage exists for pipeline", { pipelineId }); return stage; }
  private findById<T extends { id: string; tenantId: string }>(items: T[], tenantId: string, id: string, label: string): T { const item = items.find((candidate) => candidate.tenantId === tenantId && candidate.id === id); if (!item) notFound(`${label} not found`, { id }); return item; }
  private tenant<T extends { tenantId: string }>(items: T[], tenantId: string): T[] { return items.filter((item) => item.tenantId === tenantId); }
  private nextNumber(prefix: string, sequence: number): string { return `${prefix}-${String(sequence).padStart(4, "0")}`; }
}
