import { createServer } from "http";
import { DataStore, EventBus, Router } from "./core";
import { registerRoutes } from "./routes";
import { SecurityService } from "./security.service";
import { createSeedState } from "./seed-state";
const port = Number(process.env.PORT ?? 5400);
const dbFile = process.env.SECURITYOS_DB_FILE ?? "data/securityos.db.json";
const tenantId = process.env.DEFAULT_TENANT_ID ?? "demo-tenant";
const store = new DataStore(dbFile);
if (store.getState().identities.length === 0) store.reset(createSeedState(tenantId));
const router = registerRoutes(new Router(), new SecurityService(store, new EventBus(store)));
const server = createServer((req: any, res: any) => { router.handle(req, res); });
server.listen(port, () => { console.log(`SecurityOS running on http://localhost:${port}`); console.log(`Health: http://localhost:${port}/health`); console.log(`Docs:   http://localhost:${port}/docs`); });
