import { Router } from "./core";
import { docs } from "./docs";
import { SecurityService } from "./security.service";
const q = (query: any) => Object.fromEntries(query.entries());
export function registerRoutes(router: Router, service: SecurityService): Router {
  router.get("/health", () => ({ status: "ok", os: "SecurityOS" }));
  router.get("/docs", () => ({ ...docs, routes: router.listRoutes() }));
  router.get("/securityos/permissions", ({ actor }) => ({ role: actor.role, permissions: service.permissions(actor.role) }), "security.read");
  router.get("/securityos/overview", ({ actor }) => service.overview(actor), "security.read");
  router.get("/securityos/analytics", ({ actor }) => service.analytics(actor), "security.analytics.read");
  router.get("/securityos/identities", ({ actor, query }) => service.listIdentities(actor, q(query)), "security.identities.read");
  router.post("/securityos/identities", ({ actor, body }) => service.createIdentity(actor, body), "security.identities.write");
  router.get("/securityos/identities/:id", ({ actor, params }) => service.getIdentity(actor, params.id), "security.identities.read");
  router.put("/securityos/identities/:id", ({ actor, params, body }) => service.updateIdentity(actor, params.id, body), "security.identities.write");
  router.post("/securityos/identities/:id/status", ({ actor, params, body }) => service.setIdentityStatus(actor, params.id, body.status), "security.identities.write");
  router.post("/securityos/identities/:id/reset-mfa", ({ actor, params }) => service.resetMfa(actor, params.id), "security.identities.write");
  router.get("/securityos/roles", ({ actor, query }) => service.listRoles(actor, q(query)), "security.roles.read");
  router.post("/securityos/roles", ({ actor, body }) => service.createRole(actor, body), "security.roles.write");
  router.get("/securityos/roles/:id", ({ actor, params }) => service.getRole(actor, params.id), "security.roles.read");
  router.put("/securityos/roles/:id", ({ actor, params, body }) => service.updateRole(actor, params.id, body), "security.roles.write");
  router.post("/securityos/roles/:id/permissions", ({ actor, params, body }) => service.addPermission(actor, params.id, body.permission), "security.roles.write");
  router.post("/securityos/roles/:id/remove-permission", ({ actor, params, body }) => service.removePermission(actor, params.id, body.permission), "security.roles.write");
  router.get("/securityos/groups", ({ actor, query }) => service.listGroups(actor, q(query)), "security.groups.read");
  router.post("/securityos/groups", ({ actor, body }) => service.createGroup(actor, body), "security.groups.write");
  router.get("/securityos/groups/:id", ({ actor, params }) => service.getGroup(actor, params.id), "security.groups.read");
  router.post("/securityos/groups/:id/members", ({ actor, params, body }) => service.addGroupMember(actor, params.id, body.identityId), "security.groups.write");
  router.post("/securityos/groups/:id/remove-member", ({ actor, params, body }) => service.removeGroupMember(actor, params.id, body.identityId), "security.groups.write");
  router.post("/securityos/groups/:id/roles", ({ actor, params, body }) => service.assignRoleToGroup(actor, params.id, body.roleId), "security.groups.write");
  router.get("/securityos/assignments", ({ actor, query }) => service.listAssignments(actor, q(query)), "security.assignments.read");
  router.post("/securityos/assignments", ({ actor, body }) => service.createAssignment(actor, body), "security.assignments.write");
  router.post("/securityos/assignments/:id/revoke", ({ actor, params }) => service.revokeAssignment(actor, params.id), "security.assignments.write");
  router.get("/securityos/policies", ({ actor, query }) => service.listPolicies(actor, q(query)), "security.policies.read");
  router.post("/securityos/policies", ({ actor, body }) => service.createPolicy(actor, body), "security.policies.write");
  router.put("/securityos/policies/:id", ({ actor, params, body }) => service.updatePolicy(actor, params.id, body), "security.policies.write");
  router.post("/securityos/access/check", ({ actor, body }) => service.checkAccess(actor, body), "security.access.check");
  router.get("/securityos/sessions", ({ actor, query }) => service.listSessions(actor, q(query)), "security.sessions.read");
  router.post("/securityos/sessions", ({ actor, body }) => service.createSession(actor, body), "security.sessions.write");
  router.post("/securityos/sessions/:id/revoke", ({ actor, params }) => service.revokeSession(actor, params.id), "security.sessions.write");
  router.get("/securityos/api-keys", ({ actor, query }) => service.listApiKeys(actor, q(query)), "security.api_keys.read");
  router.post("/securityos/api-keys", ({ actor, body }) => service.createApiKey(actor, body), "security.api_keys.write");
  router.post("/securityos/api-keys/:id/revoke", ({ actor, params }) => service.revokeApiKey(actor, params.id), "security.api_keys.write");
  router.post("/securityos/api-keys/verify", ({ actor, body }) => service.verifyApiKey(actor, body.token), "security.api_keys.read");
  router.get("/securityos/secrets", ({ actor, query }) => service.listSecrets(actor, q(query)), "security.secrets.read");
  router.post("/securityos/secrets", ({ actor, body }) => service.createSecret(actor, body), "security.secrets.write");
  router.get("/securityos/secrets/:id", ({ actor, params }) => service.getSecret(actor, params.id), "security.secrets.read");
  router.post("/securityos/secrets/:id/reveal", ({ actor, params }) => service.revealSecret(actor, params.id), "security.secrets.reveal");
  router.post("/securityos/secrets/:id/rotate", ({ actor, params, body }) => service.rotateSecret(actor, params.id, body), "security.secrets.write");
  router.get("/securityos/secrets/:id/versions", ({ actor, params }) => service.secretVersions(actor, params.id), "security.secrets.read");
  router.get("/securityos/controls", ({ actor, query }) => service.listControls(actor, q(query)), "security.controls.read");
  router.post("/securityos/controls", ({ actor, body }) => service.createControl(actor, body), "security.controls.write");
  router.post("/securityos/controls/:id/status", ({ actor, params, body }) => service.updateControlStatus(actor, params.id, body), "security.controls.write");
  router.get("/securityos/evidence", ({ actor, query }) => service.listEvidence(actor, q(query)), "security.evidence.read");
  router.post("/securityos/evidence", ({ actor, body }) => service.createEvidence(actor, body), "security.evidence.write");
  router.get("/securityos/access-reviews", ({ actor, query }) => service.listAccessReviews(actor, q(query)), "security.reviews.read");
  router.post("/securityos/access-reviews", ({ actor, body }) => service.createAccessReview(actor, body), "security.reviews.write");
  router.post("/securityos/access-reviews/:id/decide", ({ actor, params, body }) => service.decideAccessReviewItem(actor, params.id, body), "security.reviews.write");
  router.post("/securityos/access-reviews/:id/complete", ({ actor, params }) => service.completeAccessReview(actor, params.id), "security.reviews.write");
  router.get("/securityos/findings", ({ actor, query }) => service.listFindings(actor, q(query)), "security.findings.read");
  router.post("/securityos/findings", ({ actor, body }) => service.createFinding(actor, body), "security.findings.write");
  router.post("/securityos/findings/:id/resolve", ({ actor, params, body }) => service.resolveFinding(actor, params.id, body), "security.findings.write");
  router.get("/securityos/events", ({ actor }) => service.eventsLog(actor), "security.events.read");
  router.get("/securityos/audit-logs", ({ actor }) => service.auditLogs(actor), "security.audit.read");
  return router;
}
