import { AccessDecision, AccessEngine, AccessReview, AnalyticsEngine, ApiKey, ApiRole, asArray, asBoolean, asNumber, clone, ComplianceControl, ComplianceEvidence, conflict, DataStore, EventBus, Identity, includesText, isExpired, listPermissions, newId, normalizeEmail, notFound, nowIso, optionalString, plusDays, RequestActor, requireString, RoleAssignment, Secret, SecretEngine, SecretVersion, SecurityFinding, SecurityGroup, SecurityPolicy, SecurityRole, SecuritySession, unique, badRequest } from "./core";

export class SecurityService {
  constructor(private readonly store: DataStore, private readonly events: EventBus) {}
  permissions(role: ApiRole): string[] { return listPermissions(role); }
  overview(actor: RequestActor): Record<string, unknown> { const s = this.store.getState(); return { name: "SecurityOS", tenantId: actor.tenantId, analytics: this.analytics(actor), counts: { identities: this.scoped(actor, s.identities).length, roles: this.scoped(actor, s.roles).length, groups: this.scoped(actor, s.groups).length, assignments: this.scoped(actor, s.assignments).length, policies: this.scoped(actor, s.policies).length, sessions: this.scoped(actor, s.sessions).length, apiKeys: this.scoped(actor, s.apiKeys).length, secrets: this.scoped(actor, s.secrets).length, controls: this.scoped(actor, s.controls).length, accessReviews: this.scoped(actor, s.accessReviews).length, findings: this.scoped(actor, s.findings).length }, openFindings: this.listFindings(actor, { status: "open" }).slice(0, 5), highRiskIdentities: this.listIdentities(actor).filter((i) => i.riskScore >= 70).slice(0, 5), recentEvents: this.scoped(actor, s.events).slice(0, 10), recentAuditLogs: this.scoped(actor, s.auditLogs).slice(0, 10) }; }
  analytics(actor: RequestActor): Record<string, unknown> { return AnalyticsEngine.calculate(this.store.getState(), actor.tenantId); }

  listIdentities(actor: RequestActor, filters: Record<string,string|undefined> = {}): Identity[] { const q = String(filters.q ?? filters.search ?? "").trim(); return this.scoped(actor, this.store.getState().identities).filter((i) => !filters.status || i.status === filters.status).filter((i) => !filters.type || i.identityType === filters.type).filter((i) => !q || includesText(i.email, q) || includesText(i.displayName, q)).sort((a,b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  getIdentity(actor: RequestActor, id: string): Identity { return clone(this.findIdentity(actor, id)); }
  createIdentity(actor: RequestActor, input: any): Identity { const email = normalizeEmail(input.email); this.ensureIdentityEmailUnique(actor.tenantId, email); const now = nowIso(); const identity: Identity = { id: input.id ?? newId("ident"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, email, displayName: requireString(input.displayName ?? input.name, "displayName"), identityType: input.identityType ?? input.type ?? "user", status: input.status ?? "active", mfaEnabled: asBoolean(input.mfaEnabled, false), lastLoginAt: optionalString(input.lastLoginAt), riskScore: asNumber(input.riskScore, 0), groups: unique(asArray<string>(input.groups)), metadata: input.metadata ?? {}, createdBy: actor.userId }; this.store.getState().identities.unshift(identity); this.commit(actor, "identity.created", "Identity", identity.id, undefined, identity, { identityId: identity.id, email: identity.email }); return clone(identity); }
  updateIdentity(actor: RequestActor, id: string, input: any): Identity { const identity = this.findIdentity(actor, id); const before = clone(identity); if (input.email !== undefined) { const email = normalizeEmail(input.email); if (email !== identity.email) this.ensureIdentityEmailUnique(actor.tenantId, email); identity.email = email; } identity.displayName = optionalString(input.displayName ?? input.name) ?? identity.displayName; identity.identityType = input.identityType ?? input.type ?? identity.identityType; identity.mfaEnabled = input.mfaEnabled === undefined ? identity.mfaEnabled : asBoolean(input.mfaEnabled); identity.riskScore = input.riskScore === undefined ? identity.riskScore : asNumber(input.riskScore); identity.groups = input.groups === undefined ? identity.groups : unique(asArray<string>(input.groups)); identity.metadata = input.metadata ?? identity.metadata; identity.updatedAt = nowIso(); this.commit(actor, "identity.updated", "Identity", identity.id, before, identity, { identityId: identity.id }); return clone(identity); }
  setIdentityStatus(actor: RequestActor, id: string, status: any): Identity { const identity = this.findIdentity(actor, id); const before = clone(identity); identity.status = requireString(status, "status") as Identity["status"]; identity.updatedAt = nowIso(); this.commit(actor, "identity.status_changed", "Identity", identity.id, before, identity, { identityId: identity.id, status: identity.status }); return clone(identity); }
  resetMfa(actor: RequestActor, id: string): Identity { const identity = this.findIdentity(actor, id); const before = clone(identity); identity.mfaEnabled = false; identity.riskScore = Math.min(100, identity.riskScore + 10); identity.updatedAt = nowIso(); this.commit(actor, "identity.mfa_reset", "Identity", identity.id, before, identity, { identityId: identity.id }); return clone(identity); }

  listRoles(actor: RequestActor, filters: Record<string,string|undefined> = {}): SecurityRole[] { const q = String(filters.q ?? "").trim(); return this.scoped(actor, this.store.getState().roles).filter((r) => !filters.status || r.status === filters.status).filter((r) => !q || includesText(r.name, q) || includesText(r.description, q)).map(clone); }
  getRole(actor: RequestActor, id: string): SecurityRole { return clone(this.findRole(actor, id)); }
  createRole(actor: RequestActor, input: any): SecurityRole { const name = requireString(input.name, "name"); this.ensureRoleNameUnique(actor.tenantId, name); const now = nowIso(); const role: SecurityRole = { id: input.id ?? newId("role"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, name, description: optionalString(input.description), permissions: unique(asArray<string>(input.permissions)), system: asBoolean(input.system, false), status: input.status ?? "active", createdBy: actor.userId }; this.store.getState().roles.unshift(role); this.commit(actor, "role.created", "SecurityRole", role.id, undefined, role, { roleId: role.id }); return clone(role); }
  updateRole(actor: RequestActor, id: string, input: any): SecurityRole { const role = this.findRole(actor, id); const before = clone(role); if (input.name !== undefined && String(input.name) !== role.name) { this.ensureRoleNameUnique(actor.tenantId, String(input.name)); role.name = requireString(input.name, "name"); } role.description = input.description === undefined ? role.description : optionalString(input.description); role.permissions = input.permissions === undefined ? role.permissions : unique(asArray<string>(input.permissions)); role.status = input.status ?? role.status; role.updatedAt = nowIso(); this.commit(actor, "role.updated", "SecurityRole", role.id, before, role, { roleId: role.id }); return clone(role); }
  addPermission(actor: RequestActor, id: string, permission: string): SecurityRole { const role = this.findRole(actor, id); const before = clone(role); role.permissions = unique([...role.permissions, requireString(permission, "permission")]); role.updatedAt = nowIso(); this.commit(actor, "role.permission_added", "SecurityRole", role.id, before, role, { roleId: role.id, permission }); return clone(role); }
  removePermission(actor: RequestActor, id: string, permission: string): SecurityRole { const role = this.findRole(actor, id); const before = clone(role); role.permissions = role.permissions.filter((p) => p !== permission); role.updatedAt = nowIso(); this.commit(actor, "role.permission_removed", "SecurityRole", role.id, before, role, { roleId: role.id, permission }); return clone(role); }

  listGroups(actor: RequestActor, filters: Record<string,string|undefined> = {}): SecurityGroup[] { const q = String(filters.q ?? "").trim(); return this.scoped(actor, this.store.getState().groups).filter((g) => !filters.status || g.status === filters.status).filter((g) => !q || includesText(g.name, q)).map(clone); }
  getGroup(actor: RequestActor, id: string): SecurityGroup { return clone(this.findGroup(actor, id)); }
  createGroup(actor: RequestActor, input: any): SecurityGroup { const name = requireString(input.name, "name"); this.ensureGroupNameUnique(actor.tenantId, name); const now = nowIso(); const group: SecurityGroup = { id: input.id ?? newId("group"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, name, description: optionalString(input.description), members: unique(asArray<string>(input.members)), roleIds: unique(asArray<string>(input.roleIds)), status: input.status ?? "active", createdBy: actor.userId }; group.members.forEach((id) => this.findIdentity(actor, id)); group.roleIds.forEach((id) => this.findRole(actor, id)); this.store.getState().groups.unshift(group); this.syncIdentityGroupMembership(actor, group); this.commit(actor, "group.created", "SecurityGroup", group.id, undefined, group, { groupId: group.id }); return clone(group); }
  addGroupMember(actor: RequestActor, groupId: string, identityId: string): SecurityGroup { const group = this.findGroup(actor, groupId); this.findIdentity(actor, identityId); const before = clone(group); group.members = unique([...group.members, identityId]); group.updatedAt = nowIso(); this.syncIdentityGroupMembership(actor, group); this.commit(actor, "group.member_added", "SecurityGroup", group.id, before, group, { groupId, identityId }); return clone(group); }
  removeGroupMember(actor: RequestActor, groupId: string, identityId: string): SecurityGroup { const group = this.findGroup(actor, groupId); const before = clone(group); group.members = group.members.filter((id) => id !== identityId); group.updatedAt = nowIso(); const identity = this.findIdentity(actor, identityId); identity.groups = identity.groups.filter((id) => id !== groupId); identity.updatedAt = nowIso(); this.commit(actor, "group.member_removed", "SecurityGroup", group.id, before, group, { groupId, identityId }); return clone(group); }
  assignRoleToGroup(actor: RequestActor, groupId: string, roleId: string): SecurityGroup { const group = this.findGroup(actor, groupId); this.findRole(actor, roleId); const before = clone(group); group.roleIds = unique([...group.roleIds, roleId]); group.updatedAt = nowIso(); this.commit(actor, "group.role_assigned", "SecurityGroup", group.id, before, group, { groupId, roleId }); return clone(group); }

  listAssignments(actor: RequestActor, filters: Record<string,string|undefined> = {}): RoleAssignment[] { return this.scoped(actor, this.store.getState().assignments).filter((a) => !filters.subjectId || a.subjectId === filters.subjectId).filter((a) => !filters.roleId || a.roleId === filters.roleId).filter((a) => !filters.status || a.status === filters.status).map(clone); }
  createAssignment(actor: RequestActor, input: any): RoleAssignment { const subjectType = requireString(input.subjectType, "subjectType") as RoleAssignment["subjectType"]; const subjectId = requireString(input.subjectId, "subjectId"); const roleId = requireString(input.roleId, "roleId"); if (subjectType === "identity") this.findIdentity(actor, subjectId); else if (subjectType === "group") this.findGroup(actor, subjectId); else badRequest("subjectType must be identity or group"); this.findRole(actor, roleId); const existing = this.scoped(actor, this.store.getState().assignments).find((a) => a.subjectType === subjectType && a.subjectId === subjectId && a.roleId === roleId && a.status === "active"); if (existing) conflict("Active role assignment already exists", { assignmentId: existing.id }); const now = nowIso(); const assignment: RoleAssignment = { id: input.id ?? newId("assign"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, subjectType, subjectId, roleId, scope: optionalString(input.scope), expiresAt: optionalString(input.expiresAt), status: "active", assignedBy: actor.userId }; this.store.getState().assignments.unshift(assignment); this.commit(actor, "assignment.created", "RoleAssignment", assignment.id, undefined, assignment, { assignmentId: assignment.id }); return clone(assignment); }
  revokeAssignment(actor: RequestActor, id: string): RoleAssignment { const assignment = this.findAssignment(actor, id); const before = clone(assignment); assignment.status = "revoked"; assignment.revokedAt = nowIso(); assignment.updatedAt = assignment.revokedAt; this.commit(actor, "assignment.revoked", "RoleAssignment", assignment.id, before, assignment, { assignmentId: assignment.id }); return clone(assignment); }

  listPolicies(actor: RequestActor, filters: Record<string,string|undefined> = {}): SecurityPolicy[] { const q = String(filters.q ?? "").trim(); return this.scoped(actor, this.store.getState().policies).filter((p) => !filters.effect || p.effect === filters.effect).filter((p) => !filters.status || p.status === filters.status).filter((p) => !q || includesText(p.name, q) || includesText(p.description, q)).sort((a,b) => b.priority - a.priority).map(clone); }
  createPolicy(actor: RequestActor, input: any): SecurityPolicy { const now = nowIso(); const policy: SecurityPolicy = { id: input.id ?? newId("policy"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, name: requireString(input.name, "name"), description: optionalString(input.description), effect: input.effect ?? "allow", subjectRoles: unique(asArray<string>(input.subjectRoles)), actions: unique(asArray<string>(input.actions)), resources: unique(asArray<string>(input.resources)), conditions: input.conditions ?? {}, priority: asNumber(input.priority, 0), status: input.status ?? "active", createdBy: actor.userId }; this.store.getState().policies.unshift(policy); this.commit(actor, "policy.created", "SecurityPolicy", policy.id, undefined, policy, { policyId: policy.id }); return clone(policy); }
  updatePolicy(actor: RequestActor, id: string, input: any): SecurityPolicy { const policy = this.findPolicy(actor, id); const before = clone(policy); policy.name = optionalString(input.name) ?? policy.name; policy.description = input.description === undefined ? policy.description : optionalString(input.description); policy.effect = input.effect ?? policy.effect; policy.subjectRoles = input.subjectRoles === undefined ? policy.subjectRoles : unique(asArray<string>(input.subjectRoles)); policy.actions = input.actions === undefined ? policy.actions : unique(asArray<string>(input.actions)); policy.resources = input.resources === undefined ? policy.resources : unique(asArray<string>(input.resources)); policy.conditions = input.conditions ?? policy.conditions; policy.priority = input.priority === undefined ? policy.priority : asNumber(input.priority); policy.status = input.status ?? policy.status; policy.updatedAt = nowIso(); this.commit(actor, "policy.updated", "SecurityPolicy", policy.id, before, policy, { policyId: policy.id }); return clone(policy); }
  checkAccess(actor: RequestActor, input: any): AccessDecision { const s = this.store.getState(); const decision = AccessEngine.evaluate({ subjectId: requireString(input.subjectId, "subjectId"), action: requireString(input.action, "action"), resource: requireString(input.resource, "resource"), identities: this.scoped(actor, s.identities), roles: this.scoped(actor, s.roles), groups: this.scoped(actor, s.groups), assignments: this.scoped(actor, s.assignments), policies: this.scoped(actor, s.policies) }); this.store.audit(actor, "access.checked", "AccessDecision", decision.subjectId, undefined, decision); this.events.emit(actor, "access.checked", { subjectId: decision.subjectId, action: decision.action, resource: decision.resource, allowed: decision.allowed }); return clone(decision); }

  listSessions(actor: RequestActor, filters: Record<string,string|undefined> = {}): SecuritySession[] { return this.scoped(actor, this.store.getState().sessions).filter((s) => !filters.identityId || s.identityId === filters.identityId).filter((s) => !filters.status || s.status === filters.status).map(clone); }
  createSession(actor: RequestActor, input: any): SecuritySession { const identityId = requireString(input.identityId, "identityId"); this.findIdentity(actor, identityId); const now = nowIso(); const session: SecuritySession = { id: input.id ?? newId("sess"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, identityId, status: "active", ipAddress: optionalString(input.ipAddress), userAgent: optionalString(input.userAgent), expiresAt: input.expiresAt ?? plusDays(asNumber(input.ttlDays, 7)) }; this.store.getState().sessions.unshift(session); const identity = this.findIdentity(actor, identityId); identity.lastLoginAt = now; identity.updatedAt = now; this.commit(actor, "session.created", "SecuritySession", session.id, undefined, session, { sessionId: session.id, identityId }); return clone(session); }
  revokeSession(actor: RequestActor, id: string): SecuritySession { const session = this.findSession(actor, id); const before = clone(session); session.status = "revoked"; session.revokedAt = nowIso(); session.updatedAt = session.revokedAt; this.commit(actor, "session.revoked", "SecuritySession", session.id, before, session, { sessionId: session.id }); return clone(session); }

  listApiKeys(actor: RequestActor, filters: Record<string,string|undefined> = {}): any[] { return this.scoped(actor, this.store.getState().apiKeys).filter((k) => !filters.ownerId || k.ownerId === filters.ownerId).filter((k) => !filters.status || k.status === filters.status).map((k) => this.safeApiKey(k)); }
  createApiKey(actor: RequestActor, input: any): Record<string,unknown> { const ownerId = requireString(input.ownerId, "ownerId"); this.findIdentity(actor, ownerId); const token = SecretEngine.randomToken("ak"); const now = nowIso(); const key: ApiKey = { id: input.id ?? newId("apikey"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, ownerId, name: requireString(input.name, "name"), keyPrefix: token.slice(0, 10), keyHash: SecretEngine.sha256(token), scopes: unique(asArray<string>(input.scopes)), status: "active", expiresAt: optionalString(input.expiresAt), createdBy: actor.userId }; this.store.getState().apiKeys.unshift(key); this.commit(actor, "api_key.created", "ApiKey", key.id, undefined, key, { apiKeyId: key.id, ownerId }); return { ...this.safeApiKey(key), secretToken: token, note: "Store this token now. Only the hash is stored in SecurityOS." }; }
  revokeApiKey(actor: RequestActor, id: string): any { const key = this.findApiKey(actor, id); const before = clone(key); key.status = "revoked"; key.revokedAt = nowIso(); key.updatedAt = key.revokedAt; this.commit(actor, "api_key.revoked", "ApiKey", key.id, before, key, { apiKeyId: key.id }); return this.safeApiKey(key); }
  verifyApiKey(actor: RequestActor, token: string): Record<string,unknown> { const hash = SecretEngine.sha256(requireString(token, "token")); const key = this.scoped(actor, this.store.getState().apiKeys).find((k) => k.keyHash === hash); if (!key || key.status !== "active" || isExpired(key.expiresAt)) return { valid: false }; key.lastUsedAt = nowIso(); key.updatedAt = key.lastUsedAt; this.store.save(); return { valid: true, apiKey: this.safeApiKey(key) }; }

  listSecrets(actor: RequestActor, filters: Record<string,string|undefined> = {}): any[] { const q = String(filters.q ?? "").trim(); return this.scoped(actor, this.store.getState().secrets).filter((s) => !filters.status || s.status === filters.status).filter((s) => !filters.environment || s.environment === filters.environment).filter((s) => !q || includesText(s.name, q)).map((s) => this.safeSecret(s)); }
  getSecret(actor: RequestActor, id: string): any { return this.safeSecret(this.findSecret(actor, id)); }
  createSecret(actor: RequestActor, input: any): any { const name = requireString(input.name, "name"); const environment = input.environment ?? "default"; this.ensureSecretNameUnique(actor.tenantId, name, environment); const value = requireString(input.value, "value"); const now = nowIso(); const secret: Secret = { id: input.id ?? newId("secret"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, name, description: optionalString(input.description), environment, encryptedValue: SecretEngine.seal(value), maskedValue: SecretEngine.mask(value), version: 1, tags: unique(asArray<string>(input.tags)), status: "active", createdBy: actor.userId }; const version: SecretVersion = { id: newId("secver"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, secretId: secret.id, version: 1, encryptedValue: secret.encryptedValue, maskedValue: secret.maskedValue, createdBy: actor.userId }; this.store.getState().secrets.unshift(secret); this.store.getState().secretVersions.unshift(version); this.commit(actor, "secret.created", "Secret", secret.id, undefined, secret, { secretId: secret.id, name: secret.name }); return this.safeSecret(secret); }
  revealSecret(actor: RequestActor, id: string): Record<string,unknown> { const secret = this.findSecret(actor, id); const value = SecretEngine.reveal(secret.encryptedValue); this.store.audit(actor, "secret.revealed", "Secret", secret.id, undefined, { id: secret.id, name: secret.name, environment: secret.environment, version: secret.version, value: "***redacted***" }); this.events.emit(actor, "secret.revealed", { secretId: secret.id, name: secret.name }); return { id: secret.id, name: secret.name, environment: secret.environment, version: secret.version, value }; }
  rotateSecret(actor: RequestActor, id: string, input: any): any { const secret = this.findSecret(actor, id); const before = clone(secret); const value = requireString(input.value, "value"); secret.version += 1; secret.encryptedValue = SecretEngine.seal(value); secret.maskedValue = SecretEngine.mask(value); secret.status = "active"; secret.rotatedAt = nowIso(); secret.updatedAt = secret.rotatedAt; const version: SecretVersion = { id: newId("secver"), tenantId: actor.tenantId, createdAt: secret.updatedAt, updatedAt: secret.updatedAt, secretId: secret.id, version: secret.version, encryptedValue: secret.encryptedValue, maskedValue: secret.maskedValue, createdBy: actor.userId }; this.store.getState().secretVersions.unshift(version); this.commit(actor, "secret.rotated", "Secret", secret.id, before, secret, { secretId: secret.id, version: secret.version }); return this.safeSecret(secret); }
  secretVersions(actor: RequestActor, id: string): any[] { this.findSecret(actor, id); return this.scoped(actor, this.store.getState().secretVersions).filter((v) => v.secretId === id).map(({ encryptedValue, ...safe }) => clone(safe)); }

  listControls(actor: RequestActor, filters: Record<string,string|undefined> = {}): ComplianceControl[] { return this.scoped(actor, this.store.getState().controls).filter((c) => !filters.framework || c.framework === filters.framework).filter((c) => !filters.status || c.status === filters.status).filter((c) => !filters.severity || c.severity === filters.severity).map(clone); }
  createControl(actor: RequestActor, input: any): ComplianceControl { const now = nowIso(); const control: ComplianceControl = { id: input.id ?? newId("ctrl"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, framework: requireString(input.framework, "framework"), code: requireString(input.code, "code"), title: requireString(input.title, "title"), description: optionalString(input.description), ownerId: optionalString(input.ownerId), status: input.status ?? "not_started", severity: input.severity ?? "medium", dueDate: optionalString(input.dueDate), evidenceIds: unique(asArray<string>(input.evidenceIds)), createdBy: actor.userId }; this.store.getState().controls.unshift(control); this.commit(actor, "control.created", "ComplianceControl", control.id, undefined, control, { controlId: control.id }); return clone(control); }
  updateControlStatus(actor: RequestActor, id: string, input: any): ComplianceControl { const control = this.findControl(actor, id); const before = clone(control); control.status = requireString(input.status, "status") as ComplianceControl["status"]; control.ownerId = optionalString(input.ownerId) ?? control.ownerId; control.dueDate = optionalString(input.dueDate) ?? control.dueDate; control.updatedAt = nowIso(); this.commit(actor, "control.status_updated", "ComplianceControl", control.id, before, control, { controlId: control.id, status: control.status }); return clone(control); }
  listEvidence(actor: RequestActor, filters: Record<string,string|undefined> = {}): ComplianceEvidence[] { return this.scoped(actor, this.store.getState().evidences).filter((e) => !filters.controlId || e.controlId === filters.controlId).map(clone); }
  createEvidence(actor: RequestActor, input: any): ComplianceEvidence { const controlId = requireString(input.controlId, "controlId"); const control = this.findControl(actor, controlId); const now = nowIso(); const evidence: ComplianceEvidence = { id: input.id ?? newId("evd"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, controlId, title: requireString(input.title, "title"), evidenceType: input.evidenceType ?? input.type ?? "document", uri: optionalString(input.uri), notes: optionalString(input.notes), uploadedBy: actor.userId }; this.store.getState().evidences.unshift(evidence); control.evidenceIds = unique([...control.evidenceIds, evidence.id]); control.updatedAt = now; this.commit(actor, "evidence.created", "ComplianceEvidence", evidence.id, undefined, evidence, { evidenceId: evidence.id, controlId }); return clone(evidence); }

  listAccessReviews(actor: RequestActor, filters: Record<string,string|undefined> = {}): AccessReview[] { return this.scoped(actor, this.store.getState().accessReviews).filter((r) => !filters.status || r.status === filters.status).map(clone); }
  createAccessReview(actor: RequestActor, input: any): AccessReview { const now = nowIso(); const assignments = this.scoped(actor, this.store.getState().assignments).filter((a) => a.status === "active" && a.subjectType === "identity"); const items = assignments.map((a) => ({ identityId: a.subjectId, roleId: a.roleId, assignmentId: a.id, status: "pending" as const })); const review: AccessReview = { id: input.id ?? newId("review"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, name: requireString(input.name, "name"), reviewerId: requireString(input.reviewerId ?? actor.userId, "reviewerId"), status: input.status ?? "active", dueAt: optionalString(input.dueAt), items: input.items ? asArray<any>(input.items) : items, createdBy: actor.userId }; this.store.getState().accessReviews.unshift(review); this.commit(actor, "access_review.created", "AccessReview", review.id, undefined, review, { reviewId: review.id }); return clone(review); }
  decideAccessReviewItem(actor: RequestActor, reviewId: string, input: any): AccessReview { const review = this.findAccessReview(actor, reviewId); const before = clone(review); const item = review.items.find((i) => i.identityId === requireString(input.identityId, "identityId") && i.roleId === requireString(input.roleId, "roleId")); if (!item) notFound("Access review item not found"); item.status = requireString(input.status, "status") as any; item.decisionBy = actor.userId; item.decisionAt = nowIso(); item.notes = optionalString(input.notes); if (item.status === "revoked" && item.assignmentId) this.revokeAssignment(actor, item.assignmentId); review.updatedAt = nowIso(); this.commit(actor, "access_review.item_decided", "AccessReview", review.id, before, review, { reviewId, status: item.status }); return clone(review); }
  completeAccessReview(actor: RequestActor, id: string): AccessReview { const review = this.findAccessReview(actor, id); const before = clone(review); review.status = "completed"; review.completedAt = nowIso(); review.updatedAt = review.completedAt; this.commit(actor, "access_review.completed", "AccessReview", review.id, before, review, { reviewId: review.id }); return clone(review); }

  listFindings(actor: RequestActor, filters: Record<string,string|undefined> = {}): SecurityFinding[] { const q = String(filters.q ?? "").trim(); return this.scoped(actor, this.store.getState().findings).filter((f) => !filters.status || f.status === filters.status).filter((f) => !filters.severity || f.severity === filters.severity).filter((f) => !filters.category || f.category === filters.category).filter((f) => !q || includesText(f.title, q)).map(clone); }
  createFinding(actor: RequestActor, input: any): SecurityFinding { const now = nowIso(); const finding: SecurityFinding = { id: input.id ?? newId("finding"), tenantId: actor.tenantId, createdAt: now, updatedAt: now, title: requireString(input.title, "title"), description: optionalString(input.description), category: input.category ?? "iam", severity: input.severity ?? "medium", status: input.status ?? "open", ownerId: optionalString(input.ownerId), createdBy: actor.userId }; this.store.getState().findings.unshift(finding); this.commit(actor, "finding.created", "SecurityFinding", finding.id, undefined, finding, { findingId: finding.id }); return clone(finding); }
  resolveFinding(actor: RequestActor, id: string, input: any = {}): SecurityFinding { const finding = this.findFinding(actor, id); const before = clone(finding); finding.status = input.status ?? "resolved"; finding.resolvedAt = nowIso(); finding.updatedAt = finding.resolvedAt; this.commit(actor, "finding.resolved", "SecurityFinding", finding.id, before, finding, { findingId: finding.id }); return clone(finding); }

  eventsLog(actor: RequestActor) { return this.scoped(actor, this.store.getState().events); }
  auditLogs(actor: RequestActor) { return this.scoped(actor, this.store.getState().auditLogs); }

  private safeSecret(secret: Secret): any { const { encryptedValue, ...safe } = secret; return clone(safe); }
  private safeApiKey(key: ApiKey): any { const { keyHash, ...safe } = key; return clone(safe); }
  private syncIdentityGroupMembership(actor: RequestActor, group: SecurityGroup): void { for (const identityId of group.members) { const identity = this.findIdentity(actor, identityId); identity.groups = unique([...identity.groups, group.id]); identity.updatedAt = nowIso(); } }
  private findIdentity(actor: RequestActor, id: string): Identity { return this.findOne(this.store.getState().identities, actor.tenantId, id, "Identity"); }
  private findRole(actor: RequestActor, id: string): SecurityRole { return this.findOne(this.store.getState().roles, actor.tenantId, id, "SecurityRole"); }
  private findGroup(actor: RequestActor, id: string): SecurityGroup { return this.findOne(this.store.getState().groups, actor.tenantId, id, "SecurityGroup"); }
  private findAssignment(actor: RequestActor, id: string): RoleAssignment { return this.findOne(this.store.getState().assignments, actor.tenantId, id, "RoleAssignment"); }
  private findPolicy(actor: RequestActor, id: string): SecurityPolicy { return this.findOne(this.store.getState().policies, actor.tenantId, id, "SecurityPolicy"); }
  private findSession(actor: RequestActor, id: string): SecuritySession { return this.findOne(this.store.getState().sessions, actor.tenantId, id, "SecuritySession"); }
  private findApiKey(actor: RequestActor, id: string): ApiKey { return this.findOne(this.store.getState().apiKeys, actor.tenantId, id, "ApiKey"); }
  private findSecret(actor: RequestActor, id: string): Secret { return this.findOne(this.store.getState().secrets, actor.tenantId, id, "Secret"); }
  private findControl(actor: RequestActor, id: string): ComplianceControl { return this.findOne(this.store.getState().controls, actor.tenantId, id, "ComplianceControl"); }
  private findAccessReview(actor: RequestActor, id: string): AccessReview { return this.findOne(this.store.getState().accessReviews, actor.tenantId, id, "AccessReview"); }
  private findFinding(actor: RequestActor, id: string): SecurityFinding { return this.findOne(this.store.getState().findings, actor.tenantId, id, "SecurityFinding"); }
  private findOne<T extends { id: string; tenantId: string }>(items: T[], tenantId: string, id: string, name: string): T { const item = items.find((x) => x.tenantId === tenantId && x.id === id); if (!item) notFound(`${name} not found`, { id }); return item; }
  private scoped<T extends { tenantId: string }>(actor: Pick<RequestActor,"tenantId">, items: T[]): T[] { return items.filter((item) => item.tenantId === actor.tenantId); }
  private ensureIdentityEmailUnique(tenantId: string, email: string): void { if (this.store.getState().identities.some((i) => i.tenantId === tenantId && i.email.toLowerCase() === email.toLowerCase())) conflict("Identity email must be unique", { email }); }
  private ensureRoleNameUnique(tenantId: string, name: string): void { if (this.store.getState().roles.some((r) => r.tenantId === tenantId && r.name.toLowerCase() === name.toLowerCase())) conflict("Role name must be unique", { name }); }
  private ensureGroupNameUnique(tenantId: string, name: string): void { if (this.store.getState().groups.some((g) => g.tenantId === tenantId && g.name.toLowerCase() === name.toLowerCase())) conflict("Group name must be unique", { name }); }
  private ensureSecretNameUnique(tenantId: string, name: string, environment: string): void { if (this.store.getState().secrets.some((s) => s.tenantId === tenantId && s.name.toLowerCase() === name.toLowerCase() && s.environment === environment && s.status !== "deleted")) conflict("Secret name must be unique per environment", { name, environment }); }
  private commit(actor: RequestActor, event: string, entityType: string, entityId: string, before: unknown, after: unknown, eventData: Record<string,unknown>): void { this.store.save(); this.store.audit(actor, event, entityType, entityId, before, after); this.events.emit(actor, event, eventData); }
}
