import { CommunityState } from "./domain";
import { emptyState } from "./core/datastore";
import { nowIso, plusDays } from "./core/id";

export function createSeedState(tenantId = "demo-tenant"): CommunityState {
  const state = emptyState();
  const createdAt = nowIso();

  state.communities.push({
    id: "comm_demo_1",
    tenantId,
    createdAt,
    updatedAt: createdAt,
    key: "appneural-developers",
    name: "APPNEURAL Developer Community",
    description: "Help developers learn AI, systems, automation, cloud, and product engineering",
    type: "developer",
    status: "active",
    category: "Technology",
    visibility: "public",
    memberCount: 3,
    ownerId: "user_ajay",
    metadata: { website: "https://appneural.com", location: "Remote" }
  });

  state.communities.push({
    id: "comm_demo_2",
    tenantId,
    createdAt,
    updatedAt: createdAt,
    key: "innovatewithajay",
    name: "InnovateWithAjay Workshop Community",
    description: "Community for workshop participants and alumni",
    type: "training",
    status: "active",
    category: "Education",
    visibility: "public",
    memberCount: 2,
    ownerId: "user_ajay",
    metadata: { website: "https://innovatewithajay.com" }
  });

  state.members.push(
    {
      id: "mem_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      userId: "user_ajay",
      displayName: "Ajay Prajapat",
      email: "ajay@appneural.com",
      avatar: "https://example.com/ajay.jpg",
      status: "active",
      role: "owner",
      joinedAt: createdAt,
      lastActiveAt: createdAt,
      engagementScore: 95,
      points: 1250,
      level: 5,
      badges: ["badge_first_post", "badge_contributor"],
      tags: ["ai", "cloud", "nodejs"],
      metadata: { title: "Founder & CEO", company: "APPNEURAL" }
    },
    {
      id: "mem_demo_2",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      userId: "user_sarah",
      displayName: "Sarah Chen",
      email: "sarah@example.com",
      avatar: "",
      status: "active",
      role: "moderator",
      joinedAt: createdAt,
      lastActiveAt: createdAt,
      engagementScore: 78,
      points: 680,
      level: 3,
      badges: ["badge_first_post"],
      tags: ["python", "data-science"],
      metadata: { title: "Senior Data Scientist" }
    },
    {
      id: "mem_demo_3",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      userId: "user_mike",
      displayName: "Mike Johnson",
      email: "mike@example.com",
      avatar: "",
      status: "active",
      role: "member",
      joinedAt: createdAt,
      lastActiveAt: createdAt,
      engagementScore: 45,
      points: 320,
      level: 2,
      badges: [],
      tags: ["react", "frontend"],
      metadata: { title: "Frontend Developer" }
    },
    {
      id: "mem_demo_4",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_2",
      userId: "user_ajay",
      displayName: "Ajay Prajapat",
      email: "ajay@appneural.com",
      avatar: "https://example.com/ajay.jpg",
      status: "active",
      role: "owner",
      joinedAt: createdAt,
      lastActiveAt: createdAt,
      engagementScore: 90,
      points: 1100,
      level: 5,
      badges: ["badge_workshop_graduate"],
      tags: ["ai", "cloud"],
      metadata: { title: "Founder & CEO" }
    },
    {
      id: "mem_demo_5",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_2",
      userId: "user_alex",
      displayName: "Alex Rivera",
      email: "alex@example.com",
      avatar: "",
      status: "active",
      role: "member",
      joinedAt: createdAt,
      lastActiveAt: createdAt,
      engagementScore: 65,
      points: 450,
      level: 3,
      badges: ["badge_first_post"],
      tags: ["javascript", "nodejs"],
      metadata: { title: "Full Stack Developer" }
    }
  );

  state.groups.push(
    {
      id: "grp_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      name: "React Learning Circle",
      description: "For React developers to share knowledge and projects",
      type: "interest",
      status: "active",
      memberCount: 2,
      ownerId: "user_ajay",
      metadata: {}
    },
    {
      id: "grp_demo_2",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      name: "Node.js Interview Prep Group",
      description: "Practice coding interviews and share resources",
      type: "topic",
      status: "active",
      memberCount: 1,
      ownerId: "user_sarah",
      metadata: {}
    },
    {
      id: "grp_demo_3",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_2",
      name: "Workshop Batch May 2026",
      description: "Participants from May 2026 workshop cohort",
      type: "batch",
      status: "active",
      memberCount: 2,
      ownerId: "user_ajay",
      metadata: {}
    }
  );

  state.posts.push(
    {
      id: "post_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      groupId: "grp_demo_1",
      authorId: "user_ajay",
      type: "text",
      title: "Welcome to APPNEURAL Developer Community!",
      content: "Excited to have everyone here! This community is for developers interested in AI, cloud, and product engineering. Feel free to introduce yourself and share what you're working on.",
      status: "active",
      likes: 12,
      comments: 5,
      views: 145,
      isPinned: true,
      isLocked: false,
      tags: ["welcome", "introduction"],
      metadata: {}
    },
    {
      id: "post_demo_2",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      authorId: "user_sarah",
      type: "question",
      title: "Best practices for deploying ML models?",
      content: "I'm working on deploying machine learning models and would love to hear about your experiences. What tools and platforms do you recommend for production deployments?",
      status: "active",
      likes: 8,
      comments: 12,
      views: 234,
      isPinned: false,
      isLocked: false,
      tags: ["machine-learning", "deployment", "devops"],
      metadata: {}
    },
    {
      id: "post_demo_3",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_2",
      authorId: "user_alex",
      type: "achievement",
      title: "Just completed the AI Agents Workshop!",
      content: "Had an amazing time learning about AI agents. Big thanks to Ajay and the team for putting together such a comprehensive workshop. Already built my first AI-powered task manager!",
      status: "active",
      likes: 15,
      comments: 8,
      views: 189,
      isPinned: false,
      isLocked: false,
      tags: ["workshop", "ai-agents", "achievement"],
      metadata: {}
    }
  );

  state.discussions.push(
    {
      id: "disc_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      authorId: "user_mike",
      title: "How to structure a Node.js backend for scalability?",
      content: "I'm building a backend service that needs to handle high traffic. Looking for advice on architecture patterns, database choices, and caching strategies.",
      category: "questions",
      status: "active",
      replies: 7,
      views: 312,
      isPinned: false,
      isLocked: false,
      isSolved: true,
      acceptedReplyId: "reply_demo_1",
      tags: ["nodejs", "architecture", "scalability"],
      metadata: {}
    },
    {
      id: "disc_demo_2",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      authorId: "user_sarah",
      title: "New AI Course: Advanced Prompt Engineering",
      content: "Excited to announce our new course on advanced prompt engineering techniques! Learn how to build better AI applications with optimized prompts.",
      category: "announcements",
      status: "active",
      replies: 15,
      views: 567,
      isPinned: true,
      isLocked: false,
      isSolved: false,
      tags: ["course", "ai", "prompt-engineering"],
      metadata: {}
    }
  );

  state.events.push(
    {
      id: "evt_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      organizerId: "user_ajay",
      title: "AI Agents Workshop",
      description: "Learn how to build AI agents from scratch. Hands-on session with real-world examples.",
      type: "workshop",
      status: "active",
      startDate: plusDays(14),
      endDate: plusDays(14),
      timezone: "UTC",
      location: "Online",
      isOnline: true,
      maxAttendees: 50,
      registeredCount: 32,
      attendedCount: 0,
      registrationRequired: true,
      tags: ["ai", "agents", "workshop"],
      metadata: {}
    },
    {
      id: "evt_demo_2",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      organizerId: "user_sarah",
      title: "Weekly Code Review Session",
      description: "Join us for weekly code reviews where we review community members' projects and provide feedback.",
      type: "community_call",
      status: "active",
      startDate: plusDays(3),
      timezone: "UTC",
      location: "Online",
      isOnline: true,
      maxAttendees: 20,
      registeredCount: 12,
      attendedCount: 0,
      registrationRequired: false,
      tags: ["code-review", "community"],
      metadata: {}
    },
    {
      id: "evt_demo_3",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_2",
      organizerId: "user_ajay",
      title: "May 2026 Workshop - AI Fundamentals",
      description: "Intensive 2-day workshop covering AI fundamentals, machine learning basics, and practical applications.",
      type: "bootcamp",
      status: "active",
      startDate: plusDays(7),
      endDate: plusDays(8),
      timezone: "UTC",
      location: "Online",
      isOnline: true,
      maxAttendees: 100,
      registeredCount: 87,
      attendedCount: 0,
      registrationRequired: true,
      tags: ["ai", "workshop", "fundamentals"],
      metadata: {}
    }
  );

  state.badges.push(
    {
      id: "badge_first_post",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      key: "first_post",
      name: "First Post",
      description: "Awarded for making your first post in the community",
      icon: "🎉",
      type: "achievement",
      points: 50,
      criteria: "Create your first post",
      status: "active",
      awardedCount: 3,
      metadata: {}
    },
    {
      id: "badge_contributor",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      key: "top_contributor",
      name: "Top Contributor",
      description: "Awarded to members who actively contribute to discussions",
      icon: "⭐",
      type: "contribution",
      points: 200,
      criteria: "Receive 50+ likes on posts",
      status: "active",
      awardedCount: 1,
      metadata: {}
    },
    {
      id: "badge_workshop_graduate",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_2",
      key: "workshop_graduate",
      name: "Workshop Graduate",
      description: "Awarded to participants who complete a workshop",
      icon: "🎓",
      type: "certificate",
      points: 150,
      criteria: "Attend and complete workshop",
      status: "active",
      awardedCount: 1,
      metadata: {}
    },
    {
      id: "badge_helpful_mentor",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      key: "helpful_mentor",
      name: "Helpful Mentor",
      description: "Awarded to members who help others in the community",
      icon: "🌟",
      type: "mentor",
      points: 300,
      criteria: "Help 10+ members with their questions",
      status: "active",
      awardedCount: 0,
      metadata: {}
    }
  );

  state.resources.push(
    {
      id: "res_demo_1",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      uploadedBy: "user_ajay",
      title: "Node.js Best Practices Guide",
      description: "Comprehensive guide on Node.js best practices for production applications",
      type: "guide",
      url: "https://docs.example.com/nodejs-best-practices",
      downloads: 145,
      status: "active",
      tags: ["nodejs", "best-practices", "backend"],
      accessLevel: "member",
      metadata: {}
    },
    {
      id: "res_demo_2",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_1",
      uploadedBy: "user_sarah",
      title: "Machine Learning Cheat Sheet",
      description: "Quick reference guide for common ML algorithms and techniques",
      type: "pdf",
      url: "https://resources.example.com/ml-cheatsheet.pdf",
      fileSize: 2048000,
      downloads: 89,
      status: "active",
      tags: ["machine-learning", "reference", "algorithms"],
      accessLevel: "public",
      metadata: {}
    },
    {
      id: "res_demo_3",
      tenantId,
      createdAt,
      updatedAt: createdAt,
      communityId: "comm_demo_2",
      uploadedBy: "user_ajay",
      title: "AI Agents Workshop Materials",
      description: "All materials from the AI Agents Workshop including slides, code examples, and exercises",
      type: "template",
      url: "https://resources.example.com/ai-workshop-materials.zip",
      fileSize: 15728640,
      downloads: 67,
      status: "active",
      tags: ["ai", "agents", "workshop", "materials"],
      accessLevel: "member",
      metadata: {}
    }
  );

  state.events.push({
    id: "cevt_demo_1",
    tenantId,
    createdAt,
    updatedAt: createdAt,
    type: "community.seeded",
    source: "CommunityOS",
    data: { message: "CommunityOS demo data seeded" }
  });

  return state;
}
