import { ResourceState } from "./domain";

export function seedState(): ResourceState {
  const now = new Date().toISOString();
  const tenantId = "demo-tenant";

  return {
    resources: [
      {
        id: "res_demo_001",
        tenantId,
        createdAt: now,
        updatedAt: now,
        name: "Node.js Developer - Ajay",
        category: "people",
        type: "Developer",
        status: "allocated",
        description: "Senior Node.js developer with 5 years of experience",
        skills: ["Node.js", "TypeScript", "NestJS", "PostgreSQL", "Docker"],
        capacity: {
          maxHoursPerDay: 8,
          maxHoursPerWeek: 40,
          maxHoursPerMonth: 160,
        },
        cost: {
          hourlyRate: 50,
          dailyRate: 400,
          monthlyRate: 8000,
          currency: "USD",
          billable: true,
        },
        location: "Udaipur, India",
        tags: ["developer", "backend", "nodejs"],
        metadata: { department: "Engineering", level: "senior" },
        createdBy: "admin-user",
      },
      {
        id: "res_demo_002",
        tenantId,
        createdAt: now,
        updatedAt: now,
        name: "React Developer - Priya",
        category: "people",
        type: "Developer",
        status: "available",
        description: "Frontend developer specializing in React and TypeScript",
        skills: ["React", "TypeScript", "Next.js", "CSS", "Tailwind"],
        capacity: {
          maxHoursPerDay: 8,
          maxHoursPerWeek: 40,
          maxHoursPerMonth: 160,
        },
        cost: {
          hourlyRate: 45,
          dailyRate: 360,
          monthlyRate: 7200,
          currency: "USD",
          billable: true,
        },
        location: "Mumbai, India",
        tags: ["developer", "frontend", "react"],
        metadata: { department: "Engineering", level: "mid" },
        createdBy: "admin-user",
      },
      {
        id: "res_demo_003",
        tenantId,
        createdAt: now,
        updatedAt: now,
        name: "AI Engineer - Rahul",
        category: "people",
        type: "AI Engineer",
        status: "available",
        description: "AI/ML engineer with expertise in LLM workflows and Azure AI",
        skills: ["Python", "LLM", "Azure AI Foundry", "LangChain", "Vector Databases"],
        capacity: {
          maxHoursPerDay: 8,
          maxHoursPerWeek: 40,
          maxHoursPerMonth: 160,
        },
        cost: {
          hourlyRate: 60,
          dailyRate: 480,
          monthlyRate: 9600,
          currency: "USD",
          billable: true,
        },
        location: "Bangalore, India",
        tags: ["developer", "ai", "ml"],
        metadata: { department: "Engineering", level: "senior" },
        createdBy: "admin-user",
      },
      {
        id: "res_demo_004",
        tenantId,
        createdAt: now,
        updatedAt: now,
        name: "Meeting Room A",
        category: "rooms",
        type: "Meeting Room",
        status: "available",
        description: "Large meeting room with projector and video conferencing",
        capacity: {
          maxUnits: 20,
          availableUnits: 20,
        },
        cost: {
          dailyRate: 100,
          currency: "USD",
          billable: true,
        },
        location: "Udaipur Office - Floor 2",
        tags: ["meeting", "conference", "presentation"],
        metadata: { facilities: ["projector", "video conferencing", "whiteboard"] },
        createdBy: "admin-user",
      },
      {
        id: "res_demo_005",
        tenantId,
        createdAt: now,
        updatedAt: now,
        name: "Training Room B",
        category: "rooms",
        type: "Training Room",
        status: "available",
        description: "Training room with 30 seats, projector, and audio system",
        capacity: {
          maxUnits: 30,
          availableUnits: 30,
        },
        cost: {
          dailyRate: 150,
          currency: "USD",
          billable: true,
        },
        location: "Udaipur Office - Floor 3",
        tags: ["training", "workshop", "presentation"],
        metadata: { facilities: ["projector", "audio system", "30 seats"] },
        createdBy: "admin-user",
      },
      {
        id: "res_demo_006",
        tenantId,
        createdAt: now,
        updatedAt: now,
        name: "Projector Canon X7",
        category: "equipment",
        type: "Projector",
        status: "available",
        description: "High-resolution projector for presentations and training",
        capacity: {
          maxUnits: 1,
          availableUnits: 1,
        },
        cost: {
          dailyRate: 50,
          currency: "USD",
          billable: true,
        },
        location: "Udaipur Office - Storage",
        tags: ["equipment", "presentation", "training"],
        metadata: { brand: "Canon", model: "X7" },
        createdBy: "admin-user",
      },
      {
        id: "res_demo_007",
        tenantId,
        createdAt: now,
        updatedAt: now,
        name: "MacBook Pro 16\"",
        category: "equipment",
        type: "Laptop",
        status: "available",
        description: "Apple MacBook Pro for development and design work",
        capacity: {
          maxUnits: 5,
          availableUnits: 5,
        },
        cost: {
          dailyRate: 30,
          currency: "USD",
          billable: true,
        },
        location: "Udaipur Office - Equipment Room",
        tags: ["equipment", "laptop", "development"],
        metadata: { brand: "Apple", model: "MacBook Pro 16\"", specs: "M3 Pro, 32GB RAM, 1TB SSD" },
        createdBy: "admin-user",
      },
      {
        id: "res_demo_008",
        tenantId,
        createdAt: now,
        updatedAt: now,
        name: "Figma Enterprise License",
        category: "licenses",
        type: "Software License",
        status: "available",
        description: "Figma enterprise license for design collaboration",
        capacity: {
          maxUnits: 10,
          availableUnits: 10,
        },
        cost: {
          monthlyRate: 500,
          currency: "USD",
          billable: true,
        },
        location: "Cloud",
        tags: ["license", "design", "saas"],
        metadata: { vendor: "Figma", plan: "Enterprise", seats: 10 },
        createdBy: "admin-user",
      },
      {
        id: "res_demo_009",
        tenantId,
        createdAt: now,
        updatedAt: now,
        name: "AWS Cloud Resources",
        category: "cloud",
        type: "Cloud Infrastructure",
        status: "allocated",
        description: "AWS EC2 and Lambda resources for production workloads",
        capacity: {
          maxHoursPerMonth: 744,
        },
        cost: {
          monthlyRate: 2000,
          currency: "USD",
          billable: true,
        },
        location: "AWS us-east-1",
        tags: ["cloud", "infrastructure", "aws"],
        metadata: { provider: "AWS", region: "us-east-1", services: ["EC2", "Lambda", "RDS", "S3"] },
        createdBy: "admin-user",
      },
      {
        id: "res_demo_010",
        tenantId,
        createdAt: now,
        updatedAt: now,
        name: "Company Car - Honda City",
        category: "vehicles",
        type: "Car",
        status: "available",
        description: "Company car for client visits and field operations",
        capacity: {
          maxUnits: 1,
          availableUnits: 1,
        },
        cost: {
          dailyRate: 80,
          currency: "USD",
          billable: true,
        },
        location: "Udaipur Office Parking",
        tags: ["vehicle", "car", "transport"],
        metadata: { brand: "Honda", model: "City", registration: "RJ27CA1234" },
        createdBy: "admin-user",
      },
    ],
    allocations: [
      {
        id: "alloc_demo_001",
        tenantId,
        createdAt: now,
        updatedAt: now,
        resourceId: "res_demo_001",
        allocationType: "project",
        projectId: "proj_website_redesign",
        startDate: new Date().toISOString().split("T")[0],
        endDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        allocationPercent: 60,
        hoursPerWeek: 24,
        status: "active",
        createdBy: "admin-user",
        notes: "Working on backend API development",
      },
      {
        id: "alloc_demo_002",
        tenantId,
        createdAt: now,
        updatedAt: now,
        resourceId: "res_demo_001",
        allocationType: "project",
        projectId: "proj_mobile_app",
        startDate: new Date().toISOString().split("T")[0],
        endDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        allocationPercent: 40,
        hoursPerWeek: 16,
        status: "active",
        createdBy: "admin-user",
        notes: "Consulting on backend architecture",
      },
    ],
    bookings: [
      {
        id: "book_demo_001",
        tenantId,
        createdAt: now,
        updatedAt: now,
        resourceId: "res_demo_004",
        bookingType: "room",
        requesterId: "admin-user",
        startDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        endDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        startTime: "10:00",
        endTime: "12:00",
        status: "confirmed",
        attendees: 15,
        purpose: "Sprint planning meeting",
        createdBy: "admin-user",
      },
      {
        id: "book_demo_002",
        tenantId,
        createdAt: now,
        updatedAt: now,
        resourceId: "res_demo_005",
        bookingType: "room",
        requesterId: "admin-user",
        startDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        startTime: "09:00",
        endTime: "17:00",
        status: "confirmed",
        attendees: 25,
        purpose: "React Workshop",
        createdBy: "admin-user",
      },
      {
        id: "book_demo_003",
        tenantId,
        createdAt: now,
        updatedAt: now,
        resourceId: "res_demo_006",
        bookingType: "device",
        requesterId: "admin-user",
        startDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        status: "confirmed",
        purpose: "For React Workshop presentations",
        createdBy: "admin-user",
      },
    ],
    availabilities: [],
    utilizations: [
      {
        id: "util_demo_001",
        tenantId,
        createdAt: now,
        updatedAt: now,
        resourceId: "res_demo_001",
        period: "monthly",
        periodStart: new Date().toISOString().split("T")[0],
        periodEnd: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        availableHours: 160,
        allocatedHours: 160,
        usedHours: 96,
        idleHours: 64,
        billableHours: 96,
        nonBillableHours: 0,
        utilizationPercent: 60,
        costPerHour: 50,
      },
      {
        id: "util_demo_002",
        tenantId,
        createdAt: now,
        updatedAt: now,
        resourceId: "res_demo_002",
        period: "monthly",
        periodStart: new Date().toISOString().split("T")[0],
        periodEnd: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        availableHours: 160,
        allocatedHours: 0,
        usedHours: 0,
        idleHours: 160,
        billableHours: 0,
        nonBillableHours: 0,
        utilizationPercent: 0,
        costPerHour: 45,
      },
    ],
    skills: [
      {
        id: "skill_demo_001",
        tenantId,
        createdAt: now,
        updatedAt: now,
        resourceId: "res_demo_001",
        skillName: "Node.js",
        proficiencyLevel: "expert",
        yearsOfExperience: 5,
        certifications: ["Node.js Certified Developer"],
        verified: true,
      },
      {
        id: "skill_demo_002",
        tenantId,
        createdAt: now,
        updatedAt: now,
        resourceId: "res_demo_001",
        skillName: "TypeScript",
        proficiencyLevel: "advanced",
        yearsOfExperience: 4,
        certifications: [],
        verified: true,
      },
      {
        id: "skill_demo_003",
        tenantId,
        createdAt: now,
        updatedAt: now,
        resourceId: "res_demo_002",
        skillName: "React",
        proficiencyLevel: "advanced",
        yearsOfExperience: 3,
        certifications: ["React Developer Certification"],
        verified: true,
      },
      {
        id: "skill_demo_004",
        tenantId,
        createdAt: now,
        updatedAt: now,
        resourceId: "res_demo_003",
        skillName: "LLM",
        proficiencyLevel: "expert",
        yearsOfExperience: 3,
        certifications: ["Azure AI Engineer Associate"],
        verified: true,
      },
    ],
    pools: [
      {
        id: "pool_demo_001",
        tenantId,
        createdAt: now,
        updatedAt: now,
        name: "Frontend Developers",
        description: "Pool of frontend developers for project allocation",
        poolType: "skill",
        resourceIds: ["res_demo_002"],
        ownerId: "admin-user",
        status: "active",
        createdBy: "admin-user",
      },
      {
        id: "pool_demo_002",
        tenantId,
        createdAt: now,
        updatedAt: now,
        name: "Backend Developers",
        description: "Pool of backend developers for project allocation",
        poolType: "skill",
        resourceIds: ["res_demo_001"],
        ownerId: "admin-user",
        status: "active",
        createdBy: "admin-user",
      },
      {
        id: "pool_demo_003",
        tenantId,
        createdAt: now,
        updatedAt: now,
        name: "Meeting Rooms",
        description: "Pool of available meeting rooms",
        poolType: "equipment",
        resourceIds: ["res_demo_004", "res_demo_005"],
        ownerId: "admin-user",
        status: "active",
        createdBy: "admin-user",
      },
    ],
    requests: [
      {
        id: "req_demo_001",
        tenantId,
        createdAt: now,
        updatedAt: now,
        requestType: "people",
        resourceName: "QA Engineer",
        skills: ["Playwright", "Jest", "Cypress"],
        quantity: 1,
        startDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        endDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        allocationPercent: 100,
        purpose: "Website testing and QA",
        projectId: "proj_website_redesign",
        status: "submitted",
        requestedBy: "admin-user",
      },
    ],
    maintenances: [
      {
        id: "maint_demo_001",
        tenantId,
        createdAt: now,
        updatedAt: now,
        resourceId: "res_demo_006",
        maintenanceType: "preventive",
        scheduledDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        description: "Quarterly projector bulb replacement and cleaning",
        cost: 100,
        status: "scheduled",
      },
    ],
    conflicts: [],
    events: [],
    auditLogs: [],
  };
}
